### ISSUE TITLE
Rethink graph augmentation

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#1208]
Can we get rid of our pileups from Caller?

Can we stop breaking nodes all the time in `vg genotype`'s augmented graph?

**Comment by adamnovak** [comment]
Maybe we should separate discovery and typing steps in the caller? And do typing first?

**Comment by edawson** [comment]
I think discovery should be the default because that's how most tools have historically worked, but I agree we should be able to do discovery and typing (+ phasing and genotyping) as individual steps in addition to having a streamline push-button option.

The variant recall stuff I did as an experiment would perform typing if an input VCF was provided. This is nice for a few reasons: 
  
- The output VCF structure can be stolen from the input VCF (no need to do left alignment, header is halfway there, etc)
- Users can provide a subset of their original VCF to type specific variants. This is useful if someone did something like build a pan-cancer graph but they want to type a patient for a suspected BRCA mutation.

My naive implementation was like 10X faster for the typing step than the SV discovery process from existing callers. This was inconveniently offset by a 10X increase in mapping time.
