### ISSUE TITLE
The mapping evaluation tests on Jenkins stopped producing run times

### ISSUE THREAD

**Issue by jeizenga** [vgteam/vg#1284]
Seems to have happened somewhere around 3 days ago, based on a cursory scan of the recent PRs.

See here with run times still around:
https://github.com/vgteam/vg/pull/1270

And here with the run times missing:
https://github.com/vgteam/vg/pull/1274

**Comment by glennhickey** [comment]
Weird, all the mapping logging information (where times are getting scraped
from) seems to have disappeared from the stderr dumps.  Indexing and
simulation and everything else is still there.  Will sort it out tomorrow.
The script is now writing a file with all the running times, so it'd be
better just to get the times from that instead of the logs.
