### ISSUE TITLE
`vg construct` error:  Assertion `chunk.left_ends.count(mutable_first_node->id()) == 1' failed.

### ISSUE THREAD

**Issue by evanbiederstedt** [vgteam/vg#1367]
I haven't seen this error elsewhere. 

I'm running `vg construct` on a valid VCF. 

    vg construct -r hg38.fa -v example.vcf > output.vg 

Here's the error I see:

```
vg: src/constructor.cpp:1030: vg::Constructor::construct_graph(std::__cxx11::string, FastaReference&, vg::VcfBuffer&, const std::vector<FastaReference*>&, std::function<void(vg::Graph&)>)::<lambda(vg::ConstructedChunk&)>: Assertion `chunk.left_ends.count(mutable_first_node->id()) == 1' failed.
Got signal 6
Manual stack trace:
Stack trace from backtrace() for signal 6:
[0x92bb5a]
=================
[0x92beb5]
=================
[0xc667b0]
=================
[0xc6677e]
=================
[0x107ba2a]
=================
[0x1076668]
=================
[0x10766ce]
=================
[0x8560d4]
=================
[0x856eb9]
=================
[0x85808b]
=================
[0x7fcfa1]
=================
[0x7d1d28]
=================
[0x40532d]
=================
[0x10733a3]
=================
[0x107362e]
=================
[0x4c0ffa]
=================
```

Are there troubleshooting/debugging tips in this case? Thanks for any help!

**Comment by adamnovak** [comment]
The construction code is doing something wrong, and you're ending up with a chunk of graph that has multiple starting points when there should just be one.

I think I will have to go back through the construct code and try to work out how that could possibly happen. Do you have the VCF you are using handy?

**Comment by evanbiederstedt** [comment]
> Do you have the VCF you are using handy?

Sure, I'll e-mail you instructions how to download it from my server. Would that work?

**Comment by adamnovak** [comment]
Sure, that should be fine.

**Comment by evanbiederstedt** [comment]
messaged

**Comment by adamnovak** [comment]
OK, I can reproduce this problem. It's happening on chromosome 4, and the first variant in the offending chunk is this one:

```
chr4    9113428 .       CCAC    CA,CC,CCGC      .       PASS    .
```

Somehow, when that variant gets turned into graph material, the first node generated isn't that anchoring reference C node but an A. We do correctly record that the chunk should be attached by the C, but that C is the 3rd node instead of the first node in the chunk, so it's not trivially findable when the time comes to hook the chunk up, and the constructor bails out.

**Comment by adamnovak** [comment]
Here's the debug log for constructing that variant:

```
    Non-ref allele 0
    Non-ref allele 1
    Non-ref allele 2
    Edits run between 0 and 3
    Apply C ->  @ 9113428
    Ensure deletion arc 0 to 2
    Apply A -> A @ 9113429
    Created nodes running 2 to 2
    Apply C ->  @ 9113430
    Ensure deletion arc 2 to 4
    Apply CA ->  @ 9113428
    Ensure deletion arc 0 to 3
    Apply C -> C @ 9113430
    Created nodes running 3 to 3
    Apply C -> C @ 9113427
    Created nodes running 0 to 0
    Apply A -> G @ 9113429
    Created nodes running 2 to 2
    Apply C -> C @ 9113430
    Found existing nodes
    Created reference nodes running 1 to 1
```

The first node that gets created is that A node, because we do the aligned alts first, and since (I think) this variant is exactly at the start of the chunk, that ends up also being the first node in the chunk; there's no reference in-fill.

I'll just put in a linear scan for the left end node when we need it. It won't worsen the O() of the overall operation and it's easier than figuring out how to revise the construction to always generate that anchoring match first, or adding real indexing. Since it took so long to find this bug, the scan will almost always succeed on the first node, and it won't ever have to scan more than a variant's worth into the chunk.

**Comment by evanbiederstedt** [comment]
@adamnovak This should work on my VCF now?

**Comment by adamnovak** [comment]
Yes, I was able to build all of chromosome 4, which was the offending
segment previously. Give the current master vg version a try.
