### ISSUE TITLE
Error compiling in OSX

### ISSUE THREAD

**Issue by ifiddes-10x** [vgteam/vg#1373]
I followed the homebrew directions to try and compile on OSX High Sierra.

I am getting the following error:

```
cd ./deps/pinchesAndCacti && /Library/Developer/CommandLineTools/usr/bin/make 2>&1 | python /Users/ian.fiddes/vg/scripts/filter-noisy-assembler-warnings.py && cd /Users/ian.fiddes/vg/./deps/sonLib && cp lib/stPinchesAndCacti.a /Users/ian.fiddes/vg/lib/libpinchesandcacti.a && cp lib/3EdgeConnected.a /Users/ian.fiddes/vg/lib/lib3edgeconnected.a && mkdir -p /Users/ian.fiddes/vg/include/sonLib && cp lib/*.h /Users/ian.fiddes/vg/include/sonLib
cd externalTools && make all
cd threeEdgeConnected && /Library/Developer/CommandLineTools/usr/bin/make all
make[3]: Nothing to be done for `all'.
gcc is /usr/local/bin/gcc
gcc: error: is: No such file or directory
make[1]: *** [../sonLib/lib/stPinchesAndCacti.a] Error 1
make: *** [lib/libpinchesandcacti.a] Error 2
```

I am not sure why the makefile is leading to this `gcc: error: is: No such file or directory` line. I tried to follow the build into `sonLib` and build manually, but there is no target for the file `lib/libpinchesandcacti.a`.

**Comment by adamnovak** [comment]
It looks like the `gcc is /usr/local/bin/gcc` line, which is human-readable output from *something*, is somehow getting *executed*.

I think the problem is this line from `souce_me.sh`:

```
export CC=$(which gcc)
```

More specifically, I think you might somehow have a weird version of `which` installed that prints a human-readable "<whatever> is <path>", rather than just tersely outputting the path like we expect it to. That would account for this weird behavior, at least.

**Comment by ifiddes-10x** [comment]
I ended up following the directions more carefully and got it to build. I will note that building fails with GCC7, but using 6.4 from Homebrew worked.
