### ISSUE TITLE
compilation gmock not found despite being installed

### ISSUE THREAD

**Issue by colindaven** [vgteam/vg#1375]
Ubuntu 16.04, current clone from today

google-mock should probably be input into the required package lists. Even when it's present it is not found.

```
sudo apt-get install google-mock
Reading package lists... Done
Building dependency tree       
Reading state information... Done
google-mock is already the newest version (1.7.0-18092013-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

. ./source_me.sh &&  make static
if [ ! -d bin ]; then mkdir -p bin; fi
if [ ! -d lib ]; then mkdir -p lib; fi
if [ ! -d obj ]; then mkdir -p obj; fi
if [ ! -d obj/algorithms ]; then mkdir -p obj/algorithms; fi
if [ ! -d obj/unittest ]; then mkdir -p obj/unittest; fi
if [ ! -d obj/subcommand ]; then mkdir -p obj/subcommand; fi
if [ ! -d include ]; then mkdir -p include; fi
if [ ! -d cpp ]; then mkdir -p cpp; fi
rm -rf lib/libprotobuf* lib/libprotoc*
rm -Rf include/google/protobuf/
. ./source_me.sh && cd deps/protobuf && ./autogen.sh && export DIST_LANG=cpp && ./configure --prefix="/mnt/ngsnfs/tools/vg/vg"  && make  && make install && export PATH=/mnt/ngsnfs/tools/vg/vg/bin:$PATH
Google Mock not present.  Fetching gmock-1.7.0 from the web...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (77) error setting certificate verify locations:
  CAfile: /mnt/ngsnfs/tools/miniconda2/etc/pki/tls/certs/cacert.pem
  CApath: none
Makefile:189: recipe for target '.rebuild-protobuf' failed
make: *** [.rebuild-protobuf] Error 77
```

**Comment by adamnovak** [comment]
Not using the preinstalled Google Mock looks like an issue with Protobuf's build system. We're just going into Protobuf and calling the normal `./autogen.sh`, `./configure`, `make`, `make install` sequence. Its build system then decides that it wants Google Mock and doesn't seem to notice that you already have it.

The [Protobuf Readme](https://github.com/google/protobuf/blob/master/src/README.md) seems to suggest that Protobuf *can't* use a pre-installed version of gmock. It says that you *need* `curl` as a dependency for gmock downloading, gives an `apt-get install` line that doesn't include gmock, and talks about the release tarballs including a bundled gmock. If you want to get Protobuf to use your installed gmock, you probably need to open an enhancement request on the Protobuf github.

You also, however, seem to have a problem with the actual gmock download. You need to set up Curl so that it can download things, and specifically so that it can do:

```
curl -L -O https://github.com/google/googlemock/archive/release-1.7.0.zip
```

If that command fails, the build won't work. It looks like "miniconda2" may have reconfigured or misconfigured your Curl. Is the `/mnt/ngsnfs/tools/miniconda2/etc/pki/tls/certs/cacert.pem` file missing? Is it added to your environment variables as a place where Curl is being told to look?

**Comment by colindaven** [comment]
Thanks for that explanation of gmock - I didn't run into this error in the first compilation round but that was on an older server. I will set up the certificates correctly.

Edit: For others, this curl error can probably be solved by created a .curlrc

echo 'cacert=/etc/ssl/certs/ca-certificates.crt' > ~/.curlrc

Thanks

**Comment by colindaven** [comment]
I have to admit I haven't been a big fan of curl, wget has been much more effective for me to date ...
