### ISSUE TITLE
vg mpmap very slow on longer reads

### ISSUE THREAD

**Issue by glennhickey** [vgteam/vg#1434]
This came up while looking at #1417.  There's a link there to a fastq that contains reads of various sizes.  Aligning them single-endedq takes forever with mpmap.   

It looks like mpmap is on pace to take about 100 CPU hours to align the 1M read fastq.

**Comment by jeizenga** [comment]
I've investigated it a little bit, but I want to know more about the data. I'm pretty confident now that the cause is that there are very long unitigs (>5000 bp) that are not represented anywhere in the graph. I'm even willing to go a step further and say that no subsequence in them is present in the graph except by chance. Further still, this seems to be true of _every_ long unitig, even though they have high quality consensus base calls. Could it be that the graph has been subsetted for this example?

**Comment by ekg** [comment]
This is exactly the case. The unitigs are from a whole anopheles genome, while the reference file you have is only 3mb or so.
