### ISSUE TITLE
vg mpmap does not set pairing information in GAM

### ISSUE THREAD

**Issue by glennhickey** [vgteam/vg#1449]
when I run `vg mpmap -i -S -G reads.gam > out.gam` out.gam does not have the `fragment_next` and `fragment_prev` flags specified.

**Comment by jeizenga** [comment]
Yeah, I think the reason I didn't do this is that I didn't like the distinction between the two. They're two sides of a symmetric molecule, so having one be "previous" and the other "next" isn't a meaningful distinction. I've even noticed that the streaming functions sometimes swap the order, so that the read/2 comes before the read/1.

**Comment by glennhickey** [comment]
The order doesn't matter, at least as far as surject is using them to
validate pairings.  It's just important that consecutive reads are joined
somehow by a next/prev or prev/next relationship.  mpmap should still set
them, and debate about renaming these flags could be moved into its own
issue/pr.

**Comment by jeizenga** [comment]
Resolved in https://github.com/vgteam/vg/pull/1450
