### ISSUE TITLE
vg index/vg map problems: `GCSA::GCSA(): The input is too large, GCSA::GCSA(): Construction aborted`

### ISSUE THREAD

**Issue by evanbiederstedt** [vgteam/vg#1458]
This is the latest vg installation. Error with `vg index`. 

    vg index -p -t 10 -x myfile.xg -g myfile.gcsa -k 16 myfile.vg

Here's the output 

```
Built base XG index
Saving index to disk...
 loading graph                  [================================================================================]100.0%
InputGraph::InputGraph(): 9104263978 kmers in 1 file(s)
GCSA::GCSA(): The input is too large: 271.3 GB
GCSA::GCSA(): Construction aborted

```
which causes problems with mapping via `vg map`

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Need XG, GCSA, and LCP to create a Mapper
Got signal 6
Manual stack trace:
Stack trace from backtrace() for signal 6:
[0x92bb5a]
=================
[0x92beb5]
=================
[0xc667b0]
=================
[0xc6677e]
=================
[0x107ba2a]
=================
[0x103ca4d]
=================
[0xfb4076]
=================
[0xfb40c1]
=================
[0xfb4009]
=================
[0x76f635]
=================
[0x7d1d28]
=================
[0x40532d]
=================
[0x10733a3]
=================
[0x107362e]
=================
[0x4c0ffa]
=================

```

**Comment by ekg** [comment]
You can set a higher memory limit using the `-Z` parameter to `vg index`. For instance `vg index -p -t 10 -x myfile.xg -g myfile.gcsa -k 16 -Z 1000 myfile.vg` would do a terabyte max.

It's worth noting that this is a big input and it may grow exponentially through GCSA indexing.

What I'm typically doing now is using a pruning technique to reduce the graph complexity of the kmer input. You should see that the input size is much smaller, provided your large 16-mer input is caused by graph complexity.

First, reduce graph complexity using the non-trivial edge crossing heuristic. We remove edges which would allow a 16-mer to cross more than 3 "bifurcations" (non simple edges):

```
vg mod -pl 16 -e 3 myfile.vg >myfile.pruned.vg
```

Now we make kmers from the pruned graph (a deBruijn graph that's input to GCSA):

```
vg kmer -k 16 -gB myfile.prune.vg >myfile.prune.kmers
```

Then we make the GCSA2 index:

```
vg index -i myfile.prune.kmers -g myfile.gcsa -Z 1000 -p
```

The `-p` flag to index shows progress, which may be helpful to tell what's going on during the process.

Finally, we make the regular XG index from the non-pruned file. This is our reference system, but we've only indexed a subset of the graph that's not too complex for the GCSA2 indexer.

```
vg index -x myfile.xg myfile.vg
```

This pattern should be embedded properly in `vg index`, but it is not at the moment. Sorry for this confusion.

**Comment by evanbiederstedt** [comment]
@ekg Thanks for the help!

Let's keep this open for a few days as I try these out. I'll keep you updated.

**Comment by evanbiederstedt** [comment]
This is another memory error? 

```
        vg - use vg 1.6.1
Built base XG index
Saving index to disk...
 loading graph                  [=====================================================================================]100.0%
InputGraph::InputGraph(): 9104263978 kmers in 1 file(s)
InputGraph::read(): Read 9104263978 16-mers from .vg-kmers-tmp-XXiev9PV
InputGraph::readKeys(): 1624382686 unique keys
InputGraph::read(): Read 9104263978 16-mers from .vg-kmers-tmp-XXiev9PV
InputGraph::readFrom(): 6217635067 unique from nodes
InputGraph::read(): Read 9104263978 16-mers from .vg-kmers-tmp-XXiev9PV

DiskIO::write(): Write failed
```

I'm trying -Z 1000. I'll re-run with the print flag

**Comment by jltsiren** [comment]
@ekg  I'm going to simplify and document the indexing workflow as soon as I have good default parameters for `vg prune`.

@evanbiederstedt `DiskIO::write(): Write failed` typically means that you ran out of disk space. GCSA2 indexing writes many large temporary files. By default, it writes them to `/tmp`, but you can select another directory with `TMPDIR` environment variable.

The `-Z` parameter is really a safety mechanism. Without a size limit, index construction might accidentally use all your disk space and then crash if the graph is more complex than expected. Now it crashes when the size of the graph exceeds the specified limit. Because there are two graphs on disk at once, space usage can be up to 2x the limit.

In addition to the temporary graphs, the input kmers are also written to disk. They take 24 bytes/kmer, or about 200 gigabytes in you case. If you use `vg index` directly, the kmers will be written to the current working directory (I'm going to change this soon).

If the construction crashes, it usually leaves the temporary files on disk. As they take a lot of disk space, you should delete them immediately. The kmer files have names starting with `.vg-kmers-tmp-`, while the temporary graph file names start with `gcsa_`.

### Back to the issue at hand

The graph you are trying to index looks large. Because it's stored in a single file, the `-Z` parameter also acts as a memory limit. At certain points, index construction will load the temporary graph into memory. With `-Z 1000`, total memory usage may be over one terabyte.

GCSA2 construction uses a lot less memory, if you can partition the graph into disjoint subgraphs and store them in separate `.vg` files. This way, the indexing process only needs to load individual subgraphs into memory. For example, we have each chromosome in a separate file in the [1000GP example](https://github.com/vgteam/vg/wiki/working-with-a-whole-genome-variation-graph), and index construction only needs ~100 GB memory.
