### ISSUE TITLE
 vg construct clustal imports only first alignment block

### ISSUE THREAD

**Issue by ChriKub** [vgteam/vg#1578]
Hi @jeizenga,

I unfortunately have an issue with the vg construct clustal alignment import. (On a positive note, as far as I can judge, the fasta import is working like a charm.)
I'm trying to import a clustal alignment into vg. The file consists of several consecutive alignment blocks, but only the first one is read in and parsed. In addition, the node ids seem to be weirdly assigned. They start at 2 in every imported alignment.
I have uploaded a file to reproduce the issue [here](https://owncloud.tuebingen.mpg.de/index.php/s/op9iZeJlkag5LbY).

`vg construct -F clustal -M 214.1.genes.aln > 214.1.vg`

Thanks,
Chris

**Comment by jeizenga** [comment]
The node IDs beginning at 2 is something I know about. In fact, you should have one skipped node ID for each alignment block. It's a side-effect of an implementation decision I made, but I decided not to do anything about it since we don't promise any semantic meaning for node IDs. Is it causing you problems?

As for the clustal issue, the data I have here is to that MAF file I was working on parsing yesterday. Is that the data you meant to give me?

**Comment by ChriKub** [comment]
@jeizenga sorry, I copied the wrong link. [This](https://owncloud.tuebingen.mpg.de/index.php/s/rO3u8y9zGYRmrQ2) one is the correct one.
No, the node ID is not a problem, I was just wondering if there is any reason for it, and it confuses SequenceTubeMap.

**Comment by jeizenga** [comment]
Resolved in https://github.com/vgteam/vg/pull/1598
