### ISSUE TITLE
vg index uses a vg set, and can't read from stdin, but can't fully support multiple graphs either

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#1584]
`vg index` is one of the commands that uses a `VGset` of multiple graphs, referenced by file names on disk.

This means it can't read from standard input, but it ought to be able to operate on multiple vg files.

In https://github.com/vgteam/toil-vg/pull/469 there's a discussion of how, if we're doing haplotype indexing, vg index can't currently read from multiple vg files. Apparently the haplotype construction code isn't correct for that case, somehow. So the feature has been blocked off.

We either need to fix vg index to fully work with multiple files, or rip out the `VGset` and make it just consume a single vg file, possibly from standard input.

**Comment by jltsiren** [comment]
The root cause appears to be the use of `std::move()` in `vg_set.cpp`. We move the contents of protobuf objects, but there are still pointers to the contents somewhere else. A destructor gets called and the contents get deleted. As a result, the alt paths we get from XG construction are empty mappings, which means mappings of length 1 to node id 0. When we try to get edges for node 0 from XG, we get an SDSL assertion failure.

When I changed the move assignments to copy assignments and removed the check for the number of graph files, I was able to do the `vg index` tests for multiple graphs with haplotypes the way I originally intended. I'll create a pull request soon.
