### ISSUE TITLE
Json output format

### ISSUE THREAD

**Issue by TanyaDvorkina** [vgteam/vg#1592]
Hello,

We tried using vg to align Pacbio reads on an assembly graph of E.coli and got three types of records in the resulting json file:
1. Record with field “path” and positions in it.
2. Record with no “path” field.
3. Record that has “path” field, but it doesn’t contain any positions on the graph (node_id, offset etc.) Is it a secondary alignment? Sometimes it has a field issecondary and sometimes only secondary_score.

Could you please answer two questions regarding the output:

First, what is the difference between the last two types of records (unfortunately we couldn’t find a detailed description of vg json format)?

Second, the resulting paths are highly fragmented (e.g. multiple entries corresponding to consecutive alignments within a single node 33632 -- see the attachment). We could easily “merge” alignments to the single long node, but are afraid that some of the smaller nodes might be missing from the path. What settings (or post-processing) could you recommend to make the resulting paths more contiguous?

Many thanks in advance!

Current alignment json was produced as follows:
./vg view -vF graph > ograph.vg
./vg mod -X 1024 ograph.vg > split.vg
./vg index -p -t 16 split.vg -x split.vg.xg -g split.vg.gcsa -k 15
./vg map -t 16 -d split.vg -x split.vg.xg -g split.vg.gcsa -f queries -M 8 -w 512 -W 64 > oqueries.gam
./vg view -aj oqueries.gam > oqueries.json

Please find examples of records that we got:
[ecoli_json_fragments.txt](https://github.com/vgteam/vg/files/1866717/ecoli_json_fragments.txt)

**Comment by adamnovak** [comment]
Hello,

The JSON format is the `pb2json`-library JSON serialization of the Protobuf schema, defined and documented in https://github.com/vgteam/vg/blob/master/src/vg.proto. For `vg map`, it's outputting Alignment objects.

In Protobuf (at least in v3, which we use), having no value for a field is the same as having the field's default value. For for the `is_secondary` field, for example, you will only have records where it is true and records where it is missing, because false is the default for bools. Alignments with no `score` field have a score of 0, and so on.

The `secondary_score` field gets set to give the scores of the secondary alignment(s), so you have them handy when working on the primary alignment. It doesn't mean that the alignment itself is secondary; that's what the `is_secondary` field does.

An `Alignment` that has a `Path` that has `Mapping`s that have `Position`s is an alignment that actually found somewhere in the reference to put the sequence. It should have a nonzero score. It may be primary or secondary.

An `Alignment` with no `Path` at all is an unmapped read. The mapper couldn't find anywhere to put it to get a positive score.

An `Alignment` with a `Path` that has a `Mapping` with no `Position` is... weird. The ones you show appear to be describing your read as entirely softclipped, but aligned to no particular place. It might be that you only get this with longer reads, when the aligner ends up using its chunked mode. I *think* they basically mean the same thing as the alignments with no path, which is that the mapper couldn't find a good mapping.

The fragmentation I think is also maybe a result of the chunked aligner; it looks like no path simplification is being done on the output alignment after concatenating the chunks, or else we aren't converting from a representation that just jumps between mappings to one that uses mappings describing insertions or deletions. If you can read the format, I don't think you will be missing any of the aligned bases, but it will do counterintuitive things like not describe entire nodes that the aligned read just skips visiting but which occur between the nodes it does visit.

@ekg knows more about the chunked aligner than I do. Does this look like expected behavior to you? And is there a way to make the chunked aligner spit out things that look more like what the normal aligner spits out?

**Comment by ekg** [comment]
> An Alignment that has a Path that has Mappings that have Positions is an alignment that actually found somewhere in the reference to put the sequence. It should have a nonzero score. It may be primary or secondary.

@adamnovak I should mention a possible problem here. The alignment scores given in the chunked aligner are meant to approximate global alignment scores, and so can be negative or zero even if the read is aligned. (Zero is very unlikely if any alignment has been made, but in some small number of cases you will get this result.) For this reason the way to determine if a read is aligned is to check if there is a path that touches nodes.

This can be done by looking at the identity field in the GAM-JSON. If any region of the read is aligned it will have non-zero identity.

It should also be that the path is empty if the alignment doesn't traverse any bits of the graph we aligned it to. (Note that this is true if the "from_length" sum of its mappings is zero.)

> An Alignment with a Path that has a Mapping with no Position is... weird. The ones you show appear to be describing your read as entirely softclipped, but aligned to no particular place. It might be that you only get this with longer reads, when the aligner ends up using its chunked mode. I think they basically mean the same thing as the alignments with no path, which is that the mapper couldn't find a good mapping.

I will look into this. I've seen the same thing and I suspect it's just that I'm not running the alignment normalization on the output of the mapper. I hadn't yet been pushed to fix it as I only saw it last week and understood that I could use .identity to check if the read is aligned. For the time being treat these reads as unmapped in any post-processing. I should have a fix into master in the coming week.

@TanyaDvorkina  Your questions also show to me that we need some singular reference document to describe the formats and their features, some of which could be considered implicit (like this question of whether a read is aligned or not). That said I think the third case of alignment type is a bug. If you'd had documentation you could have been sure it was a problem and not a feature.
