### ISSUE TITLE
Pruning and indexing a large complex human assembly

### ISSUE THREAD

**Issue by kevyin** [vgteam/vg#1619]
Hello vgteam, @jltsiren 

I've been trying to index a human assembly GFA (from public novaseq reads with a short read assembler)

The starting graph is 
9405215 nodes, 13422247 edges

I've tried pruning and indexing but both have exceeded 2TB of RAM
Eg, digging into the code pruning find_edges_to_prune seems to be building up a lot of RAM
https://github.com/vgteam/vg/blob/07c5402539011cb07601b736fcad93c9b6be408e/src/prune.cpp#L5

Before I go deeper into the rabbit hole I was wondering if indexing something like this has been attempted or where the main bottlenecks may be? 

Would this problem (indexing from an assembly) be, say orders of magnitude more resource intensive than eg indexing from a reference?
https://github.com/vgteam/vg/wiki/working-with-a-whole-genome-variation-graph

Best,
Kevin

**Comment by jltsiren** [comment]
Do you have the entire graph in a single `.vg` file? That alone increases the memory requirements of many operations by 12x over having a separate file for each chromosome.

`vg prune` and `vg index` output some statistics with option `-p`. It may help determining where the memory usage grows too high.

**Comment by kevyin** [comment]
Thanks for the reply,

Atm it's one .vg file, likely with cycles, Ideally we can chop up the graph as theoretically it's a combination of chromosomes, though I haven't looked deeply into how feasible it is to predict where the cuts should be or how to predict them.

Thanks I've been using -p which is helping with showing where the pain points are.

**Comment by ekg** [comment]
@jltsiren it will be hard for @kevyin to break up the graph by chromosome because it's generated by a short read assembler. All repeats longer than the read length are likely collapsed.

@kevyin can you even load the entire graph into memory on your system, e.g. using `vg stats -lz graph.vg`? How long is the graph (`vg stats -l`)?

Most assemblers I've used tend to break the assembly graph apart to some extent. If this is already happening then you can use `vg explode` to break it apart into its connected components. Then do the indexing on these separately.

Before breaking the assembly apart you should also remove high-degree nodes from the graph. Unfortunately this seems to be a requirement of the current indexing and mapping model. I have been using a node degree of 8 (meaning 8 edges) as a limit, but this may be too aggressive. You can look at the node edge counts in JSON or GFA to get a sense of the distribution. Often a tiny number of nodes are connecting a large number of parts of the graph. The failure mode that results from this will be a memory exhaustion in kmer indexing or possibly even pruning, as the DFS that's run to generate the kmers/walks in these cases needs to maintain progressively larger fractions of the graph as it is more strongly connected by these high degree nodes.

To remove high degree nodes (for instance only keepingthose with 8 or fewer edges), do e.g.: `vg mod -M 8 graph.vg >graph.mod.vg`. I'd try this and then do `vg explode` to see how many components you get. You can also look at how much of the graph is removed by using `vg stats` before and after this pruning step. Provided things appear sane, you can then try to proceed into indexing.

You may be the first to work with a whole human short read assembly graph in vg. I'm hoping that we'll be able to use the existing tool chain here with small modifications. If not, we may need to start considering alternative indexing strategies, such as minimizer or another kind of kmer subsampling.

**Comment by ekg** [comment]
If the high-degree node issue isn't it, you might also consider chunking the graph and working on those chunks. The problem will be limiting the number of steps of splash to take in the chunks, as if you take more than a step or two in a very connected graph you'll get most of the whole graph back for every chunk.

**Comment by kevyin** [comment]
Hi Erik
Sorry for the late reply, the discussion around high-degree nodes led to a strange finding.
Firstly
```
$ vg stats -zlAr NA12878_refasm.vg

nodes	9405215
edges	13422247
length	2464546290
node-id-range	440:44276533
cyclic
```

I tried explode (before -M8), as sort of expected it just gave one large chunk, with many other very little chunks

I was about to continue with the suggestion for -M8 and then explode, but then encountered ....

Regarding the strange finding
There's one node with sequence 'T' with 4701191 edges

Here are the top 10 node ids, "to" and "from",
The rest of the top are also single base pair sequences (G,C,T, or As)

Number of edges going to node
34873872    2326724
35197640        908
34889883        623
34878303        604
35197639        592

Number of edges going from node
34873872    2374467
35197640        890
35197639        731
34889883        621
34878303        614

I double checked the original GFA and this/these where generated during the conversion from GFA to VG

Here is a Jupyter notebook, which shows distributions of neighbors of this 'T'
https://colab.research.google.com/drive/17eLeBGI_aQ3aCpuIrw45f8LvTDHpQ9F3

Original GFA
https://drive.google.com/open?id=1T88qYFboENkgX-biUYvQqwx4Th4g6jSl

Original GFA -> VG
``vg view -F NA12878_refasm.gfa -v > NA12878_refasm.vg``
https://s3-ap-southeast-2.amazonaws.com/uts-public-share/NA12878_refasm.vg

Original GFA -> VG -> VG.GFA
``vg view NA12878_refasm.vg -g > NA12878_refasm.vg.gfa``
https://s3-ap-southeast-2.amazonaws.com/uts-public-share/NA12878_refasm.vg.gfa.gz


What do you guys think?

**Comment by kevyin** [comment]
I've tested with smaller ecoli assemblies gfa -> vg, it didn't have a disproportionate node like this

**Comment by kevyin** [comment]
Using a different assembler produced something that got vg over the line.

**Comment by ekg** [comment]
Out of curiosity, which assembler did you use?

**Comment by kevyin** [comment]
megahit, we think it's their bubble popping which may have helped? still required a lot of RAM though
