### ISSUE TITLE
vg installation error with Ubuntu

### ISSUE THREAD

**Issue by evanbiederstedt** [vgteam/vg#1646]
I'm trying to install vg, and I'm running into issues. I've attached a *txt with errors. As you can see, it's  not finding any of the library files it needs despite them being present.

It looks like it's mainly any google-based tools that tie into VG that seem to be running into library issues since they’re all built on Ubuntu (c’mon google, where’s the love for other distros...).

I didn’t even realize it was struggling this bad until running strace over it. I recommend using VIM to open it up since the syntax-highlighting makes the doc way easier to read.
 
I’m going to work through this strace and find a way to link all the missing items together for now but we can also send that to devs if it will help get some feedback on installing this to centos.
The instructions someone has on https://github.com/vgteam/vg/wiki/Building-VG-on-Cent-OS-6.6-or-7--and-using-it is so diluted there’s no way it’d work just following those steps.....

[VG-1.7.0-Debug.txt](https://github.com/vgteam/vg/files/1943982/VG-1.7.0-Debug.txt)

**Comment by evanbiederstedt** [comment]
Here's a second try:

The compiler flag, “-msse4.1”, was added to fix this error, “# error "SSE4.1 instruction set not enabled"

There are several things that were fixed after using the recursively pulled module. Attached are the latest errors.

Currently errors spawn from this file:

```
. ./source_me.sh && /bin/g++ -O3 -fopenmp -std=c++11 -ggdb -g -MMD -MP -msse4.1  -c -o obj/cached_position.o src/cached_position.cpp -I/nfs/sw/src/vg-1.7.0/vg/include -I. -I/nfs/sw/src/vg-1.7.0/vg/src -I/nfs/sw/src/vg-1.7.0/vg/src/unittest -I/nfs/sw/src/vg-1.7.0/vg/src/subcommand -I/nfs/sw/src/vg-1.7.0/vg/cpp -I/nfs/sw/src/vg-1.7.0/vg/include/dynamic -I/nfs/sw/src/vg-1.7.0/vg/include/sonLib
In file included from src/cached_position.hpp:7:0,
                 from src/cached_position.cpp:1:
```

**Comment by adamnovak** [comment]
Hello,

Yes, you do indeed need to recursively clone vg, since a lot of the dependencies it has are delivered as submodules, and a lot of those submodules have their own submodules. Currently, building with system-installed versions of the dependencies we ship as submodules (i.e. linking against the system's own Protobuf, for example) is not supported.

The linked wiki instructions don't appear to be missing much at first glance. They skip a bunch of dependencies (like Protobuf) because those dependencies are submodules.

I'm not sure why you're including the systrace info; I can't see anything interesting in that. But I think your underlying problem for this most recent failed build is using a too-old C++ STL. Note that a bunch of the errors involve files in `/usr/include/c++/4.8.2/`. I think that's the STL for GCC 4.8, and the minimum GCC (and STL) required to build vg is GCC 4.9. If you use 4.8, it mostly almost builds, but there are some pieces of C++11's STL that 4.8 doesn't actually provide.

Try again with a newer GCC.

**Comment by adamnovak** [comment]
I'm going to close this; I think you eventually managed to get this to build?

**Comment by evanbiederstedt** [comment]
Hi @adamnovak 

No, I never got this working for 1.7. I'm trying to get the docker images from quay, but the sys admins on my end have issues with using docker, and we cannot install rkt  for CentOS, so....

We'll try to figure it out someday

If I ever get it solved, I'll reopen

**Comment by adamnovak** [comment]
As for the build, did you manage to excise the outdated compiler from the build process? I think the right way to do that is first to make sure that `g++ --version` reports the right version, and then to pick through your environment variables looking for out of date include paths.

If you can't get the Docker or the build to work, you can always try using the latest binary from the releases page, which is currently https://github.com/vgteam/vg/releases/download/v1.7.0/vg-v1.7.0

You should be able to run that static binary on any Linux.
