### ISSUE TITLE
get uniquely mapped reads out of the json format

### ISSUE THREAD

**Issue by malvarez94** [vgteam/vg#165]
Hi,
1) Is there a way I could get the reads that map uniquely (based on the alignment score or...?) from the alignment in json format? 2) Also, if in the json format a read doesn't have the label score I assume that the read didn't map at all, right? 3)Have you stablished a threshold for an acceptable alignment score?

**Comment by adamnovak** [comment]
Reads are unmapped if their `path` field isn't set. The `score` shouldn't be set if a read is unmapped, but it will also be set if it is somehow mapped with a score of `0` (which oughtn't happen, but isn't really prohibited). Currently there's no threshold for a minimum acceptable score, I don't think.

Uniquely-mapped reads are now harder, since we're doing paired end alignment reporting as consistent pairs. There might only be one mapping for a read, but it will be reported twice (the second time marked with `is_secondary: true`) if the read at the other side of the pair has two different mappings that are within the paired-end range.

To get all the reads that map uniquely, find all the reads for which there is a single unique non-empty `path` in `Alignment`s carrying the read's `name`.
