### ISSUE TITLE
vg augment question for whole-genome variant calling (where do I get wg graph.vg file?)

### ISSUE THREAD

**Issue by srmcgee** [vgteam/vg#1655]
Hope this is a quick question.

I seem to be missing something in the path to getting variants called in the whole genome case. I have constructed the individual chromosome graphs ($chr.vg) with "vg construct...", coordinated the node IDs with "vg ids...", indexed the individual chromosome graphs ($chr.vg) with "vg index....", pruned and smoothed all the $chr.vg files, and then indexed and created the $chr.gcsa files from the $chr.pruned.vg files. And then I'm able to successfully map to all those resulting wg.xg and wg.gcsa with "vg map..."   All that worked great (Thank you for the excellent documentation for that!) 

My problem arises when I try to use "vg augment..."  According to the small-graph documentation, It require a graph.vg file which I do not seem to have created in the whole-genome process I described above.  (I'm assuming graph.vg in this case would be a whole-genome vg file, a la wg. vg?)

Any help would be greatly appreciated to point out what am I missing. Is there a way to create this whole-genome vg file, or do I need to instead just use the individual $chr.vg files for the vg augment step? And then just ultimately combine all the resulting VCFs?

Thank you very much for your assistance,
Sean

**Comment by ekg** [comment]
You can generate the wg.vg file using `cat`:

```
cat chr1.vg chr2.vg chr3.vg >wg.vg
```

However, you should be careful when augmenting this file because you may run out of memory. It could take several hundred GB of RAM to load wg.vg and modify it using `vg augment` or `vg mod -i`. If you do run out of memory you will need to do a different technique, which I guess is based on `vg chunk` and breaking up the alignment or variant set by chromosome. This is unexplored for whole genomes, so I can't give you a precise recipe. Does this idea make sense? Let me know if you have any questions or where you get to when trying this.
