### ISSUE TITLE
Use system proviced raptor instead of one in deps

### ISSUE THREAD

**Issue by JervenBolleman** [vgteam/vg#1664]
I accidentally pushed a branch sysrap which has this and it seems to work on the right ubuntu's and mac os x. @ekg could you test and merge it if it is ok. I will be away for two weeks with very limited internet.

**Comment by adamnovak** [comment]
You mean https://github.com/vgteam/vg/tree/sysrap right?

I just dug into this a bit, with Glenn's version of the same thing: https://github.com/vgteam/vg/pull/1684

My conclusion there, and it applies here as well, is that we can't do this because it would break our ability to produce a fully static vg binary. The static Raptor that Ubuntu ships needs to link against Curl, and the static Curl that Ubuntu ships needs to link against Kerberos, and Ubuntu doesn't ship a static Kerberos (libkrb5). So if we used Ubuntu's static Raptor, we would need to dynamically link against Kerberos at runtime, and we wouldn't be able to make a fully static vg.

I'm going to close this, because I think we want to do it. If Ubuntu ever ships a static libraptor that doesn't have dynamic dependencies, we can try again.
