### ISSUE TITLE
RAM requirements.

### ISSUE THREAD

**Issue by saiz06** [vgteam/vg#1672]
Currently the system I am using has 130G memory. On the wiki page it is mentioned that for the xg and GCSA2 based index, 256G of RAM will be used. Is 256G required or a recommended? I am about to put up a request order for purchasing more RAM and I thought I'd ask first before I ordered more.

**Comment by jltsiren** [comment]
A lot of VG development is done on systems with 244-256 GB memory, so that has become an unofficial design target. You can build a GCSA2 index for a whole-genome human graph in 128 GB, but I'm not sure how much memory XG construction uses these days. The final indexes are ~30 GB each, so 128 GB should be enough for using them.

**Comment by glennhickey** [comment]
The xg indexing will need closer to 200G for the full 1000 Genomes VCF.  I
don't think you can work with this such a graph with much under 256G RAM.
If you filter out rare variants from your vcf first (ex bcftools view
--min-af 0.01), you might get a graph that you can work with in 130G.  How
filtering rare variants affects different use cases is something we're
currently exploring.
