### ISSUE TITLE
Can vg be used with protein sequences?

### ISSUE THREAD

**Issue by ivargr** [vgteam/vg#1677]
It seems to work well to do `vg construct` with e.g. a fasta file containing protein sequences. However, if I do `vg construct -M protein_msa.fasta` using the output from a multiple sequence alignment as input to vg construct, vg complains: _error:[MSAConverter] MSA contains non-nucleotide characters_

It seems like there is a constraint in the msa-converter (https://github.com/vgteam/vg/blob/9f8bb03a51b1adfd30aca73f05aa461e38ef76ef/src/msa_converter.cpp#L272) that limits it to only allow A,C,T,G and N. Is this just an old check that should have been removed?

**Comment by adamnovak** [comment]
We do not support operating on protein sequences currently. Because of the bidirected graph model we use, we will sometimes try to reverse-complement sequences. Also, some of our indexing code restricts us to a DNA alphabet.

**Comment by jeizenga** [comment]
Agreed. As written, many parts of the VG suite are heavily invested in DNA sequences. It would be relatively simple for me to remove this constraint, but you would almost certainly run into problems on the next task. I think it's more humane to have the pipeline crash early rather than let users spend time on something they won't be able to finish.

**Comment by ivargr** [comment]
Okay, I understand, thanks for letting me know!
