### ISSUE TITLE
vg map reverse strand preference - clarification request

### ISSUE THREAD

**Issue by ChriKub** [vgteam/vg#1725]
1. What you were trying to do

I am simulating error free reads using vg sim from forward and reverse strand (without the -f option), converting them into a fastq file and mapping them back to the same reference using vg and bwa. Afterwards I compare the mapping positions to the positions the reads where simulated from.

2. What you wanted to happen

I want to have mostly similar mapping positions for bwa and vg map

3. What actually happened

The reads mapped using vg map almost always map the rerverse strand if there is a reverse strand representation. Which in most cases is the position the read was simulated from. bwa mem reports a equally good forward strand position for those reads, which don't overlap with the positions they where simulated from. 

vg seems to prefer revese strand records whereas bwa reports the forward strand. Is this a wanted behavior? It can't be the solution to simulate reads from the forward strand only to obtain comparable results for bwa and vg on the same variant free reference sequence.

**Comment by adamnovak** [comment]
Are you reporting secondary mappings (with something like `-M 2` to `vg map`)? That should let you have access to both of the mappings, if you want them. And are these reverse strand mappings with equally good forward strand mappings produced with nozero mapping quality?

It's possible that we are arbitrarily and nonrandomly picking the reverse strand mapping out of two equivalent mappings, just because it happens to end up at the top of the list when we construct it and we don't have a reason to demote it.

I'm not sure that the "correct" behavior here is to just arbitrarily and nonrandomly report the forward strand mapping instead, for the sake of matching what BWA does. That's still biased toward one strand over the other for no biological reason.

Maybe we should be deterministically but randomly breaking the tie, so that 50% of the time we report the forward strand mapping and 50% of the time we report the equally good reverse strand mapping, so that we don't have a bias to one strand or the other.

**Comment by ChriKub** [comment]
@adamnovak I'm not reporting secondary mappings. I started out using toil-vg mapeval and observed this problem there the first time. Especially for se reads. The reverse strand mappings are equally good and produce nozero mapping qualities. What especially bothers me is that vg always matches the position I simulated the reads from although their are equally good mapping positions elsewhere.

I agree that it makes no sense to arbitrarily and nonrandomly report the forward strand to match bwa. I would prefer a random distribution between the possible positions.
