### ISSUE TITLE
Problem building the index - [xg] error: path JX512452.1 contains duplicate node ranks

### ISSUE THREAD

**Issue by manuelsmendoza** [vgteam/vg#1740]
Hi!

I'm trying to make the variant calling using vg but I am not able to index the graph... I have built the graph using a reference (FASTA) and multiple (a total of 10) variant files (VCF). My FASTA file is the sequence of only one gene.

When I try to build the index, vg throws the following error: `[xg] error: path JX512452.1 contains duplicate node ranks`... 

Does anyone know how to solve this problem?

**Comment by adamnovak** [comment]
What command line did you use for `vg construct`?

Did you use multiple VCFs covering the same contig, without merging them together yourself? It's possible you built the same graph multiple times, once per VCF, and dumped them into one file.

We wrote the support for multiple VCF files in order to support one-VCF-per-chromosome setups like 1000 Genomes does; I don't think we anticipated that someone would try to use multiple overlapping VCFs, and we don't have any code to check for that and handle it correctly, or even to throw an error.

The workaround is to merge all your VCFs together and re-sort them, with something like `vcftools`. The real solution is for us to add code to detect multiple overlapping VCFs and abort with an error, or for vg to do the merging itself somehow.

**Comment by manuelsmendoza** [comment]
It was I did... I am simulating multiple samples of the same sequence under different evolutive scenarios... I will try to merge all my vcf in one... Is possible to solve this problem in future versions?

**Comment by adamnovak** [comment]
I've merged in a fix to VG that will catch duplicate contigs in VCFs and prevent graphs from being built like this in the future.

**Comment by manuelsmendoza** [comment]
It's the best choice by now... I have merged all the vcf in a single one and them, reconstruct the graph with this "unified" vcf
