### ISSUE TITLE
Problem using vg index

### ISSUE THREAD

**Issue by manuelsmendoza** [vgteam/vg#1748]
Hi!

I have built the graph following the guide of this repo (`vg construct -r x.fasta -v x.vcf > x.vg`) it has run ok but, now I am trying to build the index because I want to map read to the graph. I'm trying to build the graph by `vg index -x x.xg -g x.gcsa -k 16 x.vg` but the output is: DiskIO::write(): Write failed

```
This is the progress:
Built base XG index
Saving XG index to disk...
Generating kmer files...
 loading graph                  [===================================]100.0%
DiskIO::write(): Write failed
```
Does anyone know what is happening? 

NOTE: 
My data are simulated scenarios with different mutations rates, this error started to happen with medium-high mutation rates.

**Comment by jltsiren** [comment]
`DiskIO::write(): Write failed` most likely means that you ran out of disk space in `$TMPDIR`. Typical space usage is a few hundred bytes/bp.

However, because you are working with simulated data, the real issue is probably the mutation rate. Under some reasonable assumptions, the size of the temporary files scales with *n(1+p)^O(log n)* for a genome of length *n* and mutation rate *p*. Once the mutation rate reaches *Θ(1/log n)*, things start getting ugly. At that point, you need to simplify the graph with `vg prune` (see [the wiki](https://github.com/vgteam/vg/wiki/Index-Construction)) before indexing it.

By default, `vg index -g` builds a 256-mer index. You can build a (A*2^B)-mer index with options `-k A -X B`. If you build a k-mer index, *O(n(1+p)^k)* is an expected case upper bound for the size of the temporary files.

**Comment by manuelsmendoza** [comment]
you are right, the problem was the quata in the `$TMPDIR`, I have changed this dump directory using `-b` flag and it ran 

Thanks!!
