### ISSUE TITLE
vg mod doesn't scale to large pangenomes with a number of paths

### ISSUE THREAD

**Issue by JervenBolleman** [vgteam/vg#1872]
This is just too raise the request that I would like a faster vg mod, pretty please!

17 days of compute to do my 

vg mod -i ecoli-all.gam ecoli.vg > ecoli-all.vg

and no end in sight.

It's running right now so if there is some way to generate actionable insight please let me know.

**Comment by JervenBolleman** [comment]
Thing is this vg mod application is just inserting nodes using GAM. This should be able to be done linearly, we should discuss this next time we meet. Just want to have an issue as I think it would be a nice intro into some performance orientated code for CS student.

**Comment by ekg** [comment]
I now have a partial solution for this. Use [seqwish](https://github.com/ekg/seqwish#seqwish) to induce the graph in one step. This isn't done, but it is certainly going to be more scalable than the serial vg msga and vg mod solutions. We'll need a script that can convert a BED file into PAF (which is seqwish's input), and also may need to hack some way to make annotations appear as sequences in a FASTA file (or hack seqwish to understand that these sequences are special, which I'd prefer not to do).

**Comment by glennhickey** [comment]
@JervenBolleman You can try

`vg augment ecoli.vg  ecoli-all.gam -A aug-reads.gam > aug-graph.vg`

It scales much better than `vg mod -i` because it doesn't create a Path for each read in the graph.  You still get the nodes and edges implied by each mapping, though.  Path information can be inferred if needed from aug-reads.gam which stores all the mappings in terms of aug-graph.vg.

**Comment by JervenBolleman** [comment]
This is no longer an issue since the pull request #1941 was merged. vg mod now builds 140+ ensembl genomes with it's genes as paths. Overnight or faster.
