### ISSUE TITLE
vg snarls crashing on single nodes

### ISSUE THREAD

**Issue by ekimb** [vgteam/vg#1874]
Running vg snarls on a large graph, I encounter this error:

> what():  Cactus does not currently support finding snarls in a single-node connected component

Is there a way to skip single nodes when running vg snarls?

Thanks!

**Comment by adamnovak** [comment]
Unfortunately we don't have a way to skip them at the moment. We probably could add it, but at the cost of breaking the idea that the snarls are actually a decomposition of the graph, and I'm not sure the genotyping code would be happy to encounter nodes that don't participate in any snarl.

You could try using `vg mod -X SOME_SMALL_NUMBER` to chop up your graph nodes to a certain maximum node size, so that the single-node components become multiple nodes. The `vg prune` command also has a `--subgraph-min` option where you can discard disconnected subgraphs under a certain size in bases.

We're working on changing around the way snarls are found a bit; we might be able to handle single nodes with the changes @benedictpaten is going to make where we won't have to always provide telomeres to root the decomposition.
