### ISSUE TITLE
How to output a gapped alignment, not softclipped

### ISSUE THREAD

**Issue by 13am** [vgteam/vg#1877]
**1. What you were trying to do**

I had aligned reads to a graph generated from a reference FASTA and VCF file. Visualizing the alignments I could see that some reads were aligned to the graph with no mismatches and going through a path that contained a deletion (from the VCF relative to the reference FASTA).

`vg view -d x.vg -A x.gam | dot -x -Tsvg -o x.gam.svg`

 I outputted the alignments using surject:

`vg surject -x $xg_path -b $gam_path`

**2. What you wanted to happen**

I wanted to see the reads containing the deletion outputted with a gap. 

**3. What actually happened**

The reads were outputted with no gap but instead containing softclipped bases.

So this is what I got in the SAM:

`A00282:126:H7FL2DSXX:1:1476:25418:1266	0	22	38119846	60	12S95M	*	0	0	AACGAGAGAATTCCAGAACATCCTGCGCCCAGCGGGACAATCCCAGAGCCTCCTCTCCCAGTAGAGCTACACGAGACAACCCCACAACATCCTGTGCCCAGCGGGAC	FCCHGHGHFEEEEHGHFCIEEEIEHCHEEIGHC::HCIFEEEEIGHGHEIEEIEIECEIGGDGHGFHBCICCHGHCIFCEDEI=I?>IEEDHDGDGDDHFGAA>A<?`

But I wanted to get the alignment I saw when visualising the alignment. This alignment can be had e.g. blatting the above read:

```
Side by Side Alignment:

00000001 aacgagagaattccagaac 00000019
>>>>>>>> ||||||||||||||||||| >>>>>>>>
38119756 aacgagagaattccagaac 38119774

---

00000020 atcctgcgcccagcgggacaatcccagagcctcctctcccagtagagcta 00000069
>>>>>>>> |||||||||||||||||||||||||||||||||||||||||||||||||| >>>>>>>>
38119853 atcctgcgcccagcgggacaatcccagagcctcctctcccagtagagcta 38119902

00000070 cacgagacaaccccacaacatcctgtgcccagcgggac 00000107
>>>>>>>> |||||||||||||||||||||||||||||||||||||| >>>>>>>>
38119903 cacgagacaaccccacaacatcctgtgcccagcgggac 38119940
```

**Comment by adamnovak** [comment]
It looks like in this case, the surjected alignment you want to get has a very large deletion (79 bp) and a lower score, using ordinary linear reference scoring rules) than the softclipped alignment that you actually got, right?

**Comment by 13am** [comment]
Yes, exactly. So I’d expect the surjection to reproduce the best alignment against the graph. In this case I would have expected it to be trivial, as the best alignment would be easy to describe against a linear reference.

**Comment by jeizenga** [comment]
The process of surjecting the alignments isn't really mathematically well-defined, so we've had to make some algorithmic choices in the implementation. One of these is whether to produce soft-clipped alignments when the surjected alignment takes edits (with respect to the reference path) that would cause it to have negative score, or whether to force the full length alignment and just permit the negative score. 

Right now, it's implemented to do make soft-clips, and that's intentional. However, I've been meaning to implement the other alternative as an option for a while now. I figured there would be applications like yours where it makes more sense. I can go ahead and do that for you.

**Comment by 13am** [comment]
Great, sounds good! And just to stress this point once more, in this case the 79bp deletion was

- in the input VCF used to build the graph
- correctly added to the graph
- in the path used by the aligner to align the read

Furthermore, there were no mismatches in the path of the alignment. So my interpretation of the alignment was "a perfect match to the graph, edit distance zero". Thus, I intuitively expected the surjection to just reproduce this alignment. I also believe this is what most other users would expect as the default behavior.

**Comment by adamnovak** [comment]
I'm a bit worried about changing the default behavior, because I don't
know if anyone has tested that sort of negative-score alignment with
genotyping tools that are likely to consume the downstream BAM. We
ought to see how e.g. GATK or Freebayes handles these alignments
first, I think. It's OK to surprise the users who look at the BAM file
if we need to do it to avoid surprising the ones who run genotyping
workflows.

On the other hand, maybe allowing these long indels in reads will
convince those tools to call larger variants that are in the graph.

**Comment by 13am** [comment]
I agree - changing the default behavior (of anything) should be done only after some consideration.

**Comment by jeizenga** [comment]
The PR is merged, you should be able to get behavior like you were expecting using the `-f` flag. Hope it works well for you, and let me know if you have any other issues with it.

**Comment by 13am** [comment]
I'm having hard time compiling vg now, commit 9b812d569e16ef845863a7f2fdd205901f72a59d

```
./source_me.sh && make
...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bin/vg] Error 1
```

I'm on macOS 10.13.6, installed the dependencies using homebrew. Compiling commit fc5db8e2612e091e2d4304b4b1d4f16661e3d737 worked the last time I tried. Tried building from that commit to see if I can still do it but nope, now it failed with 

```
clang: error: unsupported option '-fopenmp'
make: *** [obj/main.o] Error 1
```

Maybe something Mac-related? Either some updates in my computer in the meantime have broken something or I compiled vg differently and can't remember how. Any ideas?

**Comment by adamnovak** [comment]
I bet it's our new Clang support. fc5db8e should never have built with Clang, but now master is able to be built with Clang. If you followed the new instructions in the README and didn't do the optional step to `brew install gcc6` and link it as your `g++`, then you would be able to build the new version, but you wouldn't be able to go back and build the old version. That step didn't used to be optional.

It's also possible you had Homebrew GCC 6 set as your `g++`, but a MacOS update reset things. You should be able to check what your `g++` is currently with `which g++` and `g++ --version`.

You can get that `symbol(s) not found for architecture` error on the new version when you previously built with one compiler and are now building with another compiler. I'd say that `make clean` would fix it, but I just made some revisions to `make clean` because it didn't always completely work. So on 9b812d5 you can clear things out and rebuild with:

```
make clean-vg
rm -Rf deps
git submodule update --init --recursive
make -j4
```

**Comment by 13am** [comment]
I'll try this as soon as I get the chance!
