### ISSUE TITLE
vg construct leaves SV insertion nodes unconnected

### ISSUE THREAD

**Issue by eldariont** [vgteam/vg#1922]
Hi,

**1. What you were trying to do**
I observed strange results when using `vg construct` to create a graph from a reference fasta and a vcf file. Here is a small test dataset from one of the unittests:

ref.fa
```
>x
CAAATAAGGCTTGGAAATTTTCTGGAGTTCTATTATATTCCAACTCTCTG
```

var.vcf
```
##fileformat=VCFv4.2
##fileDate=20090805
##source=myImputationProgramV3.1
##reference=1000GenomesPilot-NCBI36
##phasing=partial
##FILTER=<ID=q10,Description="Quality below 10">
##FILTER=<ID=s50,Description="Less than 50% of samples have data">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT
x	9	sv1	N	<INS>	99	PASS	AC=1;NA=1;NS=1;SVTYPE=INS;SEQ=ACTG;SVLEN=4;END=13;CIPOS=0,3;CIEND=-3,0	GT)";
```

**2. What you wanted to happen**
I would expect a separate node "ACTG" connected to the surrounding nodes of the reference.

**3. What actually happened**
`vg construct -r ref.fa -v var.vcf -S -p -m 10 | vg view -d - | dot -Tsvg -o graph.svg`

![graph](https://user-images.githubusercontent.com/6477692/46690889-5b3dd500-cbb8-11e8-8a09-0d8c6e8fe510.png)

It seems like the test cases for SV construction (https://github.com/vgteam/vg/blob/master/src/unittest/constructor.cpp#L1438) only check the sequences of the nodes but not their connecting edges.

I don't know enough about the constructor yet to know what goes wrong but maybe @edawson can help?

Cheers
David
vg commit aa394a8477eb3f27ccfe421457e2e013e7907493

**Comment by adamnovak** [comment]
The underlying problem here is that we're putting the wrong node starts and ends in for the inserted nodes. We have the inserted node starting at (0-based) reference position 8 (i.e. instead of going to reference position 8 you can go to the insert), but the reference node that should be an alternative starts at reference position 9, with position 8 included in hat leftmost reverence node 1. I suspect this has something to do with the fake N reference sequence. It's not clear to me whether we're talking about inserting before or after the G that occurs at 1-based position 9 (the last base of node 1 in your image), and the code doesn't really know either, and that's why it doesn't work on the left end.

On the right end, we're incorrectly using SVLEN to find the end of the insertion, when in reality SVLEN is going to hold the number of inserted bases and the end should be right next to the start for a pure insertion. Also, it looks like the input is wrong; an `INS` really shouldn't start at 9 and `END` at 13. I think the `END` is supposed to be in reference coordinates.

**Comment by adamnovak** [comment]
We have fixed this issue by revising how vg and vcflib handle symbolic SVs.
