### ISSUE TITLE
Invalid thread when extracting threads as path from VCF with inconsistent insertions

### ISSUE THREAD

**Issue by jmonlong** [vgteam/vg#1932]
I was creating a graph with insertions and deletions and when extracting the threads as path I noticed a few warnings in the form of "*edge does not exist*" and "*[vg view] warning: graph is invalid!*".

It seems to be happening in regions where the input VCF is inconsistent (e.g. two different insertions in the same location and the same haplotype). I recreated this in the tiny graph:

*tiny.fa*

```
>x
CAAATAAGGCTTGGAAATTTTCTGGAGTTCTATTATATTCCAACTCTATG
```

*tiny.vcf*
```
##fileformat=VCFv4.1
##fileDate=20141110
##source=mutatrix population genome simulator
##seed=1415643582
##reference=x.fa
##phasing=true
##commandline=mutatrix --dry-run -s 0.05 -i 0.01 -p 2 x.fa
##INFO=<ID=AC,Number=A,Type=Integer,Description="Alternate allele count">
##INFO=<ID=TYPE,Number=A,Type=String,Description="Type of each allele (snp, ins, del, mnp, complex)">
##INFO=<ID=NS,Number=1,Type=Integer,Description="Number of samples at the site">
##INFO=<ID=NA,Number=1,Type=Integer,Description="Number of alternate alleles">
##INFO=<ID=LEN,Number=A,Type=Integer,Description="Length of each alternate allele">
##INFO=<ID=MICROSAT,Number=0,Type=Flag,Description="Generated at a sequence repeat loci">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	1
x	9	.	G	A	99	.	AC=1;LEN=1;NA=1;NS=1;TYPE=snp	GT	1|0
x	10	.	C	T	99	.	AC=2;LEN=1;NA=1;NS=1;TYPE=snp	GT	1|1
x	14	.	G	A	99	.	AC=1;LEN=1;NA=1;NS=1;TYPE=snp	GT	1|0
x	22	.	C	CATATATA	99	.	AC=2;LEN=1;NA=1;NS=1;TYPE=snp	GT	1|0
x	22	.	C	CATATAAGTTA	99	.	AC=2;LEN=1;NA=1;NS=1;TYPE=snp	GT	1|0
x	25	.	GAGTTCTA	G	99	.	AC=2;LEN=1;NA=1;NS=1;TYPE=snp	GT	1|0
x	39	.	T	A	99	.	AC=1;LEN=1;NA=1;NS=1;TYPE=snp	GT	1|0
```

Two different insertions in position 22 and in the same haplotypes.

The commands to get the warning:

```sh
bgzip tiny.vcf
tabix tiny.vcf.gz
vg construct -r tiny.fa -v tiny.vcf.gz -a > x.vg
vg index -x x.xg -G x.gbwt -v tiny.vcf.gz x.vg
vg mod -r x x.vg > x.threads.vg
vg paths -x x.xg -g x.gbwt -T -V >> x.threads.vg
vg view x.threads.vg
```

It seems to be happening only for insertions. I tried inconsistent SNVs and deletions but didn't get the warning.

**Comment by jltsiren** [comment]
We don't check for the existence of edges when generating the threads in `vg index -G`, because that would be too slow with large datasets. Instead, we use a heuristic that detects overlapping alternate alleles by reference coordinates and tries to resolve them by removing redundant reference nodes from the thread. When we can't resolve the overlap, we either start a new thread (default) or skip the second alternate allele (option `-o`).

Here, because both variants are insertions, there is no overlap, and hence thread generation does not see the issue. In your example, the reference jumps from node 9 to node 12:

![example](https://user-images.githubusercontent.com/11444026/46896940-69545580-ce45-11e8-8ff9-8dff864614da.png)

For both variants, the path corresponding to the reference allele starts and ends after node 9. After we have appended the first alternate allele to the thread, the reference position is still at the end of node 9, so thread generation thinks it can safely append the second alternate allele as well.

The root issue is that we have three different interpretations of the same variants:

1. According to the VCF, the first variant replaces the C at reference position 22 with CATATATA, while the second variant replaces it with CATATAAGTTA. By this interpretation, the insertions should be mutually exclusive.
2. `vg construct` builds a graph, where the variants insert ATATATA and ATATAAGTTA **after** reference position 22. According to the graph, the insertions are mutually exclusive.
3. `vg index` sees only the variant paths generated by `vg construct`. As both insertions replace an empty subpath with non-empty paths, they are not mutually exclusive.

Which should be the correct interpretation when we see a haplotype with both insertions?

**Comment by jmonlong** [comment]
Thanks for the explanation, indeed in this situation it's not clear how the variants should be interpreted. In my mind it was a problem in the input VCF and I meant to report that vg was not catching it like for SNV/deletions. 

I guess here we would like a similar behavior, starting a new thread or skipping one allele. But how to catch this configuration if the overlap doesn't work?
