### ISSUE TITLE
Problem in vg annotate -p for reads that align to the reverse strand 

### ISSUE THREAD

**Issue by jonassibbesen** [vgteam/vg#1989]
Hi,

I am trying to use `vg annotate -p` to annotate alignments with their positions on the embedded paths in the graph. However I am having trouble with the reads that align to the reverse strand. The annotation works well for the forward alignments, however for the reverse it seems to consistently be giving lower positions. I am not completely sure what the issue is, but by looking through the code and comparing the output to known correct alignments it seems that the function returns the minimum first position of the nodes in the alignment. This number would always be lower than the first position of the alignment. 

I do not feel qualified fixing the issue myself, since the function calculating the position is also used in the mapper class for which I have no experience.

Cheers,

Jonas

**Comment by adamnovak** [comment]
I think the underlying problem is more or less here:

https://github.com/vgteam/vg/blob/1c59f2e8a8253c1a8121d9d2e98a7da61b0a3b22/src/xg.cpp#L3705-L3706

The XG doesn't seem to nderstand that `pos_t`s count offset like `Position`s do: from the last base of the node when you're on the reverse strand. That offset computation has to depend on the node's length when the `pos_t` we're working with is on the reverse strand.

Hopefully I can fix this tomorrow.
