### ISSUE TITLE
com.google.protobuf.InvalidProtocolBufferException$InvalidWireTypeException: Protocol message tag had invalid wire type.

### ISSUE THREAD

**Issue by sammyjava** [vgteam/vg#1997]
Please describe:

1. What you were trying to do
Read a `vg msga` .vg file generated from a multi-FASTA into a `Vg.Graph` object. (I've also tried with a straight-up `vg construct`, same result.)
2. What you wanted to happen
I wanted a Vg.Graph to be populated with the graph in the .vg file.
3. What actually happened
A `com.google.protobuf.InvalidProtocolBufferException$InvalidWireTypeException` was thrown.
4. What data and command line to use to make the problem recur, if applicable
I've attached my .vg file and the originating multi-FASTA. The Java package `vg` I'm using was generated with `libprotoc 3.6.1` against `vg/src/vg.proto` in the current `origin/master`. It compiles fine and the package looks fine. Here's the full stacktrace:
```
Exception in thread "main" com.google.protobuf.InvalidProtocolBufferException$InvalidWireTypeException: Protocol message tag had invalid wire type.
        at com.google.protobuf.InvalidProtocolBufferException.invalidWireType(InvalidProtocolBufferException.java:115)
        at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:551)
        at com.google.protobuf.GeneratedMessageV3.parseUnknownFieldProto3(GeneratedMessageV3.java:305)
        at vg.Vg$Graph.<init>(Vg.java:342)
        at vg.Vg$Graph.<init>(Vg.java:275)
        at vg.Vg$Graph$1.parsePartialFrom(Vg.java:1976)
        at vg.Vg$Graph$1.parsePartialFrom(Vg.java:1970)
        at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:221)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:239)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:244)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
        at com.google.protobuf.GeneratedMessageV3.parseWithIOException(GeneratedMessageV3.java:311)
        at vg.Vg$Graph.parseFrom(Vg.java:676)
        at VgGraphLoader.main(VgGraphLoader.java:47)
```
and here's the code that generates it:
```
 vgGraph = Vg.Graph.parseFrom(new FileInputStream(vgFile));
```

[ecoli.pan3.fa.gz](https://github.com/vgteam/vg/files/2602381/ecoli.pan3.fa.gz)
[ecoli.pan3.msga.vg.gz](https://github.com/vgteam/vg/files/2602382/ecoli.pan3.msga.vg.gz)

**Comment by sammyjava** [comment]
@alancleary

**Comment by adamnovak** [comment]
It looks like you're trying to read straight from the file, in Java?

You probably will have to have a look at (and reimplement) some of [stream.hpp](https://github.com/vgteam/vg/blob/master/src/stream.hpp).

Basically, your problem is that a .vg file is more than just a single serialized Protobuf message. It contains multiple serialized `Graph` messages, each containing a manageably-sized chunk of the graph (to support streaming graph processing). Each message is prefixed with its varint-encoded length, and then messages are grouped together into a "group" which is prefixed with the number of messages in the group. The file is then a stream of groups, which is (optionally, but always in practice) gzip-compressed.

So to read a VG file, you need to un-gzip the stream, read the length of each group, read the length of each message in the group, and *then* deserialize each Protobuf message in turn. (The gzip compression is actually BGZF, like for a BAM file, but it's a subset of normal gzip and can be read in with the Protobuf library's gzip input stream).

Once you write that code, you can use it on `.vg` files holding graphs and also `.gam` files holding `Alignment` messages.

You probably want to look specifically at `for_each_with_group_length`, which does the real deserialization work, with code here:

https://github.com/vgteam/vg/blob/master/src/stream.hpp#L257-L366

**Comment by sammyjava** [comment]
Is there any chance that you'd provide a Java implementation of these routines? Just something to read a .vg file into a Java class would get me going. I really feel like I've been the victim of a bait-and-switch, since the vg docs clearly imply that one can consume a .vg file using the Google Protocol Buffer specified in `vg/src/vg.proto`. Clearly one cannot.

I don't understand why the Google Protocol Buffer is even mentioned in the docs if it can't be used to consume a .vg file using `vg/src/vg.proto`.

If I cannot use the Java package that protoc creates to read in a .vg file, is there anything I can do in Java without diving into your core .hpp files and porting them??? I'd like to work directly with .vg files rather than convert to, say, .dot files, which would get really large!! But I'm not terribly interested in porting core vg into Java. I thought the Google Protocol Buffer implementation saved me from having to do that, which I was pretty excited about!

**Comment by glennhickey** [comment]
If you want to quickly look at your graph in a line or two of Java, I'd
suggest going through JSON (vg view -j).   It may not scale super well, but
the net result should look like something you'd get out of Protobuf if .vg
files could be read directly.

**Comment by adamnovak** [comment]
Sorry to disappoint. It would be nice to be able to just read the whole file in as one message. One reason we didn't choose that design was Protobuf's [maximum message size](https://stackoverflow.com/a/34186672/402891). Our graphs can reach multiple gigabytes of data, but Protobuf imposes a 64 MB size limit on messages by default, for "security", because large crafted messages can take forever to parse. Even if you decide your messages are trusted and lift that limit, there's a [2 GB limit on message size in Google's Protobuf implementation](https://github.com/protocolbuffers/protobuf/blob/9313cdc442c22bc62694742597ce7c543d195a73/src/google/protobuf/message_lite.cc#L421-L425), apparently because of the use of signed 32 bit numbers.

So even if we wanted to write just a single Protobuf message per file, we wouldn't be able to fit some of our graphs.

[Google's position](https://groups.google.com/d/msg/protobuf/7idXKu-dpwo/Y23CmsOvrf0J) on this problem is approximately "write your own framing format for streams of small messages"; the Protobuf library doesn't provide one. So that's what we did. [Their implementation of this pattern](https://github.com/xeno14/recordio) has finally made its way out of Google, but we didn't know about it when we were designing the vg formats, and it only seems to exist for C++ anyway.

We talk about Protobuf in the docs because we definitely do use it. All the IO is implemented in terms of things from the Protobuf library (which we have used for the messages themselves, the varint length prefixes, and, up until recently, the compression). You do need vg/src/vg.proto to consume a .vg file; you just also need to be able to parse the container that the serialized messages live in.

The .proto file also defines a JSON encoding (since Protobuf 3 has official conversions to/from JSON). You can turn a graph into JSON with `vg view -j graph.vg`, and parse that JSON either into Protobuf types in your target language with the Protobuf library, or into whatever convenient type you have for representing JSON data. It comes out of vg line-delimited, so you could get away with just parsing each line as a Protobuf message with (com.google.protobuf.util.JsonFormat.Parser)[https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/util/JsonFormat.Parser.html].

It would be handy for us to have an implementation for vg's container format in Java. I don't think we have any real Java people on our team, but we could probably figure it out.

**Comment by sammyjava** [comment]
Thanks, @adamnovak that's hugely helpful! Explains a ton. The deal with my project is that I'm going to be working with a variant graph containing many, many human genomes, so I'm trying to avoid gigantic text files like JSON. I was pretty excited about the binary compressed .vg format - until I hit this wall, since I'm working in Java. I'll sally forth with the JSON intermediary and ponder better possibilities down the line, maybe porting `stream.hpp`. Thanks!
