### ISSUE TITLE
Complete source release in one tar ball

### ISSUE THREAD

**Issue by jeizenga** [vgteam/vg#2034]
We had a user at Biohackathon express some frustration that the source tar balls for our releases don't include our dependencies, including dependencies which are very closely tied to the VG project (gssw, gbwt, gcsa). They requested that we provide a complete source tar ball in future releases. I don't really know the tradeoffs involved with this decision, so I'm just dropping the request here in the issues so we can discuss our options.

**Comment by adamnovak** [comment]
We could add making a source tarball to our release process. The easy way to do it is to do a fresh recursive checkout without building and then tar all that up. Doing a `make clean` on an existing checkout would also work, to the extent that our make clean completely cleans, but it might leave stuff behind to the extent that it doesn't, and it would obliterate all the built artifacts that you might want to still have around.

I'm pretty sure we can't make Github do it for us, though.

**Comment by mr-c** [comment]
That is good to hear @adamnovak , please let me know once you have one for me to test with Debian!

**Comment by adamnovak** [comment]
OK, I've added this step to the release process, and prepared a tarball for v1.13.0 on the release page. I've tested it and it seems to work.

The downside is that the resulting build declares its version as "unknown", since it has no .git and it doesn't seem to be preserving the existing version header. I'll see if I can do something about that in the Makefile, for the next release.
