### ISSUE TITLE
Wondering about pan-genomic paths

### ISSUE THREAD

**Issue by sammyjava** [vgteam/vg#2043]
My "issue" is that I'd like to use vg to construct a pan-genome graph with annotated paths for each biological sample that was used to create that graph. My simple example is attached.
[ecoli.pan3.tar.gz](https://github.com/vgteam/vg/files/2719735/ecoli.pan3.tar.gz)
I have a pan-genome consisting of three E.coli sequences, each truncated to 1000bp, one of which has a pair of SNVs (TT->GA and TTT->ACA at 302 and 306) w.r.t. the first, and the other also has a pair w.r.t. the first (CAT->GTC and TCC->AAA at 362 and 590).

So I appointed the first genome to be the reference and created a VCF representing the above variations for genome2 and genome3, adding genome1 as an all-REF sample.
```
##fileformat=VCFv4.2
##reference=file:ecoli.pan3.1.fa
##contig=<ID=1,length=1000,species="E.coli">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	genome1	genome2	genome3
1	302	var1	TT	GA	.	.	.	GT	1/0	1/0	0/1
1	306	var2	TTT	ACA	.	.	.	GT	1/0	1/0	0/1
1	362	var3	CAT	GTC	.	.	.	GT	1/0	0/1	1/0
1	590	var4	TCC	AAA	.	.	.	GT	1/0	0/1	1/0
I run
```
I run vg with
```
vg construct -r ecoli.ref.fa -v ecoli.pan3.vcf -f -m 1000 > ecoli.pan3.vg
```
All is good. I use `vg view` to ponder the result, and note that there is only one path listed
```
P	1	1+,3+,4+,6+,7+,9+,10+,12+,13+	301M,2M,2M,3M,53M,3M,225M,3M,408M
```
with no mention of a sample that it corresponds to. In fact, that's the reference.

So I have a path for the reference, but only "Links" for the other possible edges.

Is there a way for me to use vg to create sample-specific paths through the graph? And what I'd really like to do, if possible, is _map_ genomic short reads for each sample to a reference graph to build paths for each individual sample.

P.S. Right now, for the "production" runs which are entire or large fractions of human chromosomes, what I'm doing is using the sample VCFs with `bcftools consensus` to build individual FASTAs for each sample; then using `splitMEM -multiFa ...` to create a pan-genomic graph in a DOT file. But I love the idea of being able to build those pan-genomes directly with the raw reads and avoiding the variant-calling step. And even with the variant-calling step, like above, I'm wondering if I can use vg so I don't have to reconstruct the sample genomes.

Much appreciation for suggestions, pointers, etc.!!!

**Comment by ekg** [comment]
Here, you won't be able to use the given VCF file to embed paths for each genome because the genotypes aren't phased. (They are written like 0/1 instead of 0|1.) I assume the E. coli are haploid? If you make haploid calls then this phasing problem goes away. In order to put these into the graph as reference paths, you'll want to follow the [VCF to GBWT construction pattern](https://github.com/vgteam/vg/wiki/Index-Construction#with-haplotypes), then extract the paths from the GBWT. Here are the commands you'd do:

```
# build the graph
vg construct -r reference.fa -v variants.vcf.gz -a > graph.vg
# build the GBWT index
vg index -x graph.xg -G graph.gbwt -v variants.vcf.gz -g graph.gcsa graph.vg
# extract the threads from the GBWT as vg Paths
vg index -x graph.xg -G graph.gbwt -v variants.vcf.gz -g graph.gcsa graph.vg
```

This may seem a little convoluted, and that's because usually we're not making full Paths for each haplotype in a VCF file and in fact have no direct way to build graph Paths from the VCF file. Having a literal Path for each haplotype in a VCF file becomes very expensive with a large number of haplotypes, and we don't have good tools to work with Paths in this format. In GBWT we can do haplotype matching efficiently on large haplotype sets, which is generally the target application for such data.

It is technically possible to build the pangenome directly from reads, without variant calling, but the result will be very hard to work with. The basic idea would be to build an assembly graph with all the reads, then realign your reads into it, then build the GBWT from that set. You can also use minimap2, seqwish and a mutual alignment of your reads to do the same, or their alignment against the reference.

**Comment by sammyjava** [comment]
Thanks, @ekg ! That's exactly the sort of help I was looking for. And happy new year! Onward....

**Comment by sammyjava** [comment]
...and thanks for pointing out the diploid rather than haploid syntax, I'm used to plant and human genomes.  :)

**Comment by sammyjava** [comment]
Hey, @ekg , you repeated the second command as the third one. I'm still a bit mystified as to how I get the GBWT threads back into the vg graph as Paths.
```
# build the graph
vg construct -r reference.fa -v variants.vcf.gz -a > graph.vg
# build the GBWT index
vg index -x graph.xg -G graph.gbwt -v variants.vcf.gz -g graph.gcsa graph.vg
# extract the threads from the GBWT as vg Paths
vg index -x graph.xg -G graph.gbwt -v variants.vcf.gz -g graph.gcsa graph.vg
```

**Comment by sammyjava** [comment]
And I'll note that I'm aware that the -a option will record individual Paths for the allelic variants, but I'm looking for whole-graph paths for the sample haplotypes  (as you know).
```
P	1	1+,3+,4+,6+,7+,9+,10+,12+,13+	301M,2M,2M,3M,53M,3M,225M,3M,408M	
P	_alt_45438d5a6822fbc34b8fffacd7348968bf43e751_0	9+	3M	
P	_alt_45438d5a6822fbc34b8fffacd7348968bf43e751_1	8+	3M	
P	_alt_e915bc7d9a0b139562b0872aed791d28de867527_0	6+	3M	
P	_alt_e915bc7d9a0b139562b0872aed791d28de867527_1	5+	3M	
P	_alt_f689b649892bb5a1615546b481dc574ff6daf3df_0	12+	3M	
P	_alt_f689b649892bb5a1615546b481dc574ff6daf3df_1	11+	3M	
P	_alt_f9c4699fa7722501ac180e6ac4c854d1c276a888_0	3+	2M	
P	_alt_f9c4699fa7722501ac180e6ac4c854d1c276a888_1	2+	2M	
```

**Comment by glennhickey** [comment]
You can use `vg paths` to get your threads for sample SAMPLE as paths:
```
vg paths -x graph.xg -g graph.gbwt -V -q _thread_SAMPLE > SAMPLE_paths.vg
```
To add those paths back to your graph, you can use `cat`
```
cat graph.vg SAMPLE_paths.vg > graph_with_paths.vg
```

**Comment by sammyjava** [comment]
Thanks @glennhickey , worked like a charm!
```
P	_thread_genome1_1_0_0	1+,3+,4+,6+,7+,9+,10+,12+,13+	301M,2M,2M,3M,53M,3M,225M,3M,408M	
P	_thread_genome2_1_0_0	1+,3+,4+,6+,7+,8+,10+,11+,13+	301M,2M,2M,3M,53M,3M,225M,3M,408M	
P	_thread_genome3_1_0_0	1+,2+,4+,5+,7+,9+,10+,12+,13+	301M,2M,2M,3M,53M,3M,225M,3M,408M
```
