### ISSUE TITLE
Unexpected mapping scores in haplotyped alignments

### ISSUE THREAD

**Issue by tomokveld** [vgteam/vg#2046]
Hi,

While trying the haplotyping functionality I ran into some trouble interpreting the resultant alignments. At times the mapping scores appear to be very large negative/positive numbers (e.g. -737941398, 179053076).

For comparison here is a read alignment when running without haplotyping:
`"score":111`
```
{"sequence":"CGCCGGCCCAACCGGTTATCCACGGCCTCCCAGACTTGGCCCATACCACCGGTGGCGATGAGGCGCTGCAGGCGGTATCTGCCCGACAGCGTCACGCCAAC","path":{"mapping":[{"position":{"node_id":"195","offset":"992"},"edit":[{"from_length":8,"to_length":8}],"rank":"1"},{"position":{"node_id":"196"},"edit":[{"from_length":93,"to_length":93}],"rank":"2"}]},"name":"SRR847783.33291 ","quality":"Hx8fIyUlJSUnJicnGSUlJycoKCgoKSYmJx8lJycnKSkpKSgoKSgoKCglJycnJSUlJSMjIxgaHyEjGiEhIyIjIyMhISEhHSIjIyMjIyMjIyQgIiAgIR8jHyMjIyMhIyMjISMhIxs=","mapping_quality":60,"score":111,"identity":1,"refpos":[{"offset":"18649","name":"ref"}],"time_used":1101}
```

and the same aligned read using haplotyping:
`"score":179053076`
```
{"sequence":"CGCCGGCCCAACCGGTTATCCACGGCCTCCCAGACTTGGCCCATACCACCGGTGGCGATGAGGCGCTGCAGGCGGTATCTGCCCGACAGCGTCACGCCAAC","path":{"mapping":[{"position":{"node_id":"195","offset":"992"},"edit":[{"from_length":8,"to_length":8}],"rank":"1"},{"position":{"node_id":"196"},"edit":[{"from_length":93,"to_length":93}],"rank":"2"}]},"name":"SRR847783.33291 ","quality":"Hx8fIyUlJSUnJicnGSUlJycoKCgoKSYmJx8lJycnKSkpKSgoKSgoKCglJycnJSUlJSMjIxgaHyEjGiEhIyIjIyMhISEhHSIjIyMjIyMjIyQgIiAgIR8jHyMjIyMhIyMjISMhIxs=","mapping_quality":60,"score":179053076,"identity":1,"refpos":[{"offset":"18649","name":"ref"}],"time_used":1003,"annotation":{"haplotype_score":179052965.12209058,"haplotype_score_used":true}}
```

For reference this was using the static release of vg 1.12.1 - Parolise (6d6e41a).
Data (50 samples): https://www.dropbox.com/s/0oid2syrhynekvv/vg_50.zip?dl=0
Reproducible with the commands:
`vg construct -r ref.fasta -v 50.vcf.gz -a > 50.vg`
`vg index -x 50.xg -G 50.gbwt -v 50.vcf.gz -g 50.gcsa 50.vg`
`vg -f r1.fastq.gz -x 50.xg -g 50.gcsa -1 50.gbwt -M 2 > 50.gam`

**Comment by adamnovak** [comment]
I assume you mean that last command to be `vg map` and not just `vg`.

I added an assert for reasonable-looking scores, and turned on some debug prints in the haplotype scoring code, and it looks like the actual haplotype scoring algorithm is going a bit wrong.

```
### clusters:
clusters: 
1 MEMs covering 101 @ |2009+:29,1,TCCCGCCGGTGACCGATGACCGATCGGCTCCGCACGCGGACTCCATCGAGGCGGTCAAGGCCGCGCTCGACGGCGCGCCGCCGATGCCCCCGCCGCGCGAC 
After entry 0 (2009) height: 200 intervals: 200 score: 0.693147
After entry 1/6 (2010) height: 200 intervals: 200 score: 1.44322e+27
After entry 2/6 (2011) height: 200 intervals: 200 score: 2.88644e+27
After entry 3/6 (2012) height: 200 intervals: 200 score: 3.25888e+27
After entry 4/6 (2014) height: 98 intervals: 98 score: 3.25888e+27
After entry 5/6 (2015) height: 200 intervals: 102 98 score: 4.32965e+27
Applying haplotype consistency to 1 alignment candidates
Alignment statring at 2009 got logprob 4.32965e+27 vs 100 haplotypes, moving score by 3.32602e+27 from 111 to 0
vg: src/mapper.cpp:1755: void vg::BaseMapper::apply_haplotype_consistency_scores(const std::vector<vg::Alignment*>&): Assertion `score_penalty < 1000' failed.
```

That output value should be a log probability, and log(1) = 0, so it ought to be negative. It shouldn't be positive and extremely large.

Here are the nodes the path touches, drawn with our tube map. Nothing interesting seems to be happening here in the graph:

![image](https://user-images.githubusercontent.com/5062495/50922847-50395180-1400-11e9-9125-b23f264619fd.png)

Node 2009 is at `ref:53316`, which isn't near anything interesting in the VCF.

I will have to poke around @yoheirosen's scoring algorithm and see what's confusing it.

**Comment by adamnovak** [comment]
Weirdly, when I run the read by itself, it works:

But in context in the file, it fails:

```
align_multi_internal(1, TCCCGCCGGTGACCGATGACCGATCGGCTCCGCACGCGGACTCCATCGAGGCGGTCAAGGCCGCGCTCGACGGCGCGCCGCCGATGCCCCCGCCGCGCGAC, 0, 0, 256, 2, 128, 0)
mems for read [["TCCCGCCGGTGACCGATGACCGATCGGCTCCGCACGCGGACTCCATCGAGGCGGTCAAGGCCGCGCTCGACGGCGCGCCGCCGATGCCCCCGCCGCGCGAC",["2009:29"]]]
maybe_mq SRR847783.92232  inf 128 101 6.95336e-310 128 1 0 570.997 128
### clusters:
clusters: 
1 MEMs covering 101 @ |2009+:29,1,TCCCGCCGGTGACCGATGACCGATCGGCTCCGCACGCGGACTCCATCGAGGCGGTCAAGGCCGCGCTCGACGGCGCGCCGCCGATGCCCCCGCCGCGCGAC 
After entry 0 (2009) height: 200 intervals: 200 score: 0.693147
After entry 1/6 (2010) height: 200 intervals: 200 score: 0.693147
After entry 2/6 (2011) height: 200 intervals: 200 score: 0.693147
After entry 3/6 (2012) height: 200 intervals: 200 score: 0.693147
After entry 4/6 (2014) height: 98 intervals: 98 score: -0.0202027
After entry 5/6 (2015) height: 200 intervals: 102 98 score: -0.0202027
Applying haplotype consistency to 1 alignment candidates
Alignment statring at 2009 got logprob -0.0202027 vs 100 haplotypes, moving score by -0.0155196 from 111 to 111
```

But in the original file, it fails:                

```
align_multi_internal(1, TCCCGCCGGTGACCGATGACCGATCGGCTCCGCACGCGGACTCCATCGAGGCGGTCAAGGCCGCGCTCGACGGCGCGCCGCCGATGCCCCCGCCGCGCGAC, 0, 0, 256, 2, 128, 0)
mems for read [["TCCCGCCGGTGACCGATGACCGATCGGCTCCGCACGCGGACTCCATCGAGGCGGTCAAGGCCGCGCTCGACGGCGCGCCGCCGATGCCCCCGCCGCGCGAC",["2009:29"]]]
maybe_mq SRR847783.92232  inf 128 101 1.62772e-315 128 1 0 570.997 128
### clusters:
clusters: 
1 MEMs covering 101 @ |2009+:29,1,TCCCGCCGGTGACCGATGACCGATCGGCTCCGCACGCGGACTCCATCGAGGCGGTCAAGGCCGCGCTCGACGGCGCGCCGCCGATGCCCCCGCCGCGCGAC 
After entry 0 (2009) height: 200 intervals: 200 score: 0.693147
After entry 1/6 (2010) height: 200 intervals: 200 score: 1.44322e+27
After entry 2/6 (2011) height: 200 intervals: 200 score: 2.88644e+27
After entry 3/6 (2012) height: 200 intervals: 200 score: 3.25888e+27
After entry 4/6 (2014) height: 98 intervals: 98 score: 3.25888e+27
After entry 5/6 (2015) height: 200 intervals: 102 98 score: 4.32965e+27
Applying haplotype consistency to 1 alignment candidates
Alignment statring at 2009 got logprob 4.32965e+27 vs 100 haplotypes, moving score by 3.32602e+27 from 111 to 0
vg: src/mapper.cpp:1755: void vg::BaseMapper::apply_haplotype_consistency_scores(const std::vector<vg::Alignment*>&): Assertion `score_penalty < 1000' failed.
```

**Comment by yoheirosen** [comment]
Let me check it out. Won't have time for a few days though but I'll be on a
lighter clinical rotation

There might be a numeric error...

This is the one going through the linear bit right? If so I've got an 80%
finished rewrite to make the code more interpretable because there's a lot
of voodoo which I refactored for ease of following

**Comment by yoheirosen** [comment]
That could be even worse if I'm writing out of frame of an array. I thought
that I had verified that isn't happening there should be a debug version in
my code which looks for that and throws appropriate exceptions but if
single read is fine that sounds suspicious that something like that could
be sneaking in

**Comment by adamnovak** [comment]
This is using a graph GBWT haplotype index, not the SLLS code.

I'll see if I can find an uninitialized memory read or something to blame for this weird dependence on the input file. But I may end up needing your help to figure out how to actually fix it.

**Comment by yoheirosen** [comment]
Ok! Yeah I'll have bandwidth but will be next week

**Comment by adamnovak** [comment]
OK, so one problem here is some uninitialized memory reads related to an uninitialized `longest_lcp` being passed to `align_mem_multi`. I can fix that, but I think it's maybe unrelated.

But the real problem is right there in the debug logs I posted; the GBWT thinks we have 200 matches (height 200) when we only have 100 haplotypes (from 50 samples) in the VCF. This makes us read *way* out of bounds in logS_bases (which is only filled in up to 100) in the haplotype code, which somehow wasn't crashing everything.

And the reason we think that we have 200 hits is that **all the samples in the input VCF are unphased**. When generating the haplotype threads, we break the haplotype in two, and have some overlap of the haplotype threads, whenever we encounter adjacent variants that aren't in phase with each other. And since nothing is in phase with anything else, pretty much the whole graph is covered to double depth by haplotype threads, which is how we end up with 200 matches out of 100 haplotypes.

@tomokveld You probably want to pass in a phased VCF if you want to map using haplotype information. If you want to arbitrarily phase unphased things, you can use the `--force-phasing` option to `vg index`, but even that will not be useful in a **completely** unphased VCF like this one.

@yoheirosen What's the Right Way to robustify the haplotype consistency scoring algorithm to handle regions where there are more haplotype hits than there are real haplotypes in the database (either from these overlaps or from cycles, in the future)? I can just populate `logS_bases` out twice as big to avoid going out of bounds, so the algorithm will *run* safely, but I don't know if that's sufficient to make the scoring algorithm handle it well. Plus with cycles we may have more than just 2x the haplotypes in hits; any particular constant size of the table may be insufficient. (I guess requests for things outside the table can just be recomputed...)
