### ISSUE TITLE
VG crashed when performing index

### ISSUE THREAD

**Issue by yangxiaofeill** [vgteam/vg#2097]
Dear Colleagues,

          I have constructed vg using version 

`vg version v1.12.1-45-g88374fb "Parolise" Compiled with g++ (GCC) 4.9.2 on Linux`.

         However, when I index the graph using the following commands, vg is crashed.

```
vg index -t 20 -b temp -x SAMPLE.xg SAMPLE.vg

vg prune -t 20 -u -a -m node_mapping SAMPLE.vg > SAMPLE.pruned.vg

vg index -t 20 -g SAMPLE.gcsa -f node_mapping SAMPLE.pruned.vg
```
         The error message is:
```
vg: src/phase_unfolder.cpp:250: void vg::PhaseUnfolder::read_mapping(const string&): Assertion `this->mapping.begin() > this->xg_index.max_node_id()' failed.
ERROR: Signal 6 occurred. VG has crashed. Run 'vg bugs --new' to report a bug.
Stack trace path: /tmp/vg_crash_p9FEDQ/stacktrace.txt
ERROR: Signal 11 occurred. VG has crashed. Run 'vg bugs --new' to report a bug.
```

    Could you help me to address these problems?

**Comment by jltsiren** [comment]
You ran `vg prune` with option `-a`, which reads an existing node mapping file and appends the new mappings to it. The error message tells that the node identifiers used in the mapping overlap with the node identifiers used in the graph. It was most likely created for another graph and hence incompatible with your graph.

Because you have only a single graph file, you can omit the option `-a`, and `vg prune` will create a new node mapping file. The option is intended for indexing multiple graph files, where you get the initial mapping from `vg ids -j` and then append to it in each `vg prune` call.

**Comment by yangxiaofeill** [comment]
Thanks very much.
I will try.


Best
Xiaofei


-----------------------------------------------------------------------
Xiaofei Yang, PhD
Assistant Professor
xfyang@xjtu.edu.cn, yangxiaofeihe@163.com
School of Electronic and Information Engineering
Xi'an Jiaotong University
No. 28 Xianning West Road, Xi'an, Shaanxi.
 
2019-2-7
 
 
 
 
On 2/7/2019 21:29，Jouni Siren<notifications@github.com> wrote：

You ran vg prune with option -a, which reads an existing node mapping file and appends the new mappings to it. The error message tells that the node identifiers used in the mapping overlap with the node identifiers used in the graph. It was most likely created for another graph and hence incompatible with your graph.

Because you have only a single graph file, you can omit the option -a, and vg prune will create a new node mapping file. The option is intended for indexing multiple graph files, where you get the initial mapping from vg ids -j and then append to it in each vg prune call.
