### ISSUE TITLE
Calling against a cyclic path is not well-defined

### ISSUE THREAD

**Issue by alancleary** [vgteam/vg#2116]
I'm trying to call variants using the call operator, as described in the repo's readme:
```
vg call aug_graph.vg -b graph.vg -s aug_graph.support -z aug_graph.trans -r SEQ > calls.vcf
```
Unfortunately, the path I'm using as a reference is cyclic so the operator fails with the error "Some nodes occur more than once along the path SEQ being called against. Calling against a cyclic path is not well-defined." I'm wondering how I might go about making this path cyclic. There appears to be multiple options for the mod operator that could achieve this (-b, -d, -w, -L) but it is unclear which to use and how they might affect downstream analysis, i.e., variant calling.

Any guidance on this will be greatly appreciated, and thanks in advance!

**Comment by ekg** [comment]
How did you build the input graph?

**Comment by alancleary** [comment]
Thanks for the quick respone, @ekg. The input graph is a pangenomic de Bruijn graph constructed using a SplitMEM style tool. We then converted it to a vg graph with a program we wrapped ourselves.

**Comment by adamnovak** [comment]
The reason we don't support calling against a cyclic path right now is that we have to output VCF in the path's linear coordinate space. If you find a variant in a region of the graph that gets visited twice by the path, then you don't know which of the two possible linear positions it belongs at; it could even correspond to the entire cyclic loop around the whole path being replaced by a single base, if you make different decisions about how to place the two bounding nodes. And if the same site has two different "reference" alleles at different positions in the path, it would be quite hard for us to keep them straight.

If you just go and cut the cycles out of your path, you could get a VCF, but then you'd have to adjust the coordinates of that VCF to convert back to original path coordinates. Everything that came after a cycle loop that you had removed would need its coordinate increased by the length of the cycle that you removed.

To cut out the cycles, I don't think the "dagify" functionality in `vg mod` would work, nor would the `-b` cycle breaking. The graph itself is cyclic, and that's fine. The problem is that the path you are trying to call against goes around one or more of those cycles more than once.

You probably want some custom code to find a non-cyclic path between the start and end of your "real" path, and to put that in the graph. Then you can call variants in that path's coordinate space, and then lift them over to your true path of interest based on the alignment that the graph represents.

Does that help?

**Comment by alancleary** [comment]
Thanks for the thorough response, @adamnovak. It certainly does help. I guess I have a few options to explore. Cheers!
