### ISSUE TITLE
Read orientation in vg bam

### ISSUE THREAD

**Issue by yangxiaofeill** [vgteam/vg#2131]
Recently, I have constructed and indexed (xg and gcsa index without haplotype) the graph genome by VCF and GRCH37 reference. Then and mapped the reads to the constructed vg to generate the gam file. Then I surjected the gam file to bam file by "vg surject" command. I also sorted and indexed the bam file by samtools. 

Then, I compared the BWA bam file and vg BAM file in IGV, and colored the reads by "pair orientation", I found that reads orientation in vg BAM file are significantly different from that in BWA BAM file (the following figure, upper is the BWA BAM file, and down is the vg BAM file). I checked the reads and found the read orientation in vg BAM is different from that in BWA BAM file. 

I cannot understand this, and could you help me to explain such signals? Thanks very much.

![image](https://user-images.githubusercontent.com/26217004/53374045-3eb2f700-3925-11e9-8e2c-8dd89e220bd3.png)

**Comment by jeizenga** [comment]
Aside: this seems to have also been mentioned in the comments of https://github.com/vgteam/vg/issues/1724

**Comment by adamnovak** [comment]
Hello @yangxiaofeill,

This might have to do with the bad MREVERSE BAM flag that VG was outputting before Glenn fixed it in #2127.

If we compare your screenshot to the key at http://software.broadinstitute.org/software/igv/interpreting_pair_orientations then it looks like the coloring and the pointy end of the shapes representing the read should correspond. Only reads pointing right should ever be light blue, for example, because light blue indicates a pair of reads that both are pointing right (aka from the "left" strand, "LL"). Also, both reads in a pair should be the *same* color.

That's not what we're seeing here. We have reads in pairs (indicated by the lines between them, right?) that are different colors, and all our light blue reads are pointing left. This indicates to me that the BAM file we have emitted has self-inconsistent flags (i.e. the ends have incorrect values for their mates' orientations), and IVG is doing its best to make some sense of them when drawing the pair.

What version of `vg` did you use to surject (`vg version`)? And can you try again with one that includes Glenn's #2127 flag fix (i.e. current master)? We can probably build you a binary if you need it.

If you still see this with current master vg, after Glenn's patch, would it be possible for us to get access to your .xg file, and at least a partial GAM file of reads that exhibit this issue with weird read orientations in pairs? Those would be useful for debugging.

**Comment by yangxiaofeill** [comment]
Hello @adamnovak 
Thanks for your response. Yes, I actually checked the flag information of paired read in vg bam, and found they are not consistence. For example:

`<table><tr><td valign="top"><b>Left alignment</b><br/>Hap name: null
Dist: 0
Read name = E00440:101:HJW3TALXX:8:1211:22150:13879 
Read length = 150bp
----------------------
Mapping = Primary @ MAPQ 60
Reference span = chr5:60,587,158-60,587,307 (-) = 150bp
Cigar = 150M
Clipping = None
----------------------
Mate is mapped = yes
Mate start = chr5:60587522 (+)
Insert size = 0
First in pair
**Pair orientation = R1F2**
<hr>Location = chr5:60,587,278
Base = G @ QV 41
</td><td valign="top"><b>Right alignment</b><br/>Hap name: null
Dist: 0
Read name = E00440:101:HJW3TALXX:8:1211:22150:13879 
Read length = 150bp
----------------------
Mapping = Primary @ MAPQ 60
Reference span = chr5:60,587,523-60,587,672 (+) = 150bp
Cigar = 150M
Clipping = None
----------------------
Mate is mapped = yes
Mate start = chr5:60587157 (+)
Insert size = 0
Second in pair
**Pair orientation = F1F2**
</td></tr></table>
Alignment start position = chr5:60587158
null `

The flags of these two read are 83 and 131.  As we know, the correct mate flag of 83 should be 163 rather than 131, and correct mate flag of 131 should be 67. So I think the flag may have some problems in surjecting step. 

The vg version I used is 

`vg version v1.12.1-45-g88374fb "Parolise"
Compiled with g++ (GCC) 4.9.2 on Linux
Built by c-yangx@helix180 `

I will try the flag fix you mentioned. Thank you. If there are some other questions, I will contact you.

Best
Xiaofei

**Comment by yangxiaofeill** [comment]
Hell @adamnovak 

I have tried use `samtools fixmate`, and it works well, the orientations have been corrected. 
Thanks.

Best
Xiaofei

**Comment by ekg** [comment]
Has this been fixed in master?

**Comment by adamnovak** [comment]
I believe the underlying problem was fixed in #2127.
