### ISSUE TITLE
obtain a list of bubbles and superbubbles

### ISSUE THREAD

**Issue by ekg** [vgteam/vg#237]
It's useful to think about the bubbles and superbubbles of a sequence graph. Debugging the process that gives you the list of bubbles is important, and at a basic level it can be used for other kinds of inspection of vgs.

You can get a description of the strongly connected components of the graph using `vg stats -c`. Bubbles could be described in a similar way.

There are some nice recent to do this. For instance, see [Linear-Time Superbubble Identification Algorithm for Genome Assembly](http://arxiv.org/abs/1505.04019). I'm asking the authors if they have an implementation available.

**Comment by ekg** [comment]
@edawson what's the status of this? Is there a CLI we could hook up to for testing?

**Comment by edawson** [comment]
There is a method in vg.hpp: `vector<pair<id_t, id_t> > VG::get_superbubbles()` that returns a vector of endpoints for each superbubble in the graph. However, it's not optimized; I'm copying the graph into the supbub interface and haven't pushed things to operate directly on the VG like I should.

Getting all the bubbles of the graph is a bit messier. I haven't touched that since the previous version of deconstruct which blew up on the 1kg1mb graph.

**Comment by edawson** [comment]
As to testing at the CLI, there is a bit of access from `deconstruct`. If it's urgent I can push it to the team branch otherwise I was going to bring it in with a more complete version.

**Comment by ekg** [comment]
Not urgent at all, I was just wandering through from the waffle board.
