### ISSUE TITLE
VG Prune Crash

### ISSUE THREAD

**Issue by cademirch** [vgteam/vg#2381]
Please describe:

1. What you were trying to do
Pruning chromosome graphs with GBWT indexes for GCSA indexing. The first chromosome was pruned successfully, however the next crashes; This is the command I ran:
```
./vg prune -u -g chr2.gbwt -a -m mapping -p chr2vg > chr2.pruned.vg
```
2. What you wanted to happen
Prune graphs to create a whole genome GCSA index for read alignment. 
3. What actually happened
```
vg: src/phase_unfolder.cpp:250: void vg::PhaseUnfolder::read_mapping(const string&): Assertion `this->mapping.begin() > this->xg_index.max_node_id()' failed.
ERROR: Signal 6 occurred. VG has crashed. Run 'vg bugs --new' to report a bug.
```
Stack trace:
```
Crash report for vg v1.17.0 "Candida"
Stack trace (most recent call last):
#9    Object "/public/groups/corbettlab/cade/filtered_maf-0.02_global-0.02/index/vg", at 0x4d6269, in _start
#8    Object "/public/groups/corbettlab/cade/filtered_maf-0.02_global-0.02/index/vg", at 0x1a3f1f8, in __libc_start_main
#7    Object "/public/groups/corbettlab/cade/filtered_maf-0.02_global-0.02/index/vg", at 0x409832, in main
#6    Object "/public/groups/corbettlab/cade/filtered_maf-0.02_global-0.02/index/vg", at 0x97f927, in vg::subcommand::Subcommand::operator()(int, char**) const
#5    Object "/public/groups/corbettlab/cade/filtered_maf-0.02_global-0.02/index/vg", at 0x96c902, in main_prune(int, char**)
#4    Object "/public/groups/corbettlab/cade/filtered_maf-0.02_global-0.02/index/vg", at 0xcd4c07, in vg::PhaseUnfolder::read_mapping(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
#3    Object "/public/groups/corbettlab/cade/filtered_maf-0.02_global-0.02/index/vg", at 0x1a43111, in __assert_fail
#2    Object "/public/groups/corbettlab/cade/filtered_maf-0.02_global-0.02/index/vg", at 0x1a4309b, in __assert_fail_base
#1    Object "/public/groups/corbettlab/cade/filtered_maf-0.02_global-0.02/index/vg", at 0x1a4fac0, in abort
#0    Object "/public/groups/corbettlab/cade/filtered_maf-0.02_global-0.02/index/vg", at 0x10b47a7, in raise
```
4. These are the steps I've done up until this point:
```
/vg construct -a -C -R {chr} -r {ref} -v {vars} -t 1 -m 32 > {chr}.vg
/vg ids -j chr_*.vg
/vg index -G  {chr}.gbwt -v {vars} -P -o {chr}.gbwt

```

**Comment by jltsiren** [comment]
The error message is about the node mapping file that tells how to map the identifiers of duplicated nodes from `vg prune -u` to their original identifiers. The first id assigned to duplicated nodes `this->mapping.begin()` must be larger than any node identifier `this->xg_index.max_node_id()` in the original graphs. Otherwise GCSA indexing would not know which nodes are duplicates and which are originals.

As mentioned in the wiki page on [index construction](https://github.com/vgteam/vg/wiki/Index-Construction), a suitable empty node mapping can be generated by adding `-m mapping` to the `vg ids -j` command. If you have already harmonized the node ids with `vg ids -j`, you can generate the empty node mapping by rerunning `vg ids` with `-m mapping` but without `-j`. (Running `vg ids -j` multiple times is not recommended.)

After you have generated the empty node mapping, you should rerun `vg prune` for all chromosomes.

**Comment by cademirch** [comment]
Ah thank you. I completely missed that I needed to use ids to make the empty node mapping. I will try that and report back.

Thank you!
