### ISSUE TITLE
restart GCSA indexing with temporary outputs

### ISSUE THREAD

**Issue by vinimfava** [vgteam/vg#2422]
Hi

I am following the (https://github.com/vgteam/vg/wiki/Working-with-a-whole-genome-variation-graph) to create a graph for human genome with a custom VCF. Everything worked fine until I got the "bus error" on GCSA indexing with the following command:

$WORKINGDIR/vg index -p -t 32 \
-b $SCRATCH \
-g $WORKINGDIR/VG_alignment/hg38_all_anno.gcsa \
$(for i in $(seq 1 22; echo X; echo Y); do echo $WORKINGDIR/VG_alignment/"chr"${i}.pruned.vg; done)
 
ERROR output:
......
PathGraph::extend(): 631.1 GB in 24 file(s)
GCSA::GCSA(): Prefix-doubling: 60893.4 seconds, 96.2 GB
GCSA::GCSA(): Merging the paths
MergedGraph::MergedGraph(): 11870682601 paths with 52978059512 ranks and 648849192 additional start nodes
MergedGraph::MergedGraph(): 483.4 GB
GCSA::GCSA(): Merging: 12874.8 seconds, 96.2 GB
GCSA::GCSA(): Building the index
/var/spool/slurmd/job26594393/slurm_script: line 26: 157189 Bus error   

I was using 32 cores and 250GB of memory in an HPC cluster. I think I ran out of memory while building the index but I still have all the temporary files "gcsa_" and "vg-kmers"

Is there a way to restart the index using the pre-existing tmp files?

Thanks

**Comment by jltsiren** [comment]
You can restart the indexing from the `vg-kmers` files by using the `-i FILE` option, but this won't save you much time. The `gcsa_` files do not contain all the necessary context information, so they are mostly useless if the indexing process crashes.

As for the bus error, I don't think it was caused by running out of memory. Is the vg binary on an NFS drive, and did you recompile or otherwise replace it while the indexing process was running? I have accidentally done this a few times myself, and it's the only reason I have ever seen bus errors.

**Comment by vinimfava** [comment]
Hi Jouni,

Thanks for the response. I don't have a good explanation why, but when I reran the job using 450GB of memory and saving the GCSA output in the same scratch directory solved the problem. Now I have my index files. Thanks for the support

V
