### ISSUE TITLE
How to extract specific regions(ex, chr1:100-200 of hg38) from whole genome VG files

### ISSUE THREAD

**Issue by hd00ljy** [vgteam/vg#2583]
I built a .vg from structural variation VCF file and I want to examine if the records in VCF are well represented in the .vg file.

What I want to do is as follows.

For example, I have an Insertion(INS) at chr1:100 on hg38. I want to get nodes overlapping chr1:50-200 along with nodes that correspond to the Insertion.

But since I can not find any labels(variant IDs or chromosomal coordinates) on the graph when I converted .vg to .dot, I was not able to extract specific regions or nodes adjacent to specific SVs.

I looked through the wiki and github issues but I was not able to find the solutions.

Could you help me on this?

**Comment by ekg** [comment]
The coordinate system is given by the paths in the graph. But, we don't label the nodes with the coordinates in the output data formats. The correspondence is implicit, and is made explicit only during indexing into the XG index format, which is a static, succinct data structure that supports random access to the graph by path position.

What you are doing is well supported though. First, index the graph into an xg:

```
vg index -x x.xg x.vg
```

Then, supply the .xg format graph to `vg find` with the desired region:

```
vg find -x x.xg -p chr1:50-200 -E >chr1_50-200.vg
```

This assumes that your graph is built from a linear reference and set of variants. The query finds the start and end node, and then gets everything between them in the partial order of nodes.

If it isn't, you'll need to use the context expansion mode to get all the nearby nodes. This takes two steps from the set of nodes in the target path range, which should be enough to collect all SNPs and indels:

```
vg find -x x.xg -p chr1:50-200 -c 2 >chr1_50-200.vg
```

This is documented in this part of the `vg find --help` output:

```
subgraphs by path range:
    -p, --path TARGET      find the node(s) in the specified path range(s) TARGET=path[:pos1[-pos2]]
    -R, --path-bed FILE    read our targets from the given BED FILE
    -E, --path-dag         with -p or -R, gets any node in the partial order from pos1 to pos2, assumes id sorted DAG
    -W, --save-to PREFIX   instead of writing target subgraphs to stdout,
                           write one per given target to a separate file named PREFIX[path]:[start]-[end].vg
    -K, --subgraph-k K     instead of graphs, write kmers from the subgraphs
```

Note that you can supply a BED file or multiple `-p` targets, and write each region to a new file by adding a `-W xxx` prefix value. This makes it easy to scale up to thousands of regions. Otherwise, you'll waste a lot of time loading the xg index for each region.

---------

An aside, to the rest of the development team:

We probably should start labeling the output GFA with coordinates by default, because a lot of people find this confusing. The implicit nature of the coordinates makes it seem that there isn't a stable coordinate system. (CC @adamnovak @glennhickey @jeizenga ...). It's currently possible to do this with the [xg tool](http://github.com/vgteam/xg) itself. Writing the graph in GFA will result in annotations (in JSON format) that say what chromosome and position each node is at. Maybe we should do something similar by default in vg. rGFA would be a solution, but it is limited to a single reference coordinate at any graph position, which will break in any graph that we build from whole genome alignments. I'd suggest that we start working on a vGFA specification that fully supports our use case and defines a format for specifying node coordinates relative to paths.

**Comment by hd00ljy** [comment]
Thank you very much for your detailed reply!

**Comment by ekg** [comment]
Glad this helped.

Did you expect positional annotations in the GFA?

I'd like to improve user experience on this point. Most people, including
bioinformatics researchers, seem inclined to disbelieve the coordinate
system in variation graphs even after it's explained. I keep thinking it's
just that we don't make it doubly explicit in the serialization format.

**Comment by hd00ljy** [comment]
I think it would be more comfortable if the positional information is available even after I converted the binary VG files into some text files like dot or GFA.


Actually It's hard for me to say whether I expect certain features or not. since I don't have much experience in genome assembly or graph representation.

But since many external meta data including transcripts gff3 or epigenome bigwigs usually use common coordinate systems such as hg19 or hg38 as of human data, it would be more comfortable to associate variation graphs with those external meta data if I can directly see and manipulate the positions.


------------
Additionally, it would also be great if I can see the annotation of variant IDs on the edges and nodes for VG built from a VCF.

**Comment by adamnovak** [comment]
This sounds to me like a use case for subpaths. We can represent the whole GCRh38 chromosome paths as embedded in the full genome graph (and they come out in the dot when you use `-p`), but as soon as we take a subgraph we have no way to represent the *portions* of those paths that overlap the subgraph. I think right now we just sort of hack around the problem and produce paths in the subgraph that have the right name and take the right nodes but don't really record their starting offset. But we could instead adjust our concept of a path to include a starting offset, so it is easier to work with reference genome coordinates in subregion graphs.

We could also have a way to spit out GFA annotated with per-node path positions, but unless we keep track of subpath start offsets when computing the subgraph, we won't have global coordinates available when writing the subgraph GFA.

As for annotating the graph with variants, if you use the `-a` option to `vg construct` it will create "alt paths" that trace where each allele of each variant in the VCF gets embedded in the graph. But those paths are named using a hash of the variant (so you can really only find the path for the variant, and not the other way around), and there's not really much CLI tooling for working with them (because we really only use them as intermediates for building the GBWT haplotype index). Also they get discarded when building the XG, unless you provide `-L` to `vg index`.

If you want, we could maybe add something to `vg find` that lets you feed in a VCF and then selects the part of the graph covered by the variants' alt paths.

**Comment by glennhickey** [comment]
I had an option in a branch (that I never merged in) that had vg construct
use the VCF variant ID instead of a hash for the alt paths.  Something like
that could probably help here.  Or perhaps changing the naming scheme to
use the variant ID by default when possible.  I think a lot of users would
appreciate this.

Another hack that may be relevant:  vg chunk now stores the starting offset
in the path name of subpaths in the output.  This is enabled with a flag in
add_subpaths_to_subgraph() in subgraph.hpp.  It is trivial to toggle this
on in vg find.  It's not ideal, but it is a way to get the subpath
information into the subgraph with the formats we have now.
