### ISSUE TITLE
vg index: xg construction memory usage increase 

### ISSUE THREAD

**Issue by mlin** [vgteam/vg#267]
I'm noticing memory usage in `vg index` to build the xg index has increased quite a lot in the last few weeks. Previously and for a long time, this operation maxed out at roughly 200 GiB of RAM on the whole-genome 1000G graph. Now I see it blowing through the machine's 244 GiB. Is this expected, anything to be done?

(Edited to remove misleading reference to gcsa2)
(Edited to remove misleading reference to 435c97c)

**Comment by ekg** [comment]
I'm surprised that you are able to get the whole genome indexing to work
directly from vg index. It should be supported, but I am not yet sure
exactly how to implement it. The typical approach I have followed for the
1000G graph is to use vg kmers to make GCSA2 binary deBruijn graphs for
each chromosome, then feed these into the build_gcsa utility. The
documentation does need be updated to reflect the generation of the LCP
array that is used for counting and parent queries. Memory usage should be
well below 100G maximum. I think @jltsiren's tests show under 40G during
build_gcsa.

**Comment by mlin** [comment]
Sorry I got a bit mixed up -- I mean the use of `vg index` to build the xg index, the first step in: https://github.com/vgteam/vg/wiki/working-with-a-whole-genome-variation-graph#xggcsa-index-high-memory-build-low-memory-runtime-fast

So i'm not getting to the kmers or GCSA2...

**Comment by adamnovak** [comment]
You need https://github.com/vgteam/xg/commit/9fda90e46546956195cc8694da0d0282fe0283f3 which came in with #25. I'll make a PR to update vg to use that xg.

**Comment by mlin** [comment]
Thanks @adamnovak - I'm launching a build from your PR now

**Comment by ekg** [comment]
I've merged your PR in @adamnovak.

**Comment by adamnovak** [comment]
Does it actually solve your problem, Mike?

**Comment by mlin** [comment]
I hit the same OOM error with 93d26266 unfortunately. Are there any other quick things to try? If not, I can try some git-bisect although the iteration time is slow unfortunately.

**Comment by adamnovak** [comment]
OK, I am looking at this a bit more closely. I thought you were talking about some older commits where I brought in the succinct thread storage, but it seems that that is not your problem if you've made it work successfully with anything after, say, c621d413b707278194f32540fdedbd7f7b64dd47.

435c97c is actually where my much more recent code to track paths for alts from the VCF comes in, but that's all in `vg construct`, so it's odd that `vg index` would be your failing step. And since the hash-based tests pass, the graphs constructed are really supposed to be identical to the graphs made the old way, as long as you don't pass -a (or -P for the older include-phase-paths-in-construction code) to vg construct.

Can you give me a commit for a known working vg?

Are the .vg graphs you build with the known working vg different from the graphs on which your indexing is failing with the new vg? (Can we blame the problem on `vg construct` making harder-to-index graphs, or is something really wrong with `vg index`?) Usually I think we diff the graphs by doing `vg view graph.vg | md5sum` and comparing the hashes, to control for protobuf chunking.

**Comment by ekg** [comment]
I thought the problem was that the memory usage during xg construction went
way up. How does the callback based construction work? Maybe we could drop
the memory usage by making several passes over the graph file rather than
trying to store it all in memory. std::map is not very space efficient.

**Comment by adamnovak** [comment]
The build-by-callback setup for xg sort of just exposes the lambda that was used by `from_stream` and passed down to `stream.hpp` to receive graph chunks. Instead of giving xg a stream and having it use `stream.hpp` to pull out chunks and process them, xg will call you back, giving you the chunk-processing function, and you feed chunks into it and then return when you are out of chunks.

I set it up like that to get rid of the `system()` call in `VGset::to_xg()`. Previously, you had to concatenate all your vg graphs together on disk and then run them through `XG::from_stream()`. Now, you can use `XG::from_callback()`, and loop over the individual vg files on disk with `stream.hpp`, feeding all the chunks into the same ingestion function that you got from XG. Just like before, the chunks themselves should be getting discarded after use, with all the important information ending up in the xg construction intermediates.

In the commit that @mlin cited originally as having the bug, the old construction functions are being called. See https://github.com/vgteam/vg/blob/435c97cd4530ec979916a57fcd5ee660ffc06b2c/src/vg_set.cpp#L60-L85 and the xg it references at https://github.com/vgteam/xg/blob/dd41c32972af30f1f0ee9d8b6c1fe4d6aa2b1c69/src/xg.cpp#L344. So unless there are two memory usage regressions, it can't be that.

Which map are you referring to? I threw some new maps into *vg* construction, but if I did it right they *should* all be empty unless you pass one of my new options.

**Comment by mlin** [comment]
On reviewing the history, I can't reconstruct the basis of my statement that the mem usage arose "with the last one or two commits before/including 435c97c on master." I think I got myself confused and I'm sorry this may have led you down some dry wells.

My last good whole-genome xg index was actually back on v1.4.0, so the possible causal variants are quite wide-ranging. I'm going to think about how to set up a smaller regression test to use with git bisect.

**Comment by adamnovak** [comment]
Hm. That is quite far back.

I think you might want to try https://github.com/vgteam/vg/tree/47c121c677469ef1749bd8b37f04c80828528845 which is the last commit before my dramatic changes to construct, and my xg succinct thread stuff, went in. If that works, we could probably assume that something I did in my push for new path features managed to break it.

**Comment by mlin** [comment]
WIP update: I have run a build using 36d8cdff and found the peak memory usage in `vg index` is intermediate between v1.4.0 and HEAD. This suggests unfortunately we're probably not looking at just one problematic change, but possibly an accumulation of several things.

With v1.4.0 (and prior versions going back to Leiden!) the memory usage in `vg index` peaks around 200GiB. With HEAD it blows out the machine's 244GiB. In 36d8cdff it peaks around 225GiB (and is able to complete).

That's all the data I have right now...there's unfortunately some friction in going back to old versions due to a few of the old submodule revisions having disappeared or moved around. I still think it'll be possible to set up a more automated harness with a smaller benchmark, but it'll take some focused hacking.

General observation- if there are 'dramatic changes to construct' as @adamnovak mentioned, perhaps we shouldn't even expect the same memory usage in order to index a substantially different graph structure'? Does this seem true?

**Comment by ekg** [comment]
@mlin what is HEAD here? There have been relevant changes in the last day.

I don't think the default code path in construct is dramatically changed.

That said, I'm just now running a test with d23242a9. I'll report here if I see the same issues.

**Comment by mlin** [comment]
Sorry, HEAD is definitely not from the last day (since it takes a day :). I'll kick one off shortly too.

**Comment by adamnovak** [comment]
There are dramatic changes to the construct *code*, but unless any of the
new options are invoked the output *graphs* are supposed to be exactly the
same (at least as before my changes; not sure if anything else changed back
to 1.4.0.).

Do you still have (some of) the .vg files from these runs, to compare?

**Comment by ekg** [comment]
@mlin I've reproduce the problem locally.

I'm confused by why things got worse. To see I'll need to bisect xg. In general the construction was already very memory-hungry. It stores the entire graph in temporary maps. I am considering an alternative way of doing it. I'll see what I can implement today.

**Comment by ekg** [comment]
The big change seems to be that we moved to `Sides`, which are pairs, rather than just ids in the edge maps. I think I can shift into using a set of dynamic wavelet trees, but I don't have a design yet.

**Comment by ekg** [comment]
@mlin This should be resolved with the merge of #277.

The resulting xg index is rather large (30G!) so we have also bloated that by adding in all the flags and other things necessary to handle the reverse complement of the graph and paths over it.

I think it is very possible that appropriate use of compression on some of the components of the xg index will help us get this down by up to a third. Something silly is lurking in there.

**Comment by mlin** [comment]
Alright- I'm giving it a try!

**Comment by mlin** [comment]
Looking GOOD! Mem usage for xg stayed <170GiB for the 1000G graph. build_gcsa <60GiB. 

I am still using the [old recipe](https://github.com/vgteam/vg/wiki/working-with-a-whole-genome-variation-graph#xggcsa-index-high-memory-build-low-memory-runtime-fast) to prepare the graph for build_gcsa ([exact code](https://github.com/dnanexus-rnd/dxvg/blob/xg/applets/vg_index/src/code.sh#L17)) -- LMK when there's a new one!

**Comment by ekg** [comment]
What is the pruning on this?

**Comment by mlin** [comment]
The defaults I'm using at https://github.com/dnanexus-rnd/dxvg/blob/xg/applets/vg_index/src/code.sh#L22 are:
prune_complex_options: -l 16 -e 2
prune_subgraph_options: -l 100

**Comment by ekg** [comment]
I've tried with -l 16 -e 3 and -l 32. I've needed to set the memory limits
on GCSA2 higher, using -Z 500. I thought this was now the largest graph
size *on disk* rather than in-memory. Watching the job today suggests that
it should be fine. We'll see if I regret it.

Here's my process for building the index (assumes 16 CPUs):

    # generate the deBruijn graph
    vg mod -pl 16 -t 8 -e 4 -t 16 $chr.vg \
        | vg mod -S -l 32 - \
        | kmers -gB -k 16 -H 1000000000 -T 1000000001 -t 16  - >$chr.graph
    vg index -g wg.k32.gcsa -Z 500 -X 2 $(for i in $(ls *.graph); do echo
-n " -i $i"; done)

It's been running since my morning using no more than 80G, but usually
quite a bit lower.

Note that we could break it into smaller pieces. I'm thinking about how to
do that because it's basically impossible for me to run this process
reliably at the sanger due to extremely long wait times on our cluster for
jobs that need many CPUs.

I could generate subgraphs using regions in the xg index, then generate the
graphs of these, then run gcsa2 on that. I'm going to test if this works.
