### ISSUE TITLE
read-log-likelihood returns zero when it shouldn't

### ISSUE THREAD

**Issue by code-s-witch** [vgteam/vg#2820]
**1. What were you trying to do?**
Sometimes when I call read-log-likelihood from within my mcmc_genotyper code, it returns score = 0 for every multipath alignment and that is wrong when I compare it to the optimal_score_on_genome. I noticed that read-log-likelihood returns sensible scores when I build mp alignments manually and score = 0 when  mp alignments are built using multipath_mapper. 

**2. What did you want to happen?**
I want optimal_score_on_genome and read_log_likelihood to agree with each other. 

**3. What actually happened?**
read_log_likelihood is returning 0 for all reads and the total score is adding up to 0 which does not agree with the previous implementation using optimal_score_on_genome. 

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

```
Place stacktrace here.
```

**5. What data and command can the vg dev team use to make the problem happen?**
When I run `vg test Test10` read-log-likelihood returns a sensible score, and when I run `vg test Test6` read-log-likelihood returns a zero score for every mp alignment. 

I have a branch called `read-log-likelihood` if you run [Test6 ](https://github.com/vgteam/vg/blob/47105f0899f4295d96647731f1ac1ad26d14d1b9/src/unittest/mcmc_genotyper.cpp#L614-L734) you can reproduce the behavior. Test9 and Test10 are structured similar to a unit test from phased_genome that tests read_log_likelihood. Test9 is almost identical to identical from phased_genome unit test (https://github.com/vgteam/vg/blob/47105f0899f4295d96647731f1ac1ad26d14d1b9/src/unittest/phased_genome.cpp#L1269-L1311) but includes a call to mcmc_genotyper instead of manually creating haplotypes, and it works as expected. [Test10](https://github.com/vgteam/vg/blob/47105f0899f4295d96647731f1ac1ad26d14d1b9/src/unittest/mcmc_genotyper.cpp#L1107-L1201)  is similar to Test9 but it uses multipath_mapper instead of building mp alignments manually and also calls mcmc_genotyper to build haplotypes. Test6 is similar to Test10 in that they follow the same workflow but Test6 has more reads and a slightly bigger graph. 
**6. What does running `vg version` say?**

```
vg version v1.21.0-1109-g65dabe0c0 "Fanano"
Compiled with g++ (GCC) 8.1.0 on Linux
Linked against libstd++ 20180502
```

**Comment by jeizenga** [comment]
Can you point me at a branch I can use to reproduce the bug? It's hard to test a few source files without the rest of the project.

**Comment by code-s-witch** [comment]
I just made a branch called read-log-likelihood.

**Comment by code-s-witch** [comment]
@jeizenga I updated comments on the issue to summarize the problem better.

**Comment by jeizenga** [comment]
@code-s-witch Sorry to have been slow to get to this, I misunderstood where we were with it.

The problem (at least in Test6) is that the mapping quality of the reads is 0. This is because multipath mapper that you're using hasn't had its mismapping detection calibrated to the graph you're mapping to, so it's using the default parameters, which are trained on a graph of the whole human genome. Thus, the mapper thinks that a score of 22 is indistinguishable from a score obtained from mapping a random sequence and therefore gives the mapping a low quality.

There are two possible solutions. First, you could calibrate the mapper in the unit test. That would probably fix this problem, but calibration can take several minutes and you will need to do it in every test. The second option is to manually adjust the mapping qualities in the unittests. That is probably the more expedient option since ideally we want the unit tests to run fairly quickly.

**Comment by code-s-witch** [comment]
Hi Jordan,

I looked at unittest 10 where i used the mp mapper and it seems i set the
quality score before calling the mp mapper and it was overwritten.
I will test again and set the quality score manually on all unittests that
either don't have it set or are set prematurely (eg. test 6 ).

Best,
Susanna

**Comment by jeizenga** [comment]
Yes, that would happen. It's intentionally setting the mapping quality to 0 to indicate that it isn't confident in the mapping, so you will actually need to adjust the mapping quality _after_ mapping.
