### ISSUE TITLE
giraffe produces free-floating insertion

### ISSUE THREAD

**Issue by glennhickey** [vgteam/vg#2833]
From what I gather, this happens with dozeu but not without. @jmonlong would have the command line and indexes to reproduce.

full gam: s3://vg-k8s/users/jmonlong/hsvlr_srdedup17_aug/indexes/HG00514_961a37c/HG00514_961a37c-hg38-hsvlr_srdedup17_aug.gaffe39k15w16N.gam
xg: s3://vg-k8s/users/jmonlong/hsvlr_srdedup17_aug/indexes/hg38-hsvlr_srdedup17_aug.xg
```
{
  "annotation": {
    "fragment_length": 1098,
    "fragment_length_distribution": "-I 542.973684 -D 141.206118",
    "mapq_applied_cap": 46.364361584299516,
    "mapq_extended_cap": "Infinity",
    "mapq_uncapped": 1.5051499783199018,
    "rescued": true,
    "secondary_scores": [
      99.4157375734459
    ]
  },
  "mapping_quality": 1,
  "name": "ERR903030.51990324",
  "path": {
    "mapping": [
      {
        "edit": [
          {
            "sequence": "GGGCACGGTGGCTCACAGCTGTCACCACNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
            "to_length": 126
          }
        ],
        "position": {
          "is_reverse": true,
          "node_id": "91194329",
          "offset": "15"
        },
        "rank": "1"
      }
    ]
  },
  "quality": "ISEhICEhJCIkJiYdJiUQJSYmHyMmIxAkJiICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC",
  "sample_name": "HG00514_961a37c",
  "sequence": "GGGCACGGTGGCTCACAGCTGTCACCACNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
}
{"annotation": {"fragment_length": 1098, "fragment_length_distribution": "-I 542.973684 -D 141.206118", "mapq_applied_cap": 46.364361584299516, "mapq_extended_cap": 46.364361584299516, "mapq_uncapped": 1.5051499783199018, "rescuer": true, "secondary_scores": [99.415737573445895]}, "identity": 0.95238095238095233, "mapping_quality": 1, "name": "ERR903030.51990324", "path": {"mapping": [{"edit": [{"from_length": 26, "to_length": 26}], "position": {"node_id": "91185277", "offset": "6"}, "rank": "1"}, {"edit": [{"from_length": 23, "to_length": 23}, {"from_length": 3}, {"from_length": 6, "to_length": 6}], "position": {"node_id": "91185278"}, "rank": "2"}, {"edit": [{"from_length": 6, "to_length": 6}, {"sequence": "TAAT", "to_length": 4}, {"from_length": 26, "to_length": 26}], "position": {"node_id": "91185279"}, "rank": "3"}, {"edit": [{"from_length": 23, "to_length": 23}, {"from_length": 1, "sequence": "T", "to_length": 1}, {"from_length": 8, "to_length": 8}], "position": {"node_id": "91185280"}, "rank": "2"}, {"edit": [{"from_length": 2, "to_length": 2}, {"from_length": 1, "sequence": "T", "to_length": 1}], "position": {"node_id": "91185281"}, "rank": "3"}]}, "quality": "ISEiIiImJiYmJhAiJRAeECQlIyYQJBAlHSIlJBwlJCIfGR0lJiYfHCQlEBAQJCUPIhwiEBwkJiYmECIjJiYdEBwQECQlJhAkEBwlIyUlGSUQJSYQISUdIRAZJRkQIiUQEBAdDxkPIiUPHRkPDw8PHCUjDw8aJSEPDxwPHCUP", "sample_name": "HG00514_961a37c", "score": 105, "sequence": "ATATAATATAATTACATATTTTACTATGTTAATATATAATATAAAACATATGATTAATATGTAATTAATTATATTAATATATTAATATATTTATTATATTTTATATAACATTTATATTATATTATT"}
```

**Comment by jmonlong** [comment]
I was using the default gaffe, i.e not forcing gssw rescue, so I thin it's mean using dozeu.
When I ran the genotyping pipeline using gssw rescue, I didn't get an error so it might be happening because of dozeu?

The indexes are in `s3://vg-k8s/users/jmonlong/hsvlr_srdedup17_aug/indexes/`: 
hg38-hsvlr_srdedup17_aug.N16.gbwt
hg38-hsvlr_srdedup17_aug.dist
hg38-hsvlr_srdedup17_aug.k39.w15.N16.min
hg38-hsvlr_srdedup17_aug.snarls
hg38-hsvlr_srdedup17_aug.trivial.snarls
hg38-hsvlr_srdedup17_aug.xg

Let me know if I can help more.

**Comment by jltsiren** [comment]
Is this with version 1.24.0 or with the latest master? Dozeu rescue used to find alignments with a negative score, but I (hopefully) fixed it after the release.

**Comment by jeizenga** [comment]
There are code paths that would have this result, but I'm not totally sure how to interpret them:
https://github.com/vgteam/vg/blob/master/src/dozeu_interface.cpp#L334-L372

**Comment by jltsiren** [comment]
At the moment, Giraffe reverts to GSSW if dozeu finds an alignment with a negative score. I implemented the change after the release of 1.24.0.

**Comment by glennhickey** [comment]
@jmonlong Do you know which version you used?  It looks like if it's pre 1.24.0 I can close this issue.

**Comment by jmonlong** [comment]
Yes, so the GAM was produced with commit [961a37c](https://github.com/vgteam/vg/commit/961a37cfc7aee7494fbc979946cb3276472073ef) (22 days ago) and the GAF from [18a5600](https://github.com/vgteam/vg/commit/18a5600320e1df3841a51c34203770b3887f516e) (7 days ago)

The release 1.24.0 was from 24 days ago. @jltsiren do you remember when after 1.24.0 you implemented this. Would that help if I make a GAM with the more recent version?

@glennhickey the latest GAF issue was because of that, right? If so that would mean that the master 7 days ago was producing this kind of output.

**Comment by glennhickey** [comment]
Yeah, from what I checked, this issue is present in both the GAM and GAF.  So it would be there in https://github.com/vgteam/vg/commit/18a5600320e1df3841a51c34203770b3887f516e from 7 days ago. 

It was caught, like you say, by trying to read the GAF.  Until #2834, vg couldn't read these kinds of alignments without crashing.

**Comment by jltsiren** [comment]
Apparently the alignment qualifies as a single softclip and gets alignment score 0. Because the score is good enough, Giraffe does not revert to using GSSW.

How does GSSW deal with situations like this? If the behavior is reasonable, it should be enough to replace the condition `if (score >= 0)` in `MinimizerMapper::fix_dozeu_score()` with `if (score > 0)`.

**Comment by jeizenga** [comment]
Because vanilla GSSW allows soft-clips and isn't anchored, you never really see this. You can essentially always find a 1-base match to get a positive score -- or even a 1-base mismatch and the full length bonus. When we do pinned alignment in GSSW and the score is 0, GSSW ends its traceback without producing an alignment, but we infer the full insertion based on the pinning points and manually create it in the Aligner.

**Comment by jltsiren** [comment]
PR #2850 included the solution I proposed. It may be enough to resolve the situation.

**Comment by jltsiren** [comment]
I think this issue has been resolved. Feel free to reopen if you encounter something similar in the future.
