### ISSUE TITLE
warning - skipping duplicate variant

### ISSUE THREAD

**Issue by a00101** [vgteam/vg#2898]
Dear vg team.

I downloaded file from dbsnp, 00-common_all.vcf.gz and tbi index file
Then construct with code below.
`vg construct -t 70 -p -r Homo_sapiens.GRCh38.dna.primary_assembly.fa -v 00-common_all.vcf.gz > test.vg`
And got too many warnings.
```
warning:[vg::Constructor] Skipping duplicate variant with hash 2b7967a3cd675990d0fd206a08d6417b86efb07a at 2:141330002
warning:[vg::Constructor] Skipping duplicate variant with hash 7e3da9062d23664c3d231c93fce66dad34e551ca at 2:141330747
warning:[vg::Constructor] Skipping duplicate variant with hash 7e3da9062d23664c3d231c93fce66dad34e551ca at 2:141330747

```

need to trim vcf file?

Thanks.

**Comment by adamnovak** [comment]
The warnings are safe to ignore if you are confident in your input VCF.

But vg gets suspicious when it sees the same variant multiple times in the input VCF and warns you. If you're surprised that `00-common_all.vcf.gz` has duplicate variants, you may want to remove the duplicates with another tool before running vg on the file.

I'm going to close this as this is expected behavior. If your real problem is that the warnings are "too many" and you need it to stop after printing a few of them and suppress the rest, let us know and we can add some logic to do that.
