### ISSUE TITLE
Indexing step too long

### ISSUE THREAD

**Issue by AdrienOliva** [vgteam/vg#2959]
Hi, I am trying to create the 1000 Genome Project graph following your tutorial https://github.com/vgteam/vg/wiki/Working-with-a-whole-genome-variation-graph. I am using the vg-v1.25.0.simg image (using Singularity 2.5.2). 

I am running the GSCA indexing script using the command:  
```
vg index -g /home/WorkDir/WG.gcsa -b /home/WorkDir/tmp $(for i in $(seq 22; echo X; echo Y); do echo /home/WorkDir/$i.pruned.vg; done)
```
 I simulated the pruned.vg using the command in the same tutorial and everything works fine; no errors.

The tutorial says "This takes about 32 hours on a 32 core system." and I am actually running the GSCA indexing with 24 cores so I was expecting the job to take more time than that. However the indexing step is running for 9 days in a row without spitting out any errors. Is it a known behaviour on the new version of VG or something went wrong ? 

On the same tutorial while creating the XG index, my XG output is 15GB where in the tutorial you talk about 30GB file. Is there any change in the way VG works during those steps ? I had no errors messages during the xg indexing either.

Thanks

VG version from the image:
```
vg version
vg version v1.25.0 "Apice"
Compiled with g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0 on Linux
Linked against libstd++ 20191114
Built by root@7032b439058e
```

Thanks a lot !

**Comment by jltsiren** [comment]
How much memory do you have and how fast is the disk you use for temporary files? The minimum for 1000GP GCSA construction is 128 GB, and 192 GB should be somewhat faster due to disk cache. The total I/O volume for the construction should be ~15 TB, which would take about two days if the average throughput is 100 MB/s.

If you happened to run the construction with option `-p` / `--progress`, the log may contain hints on what is going on. You may also look into the temporary directory to see how many `gcsa_<hostname>_<pid>_<counter>` files there are and what is the current range of counter values. If I remember correctly, files 0-47 should be from preprocessing, 48-143 from the first step of prefix-doubling, 144-239 from the second step, 240-335 from the third step, 336-431 from the fourth step, and 432-435 from the final merging.

15 GB for the XG index is normal. Older XG versions required 30 GB. I have updated the tutorial.

**Comment by AdrienOliva** [comment]
Indeed I didn't use the ```-p``` option so I check in the tmp folder and I only had 25 files of kmers that was created 8 days ago but nothing else. So it did run correctly but stopped for some reason. I have re-submitted the job using the ```-p``` option and with 192GB instead of 128GB of memory and I will let you know what the logs say. 
Thanks !

**Comment by AdrienOliva** [comment]
I have been running it and watching closely to the temporary files. After 37h of running , and apparently in the fourth step, nothing were happening for about 24h (see the log below). But after 5 days my GSCA index is complete now. I run it on a different cluster so might be an issue on our hand. I will let you know if I have any news. 
Thanks a lot !


```
GCSA::GCSA(): Step 4 (path length 128 -> 256)
PathGraph::prune(): 12840554404 -> 11908704523 paths (11014055990 ranges)
PathGraph::prune(): 10833780924 unique, 65558386 redundant, 781022733 unsorted, 228342480 nondeterministic paths
PathGraph::prune(): 445.293 GB in 24 file(s)
PathGraph::read(): File 0: Read 941780806 order-128 paths
PathGraph::extend(): File 0: Created 1025265535 order-256 paths
PathGraph::read(): File 0: Read 1025265535 order-256 paths
PathGraphBuilder::sort(): File 0: Sorted 1025265535 paths
PathGraph::read(): File 1: Read 953001856 order-128 paths
PathGraph::extend(): File 1: Created 1045117588 order-256 paths
PathGraph::read(): File 1: Read 1045117588 order-256 paths
PathGraphBuilder::sort(): File 1: Sorted 1045117588 paths
PathGraph::read(): File 2: Read 783112825 order-128 paths
PathGraph::extend(): File 2: Created 860090094 order-256 paths
PathGraph::read(): File 2: Read 860090094 order-256 paths
PathGraphBuilder::sort(): File 2: Sorted 860090094 paths
PathGraph::read(): File 3: Read 768580558 order-128 paths
PathGraph::extend(): File 3: Created 853322041 order-256 paths
```
