### ISSUE TITLE
Giraffe paired-end regression

### ISSUE THREAD

**Issue by xchang1** [vgteam/vg#3001]
Giraffe performance on paired-end reads regressed between 43e408c (Sept 17) and 1ee0c8f1 (Sept 20). Single end performance is unchanged

On the 1kg graph, full gbwt, novaseq6000 reads on 43e408c, giraffe gets 1968202 reads correct single end and 1983815 correct paired end
On the same graph and reads on 1ee0c8f1, giraffe gets 1968202 reads correct single end and 1961336 correct paired end.

This plot was run with 1ee0c8f1 with a 1kg graph, novaseq6000 reads, and sampled gbwts with different coverage
![plot-roc](https://user-images.githubusercontent.com/34357324/94189724-fbea3580-fe5f-11ea-8542-50d314db99f5.png)

**Comment by adamnovak** [comment]
I grabbed all the files:
```
aws s3 cp s3://vg-k8s/profiling/graphs/v2/for-NA19239/1kg/hs37d5/1kg_hs37d5_filter.xg trash/graph.xg
aws s3 cp s3://vg-k8s/profiling/graphs/v2/for-NA19239/1kg/hs37d5/1kg_hs37d5_filter.dist trash/graph.dist
aws s3 cp s3://vg-k8s/profiling/graphs/v2/for-NA19239/1kg/hs37d5/1kg_hs37d5_filter.full.gbwt trash/graph.gbwt
aws s3 cp s3://vg-k8s/profiling/graphs/v2/for-NA19239/1kg/hs37d5/1kg_hs37d5_filter.full.gg trash/graph.gg
aws s3 cp s3://vg-k8s/profiling/graphs/v2/for-NA19239/1kg/hs37d5/1kg_hs37d5_filter.full.min trash/graph.min
aws s3 cp s3://vg-k8s/profiling/reads/sim/for-NA19239/1kg/hs37d5/novaseq6000/out_sim/sim.filt1M.gam trash/sim.gam
```

I did a bisect with this script:
```
#!/usr/bin/env bash
set -ex
date
git submodule update --init --recursive
make -j32 || exit 125
date
vg giraffe trash/graph.fa -p -G trash/sim.gam -i >trash/out.gam || exit 125
vg annotate -a trash/out.gam -m -x trash/graph.xg >trash/out2.gam || exit 125
vg gamcompare -r100 trash/out2.gam trash/sim.gam >/dev/null 2>comparison.txt || exit 125
cat comparison.txt || echo 125
date
if [ "$(cat comparison.txt  | tr -d 'a-z')" -lt "1983815" ] ; then
    exit 1
else
    exit 0
fi
```

And these commands:
```
git bisect start
git bisect good 43e408c
git bisect bad 1ee0c8f
git bisect run ./bisect-script.sh
```

It implicated a couple commits from @jeizenga that don't quite build on their own:

>There are only 'skip'ped commits left to test.
>The first bad commit could be any of:
>da55574f5c464c613f4ce2f78eb404fb5be305ff
>55f9a7c6618626f481c2afa9b0405581bd4782b5
>We cannot bisect more!
>bisect run cannot continue any more

I think this is the problem:
https://github.com/vgteam/vg/commit/55f9a7c6618626f481c2afa9b0405581bd4782b5#diff-ef1120180564077e36e2de0321bb3dfaR806

Scoring was changed to subtract out the mismatch score as computed by the mismatch scoring function, but that function (secretly, because it has no doc comment) already computes a negative score for mismatches, so we're actually *awarding* points when there's a mismatch.
