### ISSUE TITLE
vg snarls output bizarre for toy example

### ISSUE THREAD

**Issue by glennhickey** [vgteam/vg#3011]
When I add an edge from node `6` to node `15` in the tiny graph, I expect the `9,12` snarl to be a child of `6,15`

![tiny-nest](https://user-images.githubusercontent.com/901102/94454705-30bbfc80-0180-11eb-9826-f3297a885518.png)

That's not what I'm seeing.  Instead I get the `9,12` snarl listed twice, and it is the parent of `1,6` and `6,15` never shows up:
```
vg construct -r tiny/tiny.fa -v tiny/tiny.vcf.gz | vg view - > tiny-nest.gfa
printf "L\t6\t+\t15\t+\t0M\n" >> tiny-nest.gfa
vg view -Fv tiny-nest.gfa | vg snarls - | vg view -R -
{"directed_acyclic_net_graph": true, "end": {"backward": true, "node_id": "12"}, "start": {"backward": true, "node_id": "9"}}
{"directed_acyclic_net_graph": true, "end": {"node_id": "6"}, "parent": {"end": {"backward": true, "node_id": "12"}, "start": {"backward": true, "node_id": "9"}}, "start": {"node_id": "1"}, "start_end_reachable": true, "type": 1}
{"directed_acyclic_net_graph": true, "end": {"backward": true, "node_id": "9"}, "start": {"backward": true, "node_id": "12"}, "start_end_reachable": true, "type": 1}
```

@adamnovak Using the old algorithm gives the expected output
```
vg view -Fv tiny-nest.gfa | vg snarls - -A cactus | vg view -R -
{"directed_acyclic_net_graph": true, "end": {"node_id": "6"}, "start": {"node_id": "1"}, "start_end_reachable": true, "type": 1}
{"directed_acyclic_net_graph": true, "end": {"node_id": "15"}, "start": {"node_id": "6"}, "start_end_reachable": true, "type": 1}
{"directed_acyclic_net_graph": true, "end": {"node_id": "12"}, "parent": {"end": {"node_id": "15"}, "start": {"node_id": "6"}}, "start": {"node_id": "9"}, "start_end_reachable": true, "type": 1}
```

**Comment by adamnovak** [comment]
The new algorithm uses a rooting algorithm that can get a little weird in small test graphs that don't have long, obvious telomeres. I think when you add that edge it collapses the Cactus graph enough that it decides to root on what looks like a cycle, which it cuts at 9 and 12. So you have (12 rev, 9 rev) as a snarl, which is equivalent to (9 fwd, 12 fwd), which is the actual SNP, and then you have (9 rev, 12 rev), which is equivalent to (12 fwd, 9 fwd), which is everything outside the SNP, and those two are your top-level chain.

This causes more trouble in test graphs than in real graphs, because in test graphs we get bored of adding linear context on either side of what we care about. But if you make the total length of the fixed sequence on the bridge path from end to end longer than the length of the Cactus petal cycle it is finding, then the rooting will go back to "normal".

**Comment by glennhickey** [comment]
Got it.  I guess I missed that the 1st 9/12 snarl was inside out.  Thanks!
