### ISSUE TITLE
Using Nanopore or Pacbio data to construct augmented reference graphs

### ISSUE THREAD

**Issue by fantasticair** [vgteam/vg#3045]
Hello,
I have a request for using Nanopore or Pacbio data to construct augmented reference graphs, I know your software using the NGS data to call SNP, then using the vcf file top construct augmented reference graphs, but the TGS date has a huge advantage to solve the complex region and continuity, your software could add this function, and can you tell me similar function software?

Best,
fantasticair

**Comment by ekg** [comment]
Look at the pangenome graph builder: https://github.com/pangenome/pggb

If you have high-quality (corrected ONT or HiFi) reads, and your graph
isn't huge, you can possibly run this process on the raw data.

Otherwise, you could make an assembly, then combine your contigs and any
references you're using with an adaptation (not all-vs-all) of the pggb
pipeline.

**Comment by fantasticair** [comment]
Thanks for your advice.
