### ISSUE TITLE
Feature Request: Accept minigraph-format GFAs

### ISSUE THREAD

**Issue by fantasticair** [vgteam/vg#3129]
Hello vgteam numbers,
        Now many people need to build a pangenome graph, we can choose the `pggb` pipeline, but this pipeline depends on so many things,  it's not friendly for users.  We know `minigraph` is a very excellent software to build pangenome graph, but  the output file of this software is a standard `GFA` format,  however, the `vg` software needs an unconventional format, maybe it's really needed,  unfortunately, it takes trouble for users, so we request your team can provide a concise and convenient program or module in `vg` to convert this format. Thank you for your contribution to the graphical genome!

Best wishes~

**Comment by cistarsa** [comment]
Indeed, I'm one of these people (commenting to get updates)

**Comment by ekg** [comment]
vg uses a restricted GFA. It has two "unconventional" aspects. 1) there are no overlaps on edges, 2) we only use integers for node names.

minigraph makes rGFA. This is also unconventional, but in different ways. It has no overlaps on edges. It does not use P lines to describe sequence relationships inside the graph.

If you would like to convert to a format usable by vg, you only need to switch the node names to be integers instead of strings. I would suggest using gfautil to do this, it's in https://github.com/chfi/rs-gfa-utils and https://crates.io/crates/gfautil, installable via `cargo install gfautil`:

```
-> % gfautil id-convert -h                                                                                                                                 
gfautil-id-convert 0.3.2
Convert a GFA with string names to one with integer names, and back

USAGE:
    gfautil -i <input GFA file> id-convert [FLAGS] --namemap <path to name map>

FLAGS:
        --hash       
        --to-int     
    -h, --help       Prints help information
    -V, --version    Prints version information

OPTIONS:
        --namemap <path to name map>    Path to a name map that was previously generated for the given GFA. Required if
                                        transforming to the original segment names. If not provided, a new map is
                                        generated and saved to disk
```

Responding here (as well as on the minigraph issue) to provide a record to other interested groups.

Maybe similar functionality for node id mapping should be put into vg.

**Comment by glennhickey** [comment]
`Maybe similar functionality for node id mapping should be put into vg.`

Yes!  We're definitely going to add input support for GFA with non-numeric ids as well as rGFA tags to vg very soon.

**Comment by cistarsa** [comment]
@fantasticair I had the same concern using minigraph output (rGFA) in vg...I kinda did a worst practice by sed'ing the segment column as ```bash-4.2$ sed -i1 s/s//g' minigraph.gfa``` (this also removes any s's you have in your headers, e.g "scaffold", so I had to add those back). 

then, constructed a graph via vg 
 ```bash-4.2$ ./vg convert -g -a minigraph.gfa > graph.vg2```
 & index with ```bash-4.2$ ./vg index graph.vg2 -x graph_vg2.xg```

...obviously this method is nuclear and I can't in good conscious condone someone doing this on their data etc etc.

**Comment by glennhickey** [comment]
vg can now accept GFAs from minigraph (via #3160)

**Comment by cistarsa** [comment]
ah! that's a relief...I have since gone the edyeet -> seqwish -> smoothxg route (for now). But comparing these graphs might be useful. 

I may need to start another comment. But I'd like to confirm that chunking the vg, from ```vg convert smoothxg.gfa smoothxg.vg```  by scaffold and then generating indexes doesn't require me to join id's if I just run each scaffold.vg independently, correct?
