### ISSUE TITLE
FATAL: kernel too old Aborted

### ISSUE THREAD

**Issue by lqsae** [vgteam/vg#3167]
**1. What were you trying to do?**

$/TJPROJ4/CCX/Users/liuqingshan/miniconda3/bin/vg -h
FATAL: kernel too old
Aborted

**2. What did you want to happen?**

**3. What actually happened?**

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

```
Place stacktrace here.
```

**5. What data and command can the vg dev team use to make the problem happen?**

**6. What does running `vg version` say?**

```
Place vg version output here
```

**Comment by adamnovak** [comment]
Hello @lqsae; sorry you are having trouble running vg.

That error happens when your Linux version is too old to run vg. The vg versions we distribute usually need something like Linux 3.2 or newer. We can't build for Linuxes older than that on the Linux versions we use.

What does `uname -a` give you when you run it? And what does `file /TJPROJ4/CCX/Users/liuqingshan/miniconda3/bin/vg` give you? I get:

```
Linux octagon 5.4.0-64-generic #72-Ubuntu SMP Fri Jan 15 10:27:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

And

```
bin/vg: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, BuildID[sha1]=90bd073e6a3d5b4c1ce2e01d28f811f41995d99f, for GNU/Linux 3.2.0, not stripped
```

The `file` output says I have an executable "for GNU/Linux 3.2.0", and my Linux version is newer than that ("5.4.0"), so it runs.

If you have an older Linux, you won't be able to run the binaries we have for download, but you may be able to [build vg from source](https://github.com/vgteam/vg#building-on-linux).

**Comment by lqsae** [comment]
ok ,thank you ,i try it

**Comment by jeizenga** [comment]
It seems like this issue may have been resolved. I'm going to close it, but let me know if you still have questions.

**Comment by lqsae** [comment]
yes ,thank you
