### ISSUE TITLE
Graph pruning/simplification should be able to leave a path

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#318]
Right now, when we prune complex regions of graphs with `vg mod` prior to GCSA2 indexing, all the nodes in the region get chopped out of the graph. This means some regions of the graph are completely unrepresented in the index, which can be very confusing for the paired-end consistency enforcement. If one read of a pair is supposed to map in that region, but produces no alignments (because the region was pruned from the index), the read pair can instead be pulled over to some other region where both ends have mappings, even if that region is a substantially worse fit.

If we left at least one path in the index for that region, this problem might be less severe.

**Comment by ekg** [comment]
It turns out that this is very easy to do. We just change the script that generates our index files.

First, we do as we've done and strip out regions of high complexity using the path bifurcation metric.

```
# build the graph
vg construct -r small/x.fa -v small/x.vcf.gz >x.vg

# make the pruned graph kmers
vg mod -pl 16 -e 2 x.vg | vg mod -S -l 32 - \
    | vg kmers -gB -k 16 -H 1000000000 -T 1000000001 >x.graph

# make the reference haplotype's kmers
vg mod -r x x.vg \
    | vg kmers -gB -k 16 -H 1000000000 -T 1000000001 - | pv -c >>x.graph

# now index
vg index -i x.graph -x x.xg x.vg

# and map
vg map -r <(vg sim -l 100 -e 0.1 -n 10000 -x x.xg ) \
    -g x.gcsa -x x.xg -J | pv -l >/dev/null
```

This works because GCSA2 is unaffected by duplicated kmers in its input.

We may want to script this out in certain functions in the command line API, but I think this is basically a non-problem.

We could also build a graph where we keep only some subset of representative haplotypes. These could be synthetic paths used to represent larger structures in the genome, such as big indels. I don't know a good way to construct those but I have some ideas. Basically we'd want to "de-noise" the graph by collapsing all superbubbles below a certain length. The same approach works for this graph--- we generate the kmers from it and just add them as input to GCSA2.

Any suggestions about interface to make this more ergonomic? I think I'll add a flag to do this to the indexer. It's a bit awkward though because we'll need to copy the graph and it's heavy enough to be a problem if someone tries to do a whole chromosome.

**Comment by adamnovak** [comment]
I think if this does turn out to be better, we definitely should make the workflow more natural.

I'll put this into my bake-off pipeline and see if it improves things there.

**Comment by adamnovak** [comment]
One thing we might be forgetting is that the primary path can visit nodes twice, in some graphs. So if the primary path merges with itself and creates an overly-complex region, this approach can still make too many kmers (although hopefully much more rarely). The example-haplotypes approach for complex regions that we're looking at long-term should fix that.

**Comment by adamnovak** [comment]
It looks like there might be a missing `-N` option in the `vg mod -r` step. Otherwise, material not in a path is not removed from the graph, and you just end up making all the kmers for the unpruned graph after the kmers for the pruned graph.

**Comment by adamnovak** [comment]
We now have the prune-and-combine workflow scripted out in toil-vg. I'm not sure it's so important to add it in to vg itself.
