### ISSUE TITLE
Ungzipped Protobuf vg output

### ISSUE THREAD

**Issue by cartoonist** [vgteam/vg#3192]
**1. What were you trying to do?**
I am trying to convert a "vg" graph constructed by `vg construct` to Protobuf format which is apparently serialised as a `HashGraph`. I am using `vg==1.27.0` (conda installed).

**2. What did you want to happen?**
To get a vg file in Protobuf format.

**3. What actually happened?**
I get an __ungzipped__ vg file while vg files were usually gzipped. Is it intentional or a bug?

**4. What data and command can the vg dev team use to make the problem happen?**
```bash
vg construct -r tiny.fa -v tiny.vcf.gz > tiny.vg
vg ids -j tiny.vg  # or any command that converts the vg file silently from Protobuf to HashGraph...
vg convert -v tiny.vg > tiny.vg.vg  # the resulting file is not gzipped...
hexdump -C -n 10 tiny.vg.vg  # ...as this clearly shows the "VG" header in the file
```

By the way, I found this silent conversion quite confusing as the files still bear the same file extension ".vg" but contains completely different file formats.

**Comment by jeizenga** [comment]
Sorry about the confusion. We're in a long-term process of completely moving away from the Protobuf-based serialization, which has proven to be rather inefficient. Before beginning the move away from Protobuf, we also stopped gzipping output, as gzip was becoming a bottleneck in IO operations. So, in short, yes this is intentional.

The process has been a bit piece-meal since VG is such a large code-base, hence the silent conversions. In general, I would strongly recommend GFA as an interchange format between different tools. You can make a GFA from of any serialized graph format in VG with `vg view graph.vg > graph.gfa`.

I'm going to close this issue, but please let me know if you have further questions.
