### ISSUE TITLE
Size limit exceeded when building index for graph

### ISSUE THREAD

**Issue by xiaoluo91** [vgteam/vg#3251]
Hi, I am using `vg index ` for indexing variation graph(constructed from 17 contigs, which are from 3 Ecoli). The variation graph is constructed by PGGB, then using `vg view --gfa-in $gfa --vg --threads 24 |vg mod -X 32 -|vg ids -c - >contig_graph.norm.vg` for graph normalization, then perform graph indexing.

Here is the code for indexing:
`export TMPDIR=tmp && vg index -x contig_graph.norm.xg -g contig_graph.norm.gcsa -k 11 -X 2 -Z 500 -t 48 contig_graph.norm.vg`

However, it failed to indexing because out of size limit. Here is the error infor:

PathGraphBuilder::write(): Size limit exceeded, construction aborted
Building index for graph

I am wondering if there is a way to solve this problem or not, because I only have 500Gb free disk space. Here, I just use a small dataset for test (i.e, 17 contigs from Ecoli), but it already takes so many spaces, which looks a bit strange (maybe I used inappropriate parameters ?). Any help would be greatly appreciated.

**Comment by jeizenga** [comment]
Did you do any pruning before GCSA2 indexing? We recommend that before indexing a complex graph, since otherwise the size of the GCSA2 can be exponentially large. The process is described in this wiki entry:
https://github.com/vgteam/vg/wiki/Index-Construction#complex-graph

Another option we've developed recently is `vg autoindex --workflow map`, which will implement our best-practice pipeline starting from common interchange formats like GFA.

**Comment by xiaoluo91** [comment]
It works now, many thanks.

**Comment by xiaoluo91** [comment]
Hi, it works now. Thanks for help!

Best regards,
