### ISSUE TITLE
Remove CMakeCache when raptor build fails

### ISSUE THREAD

**Issue by edawson** [vgteam/vg#326]
When building raptor, CMake creates a CMakeCache.txt file in the `deps/raptor/build` directory. If any version of Bison is on the path this location will be cached.

The build will then fail if this version of Bison is too old, and installing a new Bison and updating the path won't help because the old location is cached.

The solution is to make sure the CMakeCache.txt is removed by a make clean. I'll fix this and make a PR.

**Comment by adamnovak** [comment]
This is exactly what broke in #332. I added bison to the list of macports dependencies, so people installing from scratch on macports ought to find the new bison, but in general this needs to be fixed.

Is this maybe raptor's bug? If a build fails because it found something it didn't like, that result shouldn't be cached. How does raptor do its version checks?

**Comment by edawson** [comment]
It looks like this was a mistake I introduced in the Makefile actually; the raptor directory Makefile has no clean target, so the `make clean` from the main vg directory failed. The next line after the failure manually deleted the CMakeCache.txt.

I've fixed this on my branch and will merge up today/tomorrow. Hopefully I've fixed more bugs than I've created this time.

**Comment by edawson** [comment]
Resolved by #346
