### ISSUE TITLE
Giraffe for genotyping is too slow

### ISSUE THREAD

**Issue by shokrof** [vgteam/vg#3500]
I am trying to use giraffe to genotype structural variants of one chromosome from a mamilian genome. I am following this tutorial.
https://github.com/vgteam/vg/wiki/SV-genotyping-with-vg and the commands from this Snakefile https://github.com/vgteam/vg_snakemake/blob/master/Snakefile

I didn't use the autoindex command because I wanted to make sure that -a option is included for vg construct.

the commands I used for the constructions
```
vg construct -r {reference.fa} -v {vcf for SV} -a -f -S -t16 -p -C -R {Chromsome number}
vg index -L -t {threads} -x {output} {input.vg}
vg gbwt -n {wildcards.n} -g {output.gg} -o {output.gbwt} -x {input} -P
vg minimizer -k {wildcards.k} -w {wildcards.w} -t {threads} -i {output} -g {input.gbwt} {input.xg} 
vg snarls -t {threads} --include-trivial {input} > {output.trivial}
vg index -t {threads} -j {output} -x {input.xg} -s {input.trivial.snarls} 

```

alignment

```
 vg giraffe -p -t 16 -m  -d {dist} --gbwt-name  -x {input.xg} -N {sample name} -f {pair1} -f {pair2} > {output.gam}
```

My issue is that the giraffe step is very low. it maps 70 reads per thread per second. it took 1 day and 20 hours to map 30G bp using 32 threads. Am I doing something wrong with my commands? how can I optimize the execution speed? 

Thanks,
Moustafa

**Comment by jltsiren** [comment]
Let's see this line-by-line. The snakefile you followed was old, and many things have changed since then.

### Graph construction

```
vg construct -r {reference.fa} -v {vcf for SV} -a -f -S -t16 -p -C -R {Chromsome number}
```

Here you build a graph for a single chromosome. Is that what you intended?

### XG construction

```
vg index -L -t {threads} -x {output} {input.vg}
```

This seems ok.

### GBWT construction

```
vg gbwt -n {wildcards.n} -g {output.gg} -o {output.gbwt} -x {input} -P
```

This builds a GBWT containing artificially generated haplotypes. If the graph contains too many cycles or complex structures, the generated haplotypes may not cover it particularly well, which could lead to all kinds of mapping problems. Which value of `-n` are you using?

### Minimizer index construction

```
vg minimizer -k {wildcards.k} -w {wildcards.w} -t {threads} -i {output} -g {input.gbwt} {input.xg} 
```

This line is too early. You want to use option `-d {distance index}` to cache the snarl tree positions for the seeds. Caching the positions improves mapping speed significantly.

The startup time for this step is a bit faster if you use the GBWTGraph (`.gg`) instead of the XG graph.

### Snarl finding

```
vg snarls -t {threads} --include-trivial {input} > {output.trivial}
```

This seems ok.

### Distance index construction

```
vg index -t {threads} -j {output} -x {input.xg} -s {input.trivial.snarls} 
```

This seems ok.

### Read mapping

```
vg giraffe -p -t 16 -m  -d {dist} --gbwt-name  -x {input.xg} -N {sample name} -f {pair1} -f {pair2} > {output.gam}
```

Are the reads only from the same chromosome you specified in the graph construction step, or are they from the whole genome? Mapping can be slow if most reads are not supposed to map to the reference.

You have omitted the names of the minimizer index and the GBWT index from this example, but I assume that you included them in the actual command. Also, as in minimizer index construction, the startup time is a bit faster if you use a GBWTGraph instead of an XG graph.

**Comment by shokrof** [comment]
Thanks for the very fast and detailed response.

"Here you build a graph for a single chromosome. Is that what you intended?"
I am testing the pipeline for one chromosome for now. but I intended to index the whole genome.


"Which value of -n are you using?"
I am using n = 16 like the old snakemake scripts 

"If the graph contains too many cycles or complex structures, the generated haplotypes may not cover it particularly well" I was concerned about this as well because I am using structural variants. Do you have other recommendations?

" You want to use option -d {distance index} to cache the snarl tree positions for the seeds. Caching the positions improves mapping speed significantly" I am building the distance index in another step. arent they the same?

"Are the reads only from the same chromosome you specified in the graph construction step, or are they from the whole genome? Mapping can be slow if most reads are not supposed to map to the reference."
I am using the whole set of the reads. could this be the problem? Can I build the index for the whole chromosome or do I need to do it in batches and merge the results?

**Comment by jltsiren** [comment]
In the ideal case, there is either one mapping that is clearly better than any alternative and the read aligns there (almost) perfectly, or there are no seed hits at all in the reference. Reads like that can be mapped very quickly. Then there are difficult reads that either have many promising mappings or don't align particularly well anywhere. Mapping those reads can take orders of magnitude more time than in the ideal case. If you are mapping reads from the entire genome to a single chromosome, many reads that should map to somewhere else may have lower-quality alignments to that chromosome, which slows the mapper down.

16 artificial haplotypes should be enough for an SV graph if the graph is acyclic. Even then, there may be some regions that are not fully covered because they are too complex. Increasing the number of haplotypes to 64 may help a bit. If there are cycles or reversals, the greedy algorithm may leave large parts of the graph uncovered. For such graphs, you either need real haplotypes or a better algorithm for generating artificial ones.

The right order for building graphs and indexes is this:

1. Build the original graph.
2. (Convert the original graph into XG graph. This step is optional, because you can use the original graph instead of the XG graph in every command. The XG graph is just faster to use and requires less memory.)
3. Build the GBWT and the GBWTGraph from the (original / XG) graph.
4. Find the snarls and build the distance index from the (original / XG) graph.
5. Build the minimizer index from the GBWT, the GBWTGraph, and the distance index. If you don't use the distance index, Giraffe will be slower.

Giraffe requires the GBWT, the GBWTGraph, the distance index, and the minimizer index. The (original / XG) graph is unnecessary for GAM output.

**Comment by shokrof** [comment]
As you described, I indexed the whole genome and I used distance index while creating the minimizes and it giraffe now is much faster mapping >1500 reads per second per thread which is impressive. 

I have more question
you mentioned ". If there are cycles or reversals, the greedy algorithm may leave large parts of the graph uncovered".  I   am trying to genotype structure variants using short reads. How the uncovering issue will effect the genotype? will I have some false negative(giraffe wont be able to map reads to the SV and it will be genotyped as negative(0/0))?


Thanks again, Your comments were very helpful.

**Comment by jltsiren** [comment]
In serious cases, if the graph is too complex for the greedy algorithm, you may see fewer reads mapping overall than what you would reasonably expect. If you then project ("surject" in VG language) the mappings back to the linear reference, there may be regions of the reference with no coverage at all.

In less serious cases, the same may happen at the level of individual alleles. If no path manages to find its way through an allele, Giraffe does not see it at all. You may then see variants genotyped as 0/0 or 1/1 when the truth is something else, or they may be completely missing if the other alleles are too different.
