### ISSUE TITLE
remove PCR duplicates after short read mapping

### ISSUE THREAD

**Issue by biozzq** [vgteam/vg#3552]
Hi,

`vg`, a tool I really want to try out for discovering and genotyping genetic variation.  We typically remove PCR duplicates before detecting variants. From your published paper (https://doi.org/10.1126/science.abg8871), I found that I have two options:

1. first map the short reads to the reference genome using BWA and remove the duplicates using picard, then remap the de-duplicated reads to the graph genome.
2. first map the short reads to the graph genome using Giraffe Mapper and transform the alignments to be relative to reference genome path (backbone) and ouput the BAM file, then remove the duplicates and convert to fastq using picard. Finally, remap the de-duplicated reads to the graph genome.

I wonder which option will be optimal? Thank you in advance.

Also, would it be possible to add this feature in vg command.

sincerely

Zheng zhuqing

**Comment by adamnovak** [comment]
Hello, @biozzq!

This would be a useful tool for the vg toolkit, but I'm not sure we're planning to write it any time soon. We mostly work on PCR-free reads in our testing and haven't needed it.

If you get your graph mappings out in GAF format, you might be able to use a third party duplicate marking tool that operates on GAF, but I don't know if any exist.

As for which of the paths would be more efficient, it might depend on the graph; Giraffe can be faster than BWA on simple graphs but slower on more complex ones. I might actually try using `minimap2`, or whatever aligner can be found that is maximally fast and minimally accurate, since I think duplicate-marking only needs the same sequence to map to the same place each time, and doesn't care whether it's actually the right place.

Does that help?

**Comment by biozzq** [comment]
Dear @adamnovak 

Thank you, this helps me a lot. I can not find any duplicate marking tool that can operate on GAF file. Thus, I will first align to the reference genome using the fastest tool, such as `sention`.

Best,
Zheng zhuqing

**Comment by adamnovak** [comment]
Sounds good! I'm going to close this, since I think we answered the question.

**Comment by JD12138** [comment]
> Hi,
> 
> `vg`, a tool I really want to try out for discovering and genotyping genetic variation. We typically remove PCR duplicates before detecting variants. From your published paper (https://doi.org/10.1126/science.abg8871), I found that I have two options:
> 
> 1. first map the short reads to the reference genome using BWA and remove the duplicates using picard, then remap the de-duplicated reads to the graph genome.
> 2. first map the short reads to the graph genome using Giraffe Mapper and transform the alignments to be relative to reference genome path (backbone) and ouput the BAM file, then remove the duplicates and convert to fastq using picard. Finally, remap the de-duplicated reads to the graph genome.
> 
> I wonder which option will be optimal? Thank you in advance.
> 
> Also, would it be possible to add this feature in vg command.
> 
> sincerely
> 
> Zheng zhuqing

Hello, I want to know how to get the de-dump reads from the marked bam file? I mean , use the reads ID in the bam file ? Is sounds very slow.

Thanks !
