### ISSUE TITLE
display reference with samples paths 

### ISSUE THREAD

**Issue by Chaima-Bouchenak** [vgteam/vg#3599]
**1. What were you trying to do?**
Construct a .vg file from .fa reference and unphased .vcf file of 10 samples
```
vg construct -r ref.fa -v alts.vcf -t 2 > graph.vg
```

**2. What did you want to happen?**
List paths, I expected to have 11 in total

**3. What actually happened?**
vg stats shows only 1 path (the reference one)

**5. What data and command can the vg dev team use to make the problem happen?**
Data and the generated .vg file are attached below

**6. What does running `vg version` say?**

```
vg version v1.38.0 "Canossa"
```
Any help please ? adding -a argument the construct command showed a very long list of paths

Thanks

visualisation :
![10lines](https://user-images.githubusercontent.com/77233864/157425669-773cfcf6-89e6-4d8f-a5be-18887a0b0e1b.png)

**Comment by Chaima-Bouchenak** [comment]
Thank you @adamnovak for the clarifications.

I did use the ``vg index`` to get the haplotypes paths from GBWT index as desired, 2 paths for each sample, after adding the ``--discard-overlaps --force-phasing`` as my VCF is unphased heterozygous.
What I actually want is to **set the link between the *__alt__paths\** that were generated with the ``-a`` argument** and **the haplotypes information.** is it possible? not necessarily to convert the two, but identify which alt_path occur in which sample/haplotype ? if not, maybe a way to construct each sample separately; save related alt_paths; so one, then concatenate everything.

@glennhickey  your feedback on that point would be very appreciated as i'm also using VG to get the GFA file and use it in ODGI ( no haplo info in this case)

**Comment by glennhickey** [comment]
1) If your vcf is **unphased** the two paths you get for each sample will both be random combinations of the haplotypes.  I don't think there's a meaningful biological use for such data.  

2) If you really want to get paths out of the GBWT and into the graph (**only recommended if you started with a phased vcf**), you can do something like this (assumed to be run tin [vg/test](https://github.com/vgteam/vg/tree/master/test))
```
vg construct -v tiny/tiny.vcf.gz -r tiny/tiny.fa -a > tiny.vg
vg index tiny.vg -v tiny/tiny.vcf.gz -G tiny.gbwt
vg paths -x tiny.vg -g tiny.gbwt -A | sed 's/_thread_//g' > threads.gaf
vg paths -d -Q _alt_ -v tiny.vg | vg augment -BF - threads.gaf > tiny_hap.vg
```
Now the two paths for sample "1" from tiny.vcf.gz are added to the reference path "x"
```
vg paths -Lv tiny_hap.vg
1_x_0_0
x
1_x_1_0
```
If you had more samples, you'd get a path like this for each sample.

3) We're working on making this process a little more intuitive (going back and forth between haplotypes and paths), but the user will need to keep in mind that non-GBWT formats won't scale to 1000's of paths in this way (whereas the GBWT will).

**Comment by adamnovak** [comment]
> What I actually want is to **set the link between the ___alt__paths*_ that were generated with the `-a` argument** in the .vg file and **the haplotypes information** of the .gbwt one, is it possible?

The `_alt` paths have names composed from a variant name and then an allele number (with 0 for the reference allele), following the numbering in the VCF.

The variant name is a hash [as created here](https://github.com/vgteam/vg/blob/9db930296f4a4454429a3be73cef1ff108b49620/src/utility.cpp#L489-L490), based on components of the variant's record in the VCF. We do this so that we can find the variant again reliably when composing haplotypes to compress into the GBWT, but still avoid cramming an entire VCF record into a path name.

You could come up with your own code to mimic this hash operation and find the paths corresponding to the right variants for a person's genotypes, given a VCF. And then to thread them together, to the extent that what the VCF describes is actually self-consistent. But it's probably easier to do what Glenn is describing, and let vg compose the haplotypes for you and then smuggle them out and maker them full-fledged named paths. We already have code to re-find the variants and string them together with tolerance for self-inconsistent VCF calls.

**Comment by Chaima-Bouchenak** [comment]
@glennhickey  @adamnovak 

worked perfectly, 
thank's for the great support and useful information that I'll surely consider in the next operations! 

![gene_vg](https://user-images.githubusercontent.com/77233864/161018247-0dab0b96-52e2-4a32-bb05-4ccd24574cd8.PNG)
