### ISSUE TITLE
convert .vg index to the giraffe index

### ISSUE THREAD

**Issue by MinngLi** [vgteam/vg#3617]
Hi all,

I am running the [Cactus Pangenome Pipeline](https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/doc/pangenome.md) + [vg girafffe](https://github.com/vgteam/vg/wiki/Mapping-short-reads-with-Giraffe) and [vg call](https://github.com/vgteam/vg/wiki/Whole-genome-calling-and-genotyping) pipeline.

The commands of Cactus Pangenome Pipeline I used are [here](https://github.com/ComparativeGenomicsToolkit/cactus/issues/698).

All commands have no error output, but I got the empty vcf files.

When I checked all the files. I found there is no P line (just S and L line) in the combined.xg index file which create by the Cactus Pangenome Pipeline. I'm wondering if this is the reason why I got the empty vcf files.

I also run the Cactus Pangenome Pipeline using the whole genome as input. 
```
cactus-graphmap ./jobstore seqfile combined.gfa combined.paf --outputFasta combined.gfa.fa --reference ref --realTimeLogging --binariesMode local
cactus-align ./jobstore seqfile combined.paf combined.hal --pangenome --pafInput --realTimeLogging --outVG --reference ref --binariesMode local --maxCores 16 --maxMemory 120G
```
And I successfully got the combined.hal and combined.vg file. When I check the combined.vg file, there are P lines inside. So I am wondering if I can use this combined.vg file as the index for downstream analysis. But I am also not sure how to convert the combined.vg index to the giraffe index. Does anyone have ideas on this?

Best,
Ming

**Comment by glennhickey** [comment]
Sorry about this -- there's a naming convention required for the VCF to work properly and it's not described properly in the current version of the documentaiton.  It will be fixed in the next release.

Anyway, your input genome names (as described in the seqfile) must have this convention

Rreference genome:  No dots in name
All other genome: NAME.HAPLOTYPE (where haplotype == 0 for haploid sample or 1/2 for diploid sample).  For example:

```
GRCh38 grch38.fa
HG002.1 hg002.1.fa
HG002.2 hg002.2.fa
```
This will produce a VCF referenced on GRCh38 with a single (diploid sample) for HG002, and the calls in the VCF will be phased according to the input sequences. 

If you don't want to re-align everything, you can use `halRenameGenomes` to enforce this before running `cactus-graphmap-join` or you can even use the `--rename` option in `cactus-graphmap-join`, ex `cactus-graphmap-join --rename "HG002_paternal>HG002.1" "HG002_maternal>HG002.2" `..

**Comment by MinngLi** [comment]
Thanks @glennhickey 

This issue has been resolved by renaming the input genome names.
