### ISSUE TITLE
vg sim hanging

### ISSUE THREAD

**Issue by StephenHwang** [vgteam/vg#3630]
**1. What were you trying to do?**
Simulate reads based on real FASTQ reads from a specific graph sample and ploidy-regex multi-threaded.

**2. What did you want to happen?**
 Create a gam file of simulated reads.

**3. What actually happened?**
`vg sim` would hang. While using compute resources, the output gam file would not be modified.

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

No stacktrace as no error is produced.

**5. What data and command can the vg dev team use to make the problem happen?**
See the files at `/public/groups/vg/sjhwang/vg_scripts/bin/reads/sim_multipath/test/multipath/concat/hanging/example/` for an example script and gam file output.

**6. What does running `vg version` say?**

```
vg version v1.39.0-49-gf2cc6c2d4 "Runzi"
Compiled with g++ (GCC) 11.2.0 on Linux
Linked against libstd++ 20210728
```

**Comment by adamnovak** [comment]
@StephenHwang We should make `vg sim` catch this and not hang, but the sampler is hanging because it is actually being asked to so something impossible here.

You are trying to sample very long reads, and you do not have `--allow-Ns` set. It is possible that some contigs do not have space between the Ns they contain to sample a read of the length you are trying to sample. In this case, the sampler will spin forever trying to find a place to start on the read where it can get enough characters without having any of them be Ns.

Specifically, when it goes to simulate what would be read `seed_1_fragment_4721`, it decides it needs a 18,617 bp read from the `chrUn_KI270589v1` path. That path is onloy about 44 kilobases long, and in particular the longest run of non-N bases is a bit under 16 kbp:

```
wget https://hgdownload.cse.ucsc.edu/goldenpath/hg38/chromosomes/chrUn_KI270589v1.fa.gz
gunzip chrUn_KI270589v1.fa.gz
cat chrUn_KI270589v1.fa | grep -v ">" | tr 'acgtn' 'ACGTN' | tr -d '\n' | tr 'N' '\n' | awk '{ print length, $0 }' | sort -n -s | cut -d" " -f2- > segments.txt
# See https://stackoverflow.com/a/5917762 for sort by line length
tail -n1 segments.txt | wc -c

15977
```

So unless it manages to sample a read with about 2 kilobases of insertions in it, it can't fit a read of that length onto this contig. But it's not willing to give up on either the read length or the contig it has sampled, to avoid introducing bias into the sampling.

@StephenHwang Would it make sense to pass `--allow-Ns` here, or do you think the analysis you want to do relies on avoiding N bases?

I'm not sure what we should make the simulator do in this situation. Maybe after a certain number of failures to sample a read because it contained Ns, it should scan the path and see if there actually is space to sample the read from among the Ns. Or, maybe it should give up after a certain large number of N-induced failures and try another contig?
