### ISSUE TITLE
arm docker image

### ISSUE THREAD

**Issue by JD12138** [vgteam/vg#3644]
Hi,
   Do you have a docker image which is suitable for arm architecture? Because my server is an arm architecture cluster. I have searched your images at https://quay.io/repository/vgteam/vg?tab=tags&tag=v1.39.0 .But I don't know which one is useful.

Thank you very much!

**Comment by adamnovak** [comment]
It looks like we don't actually run the ARM docker build even for releases, just for branches that start with "arm":

https://github.com/vgteam/vg/blob/04775076b010604589985efadb0d17c6c8519b25/.gitlab-ci.yml#L116-L145

I think this is because we don't have any real ARM hardware to do it on in our CI and it was taking forever. But we could probably spare the time for release tags.

Until then the easiest way to get an ARM Docker image might be to clone the vg repo and build with the Dockerfile on an ARM machine:

```
git clone --recursive https://github.com/vgteam/vg.git
cd vg
git checkout v1.41.0
git submodule sync
git submodule update --init --recursive
make include/vg_git_version.hpp
docker pull mirror.gcr.io/library/ubuntu:20.04
docker build --target run -f Dockerfile . -t vg:v1.41.0
```

Or if you have `buildx` set up you can replace `docker build` and do both platforms and push to a repo somewhere:
```
docker buildx build --platform=linux/arm64,linux/arm64 --build-arg THREADS=8 --target run --push -t "your.repo.biz/yourname/vg:v1.41.0" -f Dockerfile .
```

**Comment by adamnovak** [comment]
I tried to just do a build myself for 1.40.0, but the ARM emulator is unhappy and has decided that a bunch of files don't exist when they do:

```
 > [linux/arm64 build  2/16] RUN apt-get -qq -y update &&     apt-get -qq -y upgrade &&     apt-get -qq -y install sudo:                                                                                   
#36 29.80 debconf: delaying package configuration, since apt-utils is not installed                                                                                                                        
#36 30.27 Error while loading /usr/sbin/dpkg-split: No such file or directory                                                                                                                              
#36 30.28 Error while loading /usr/sbin/dpkg-deb: No such file or directory                                                                                                                                
#36 30.28 dpkg: error processing archive /var/cache/apt/archives/login_1%3a4.8.1-1ubuntu5.20.04.2_arm64.deb (--unpack):                                                                                    
#36 30.28  dpkg-deb --control subprocess returned error exit status 1                                                                                                                                      
#36 30.65 Errors were encountered while processing:                                                                                                                                                        
#36 30.65  /var/cache/apt/archives/login_1%3a4.8.1-1ubuntu5.20.04.2_arm64.deb                                                                                                                              
#36 30.77 E: Sub-process /usr/bin/dpkg returned an error code (1)  
```

I feel like I remember seeing this before, and it was caused by some kind of disagreement between glibc and the kernel, because the userspace in the container was trying to call a new syscall that the enclosing Docker didn't know about and didn't know was safe to report as not implemented by the host Kernel, but I can't find what I did about it the last time, so sadly I can't just hand you an image right now.

**Comment by adamnovak** [comment]
After https://ucsc-ci.com/vgteam/vg/-/jobs/17096 finishes, the Docker tag `quay.io/vgteam/vg:ci-364-4ec6e7b30f3f64a2300d52f2783e0fb578e11ace` should acquire an ARM version you can use.

The caveat is that I don't know that the ARM Linux version of vg actually passes all its tests yet; they aren't constrained by CI, and nobody develops for vg on ARM Linux (although some developers are on ARM Mac).

I'm also working on the ARM build for v1.40.0 again; I think the missing piece might have been to `sudo apt install qemu-user-static` on the host.

```
docker buildx build --platform=linux/arm64,linux/amd64 --target=build --build-arg THREADS=8 -f Dockerfile . && docker buildx build --platform=linux/arm64,linux/amd64 --target=run --build-arg THREADS=8 --push -t "quay.io/vgteam/vg:v1.40.0" -f Dockerfile .
```

**Comment by adamnovak** [comment]
OK, I pushed a `quay.io/vgteam/vg:v1.40.0` that is a multi-arch image. @JD12138 You ought to be able to try that on your sever.

**Comment by JD12138** [comment]
Hi,
   I downloaded your docker image  **quay.io/vgteam/vg:v1.40.0**.Then I tested if I can run ig on my arm server cluster.Here is my codes:
**singularity exec arm_vg.sif vg giraffe -h**
But there are errors as shown below:
**<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size**

Can you help me to figure out? Thanks!

**Comment by JD12138** [comment]
> Hmmm. Are those errors or warnings? Do you actually get the help text printed, and a zero exit status from the command? Or are those messages all you see?
> 
> We could try not building with jemalloc when doing the ARM builds, and just use the system allocator, as a workaround.

This is all the print messages which I can see. I don't know why.And I didn't get the help text.So I think I can't use this docker image on my cluster.

**Comment by JD12138** [comment]
> Hmmm. Are those errors or warnings? Do you actually get the help text printed, and a zero exit status from the command? Or are those messages all you see?
> 
> We could try not building with jemalloc when doing the ARM builds, and just use the system allocator, as a workaround.

This is all the print messages which I can see. I don't know why.And I didn't get the help text.So I think I can't use this docker image on my cluster.

**Comment by adamnovak** [comment]
@JD12138 I opened #3705 with what I think your problem is. Your system has a larger page size from the system we built vg on, and the allocator we use (jemalloc) can't handle that.

The workaround would be to change your kernel's page size to 4k, to match our build machines; I think Debian derivatives use 4k and Fedora uses 64k.

We'll look into producing ARM Docker images that support 64k page sizes for future releases.

**Comment by JD12138** [comment]
> @JD12138 I opened #3705 with what I think your problem is. Your system has a larger page size than the system we built vg on, and the allocator we use (jemalloc) can't handle that.
> 
> The workaround would be to change your kernel's page size to 4k, to match our build machines; I think Debian derivatives use 4k and Fedora uses 64k.
> 
> We'll look into producing ARM Docker images that support 64k page sizes for future releases.

OK. Thank you！
