### ISSUE TITLE
Making a graph with predetermined multiple sequence alignments

### ISSUE THREAD

**Issue by hgibling** [vgteam/vg#366]
Let's say I already know the multiple sequence alignment for some sequences, including where gaps are. Can vg use this information to make a graph?

Example:
```
>A
ATTTCGC-----AAA
>B
ATTTCGCTGGCCAAA
```

For this simple example, the default `msga` produces what I want (sort of--would make more sense if the gap node didn't exist and an edge directly connected nodes 1 and 5 instead):
```
vg msga -f gap-seqs.fasta -b A > gap-seq.vg
```
![screen shot 2016-05-31 at 1 30 39 pm](https://cloud.githubusercontent.com/assets/7570351/15684204/0be59806-2734-11e6-9d07-24119ca92805.png)

But more complicated examples are tricky:
```
>A
ATTTCGC-----AAACGTGCACTG
>B
ATTTCGCTGGCCAAA------CTG

vg msga -f gap-seqs2.fasta -b A -i 0 -o 0 > gap-seq2.vg
```
![screen shot 2016-05-31 at 1 34 15 pm](https://cloud.githubusercontent.com/assets/7570351/15684295/82857d32-2734-11e6-8b6f-7d9084687680.png)

Adding additional or long sequences results in errors:
```
error:[gssw] Stuck in main matrix!
vg: src/gssw.c:1199: gssw_alignment_trace_back_byte: Assertion `0' failed.
```
or
```
vg: path/to/vg/include/sdsl/int_vector.hpp:1351: sdsl::int_vector<<anonymous> >::reference sdsl::int_vector<<anonymous> >::operator[](const size_type&) [with unsigned char t_width = 1u; sdsl::int_vector<<anonymous> >::reference = sdsl::int_vector_reference<sdsl::int_vector<1u> >; sdsl::int_vector<<anonymous> >::size_type = long unsigned int]: Assertion `idx < this->size()' failed.
```

Is it possible to construct a graph of a multiple sequence alignment without `vg msga` trying to do the aligning?

**Comment by adamnovak** [comment]
If you already know what graph you want (because your sequences are already aligned), what you probably want to do is just convert the alignment you have into a graph, rather than redoing alignment with vg MSGA. The easiest way to do that is to parse your alignment and emit vg JSON, and then use `vg view -Jg` to convert the JSON into vg's native protobuf format.

@glennhickey is currently working on a HAL to VG importer that basically does this, so if you can convert your alignment to HAL, you should be able to use that. And since there is a `maf2hal` tool written already, you could convert your format -> MAF -> HAL -> VG.

**Comment by hgibling** [comment]
Yes, I ended up writing a script to output the msa into JSON.

**Comment by adamnovak** [comment]
It would be great if you could share the script; maybe we can put it in a `tools` or `contrib` directory somewhere in the vg repo.

Since you seem to have solved your problem, I'm going to close the issue. Please open another one if you run into any more trouble!

**Comment by hgibling** [comment]
I'll clean it up a bit--not sure how useful others will find it as it's in R, but I'm happy to share
