### ISSUE TITLE
Command line specification of minimizer index size

### ISSUE THREAD

**Issue by StephenHwang** [vgteam/vg#3735]
For HiFi long reads, longer minimizers (`k=63`) may be preferred. This requires a 128-bit minimizer index instead of the default 64-bit minimizer index, which only allows for `k` up to 31 bp. This change to 128-bit is made by switching which line is commented in the [gbwt dep](https://github.com/jltsiren/gbwtgraph/blob/fb473427c7c953b8181f03c669beedee169f8da9/include/gbwtgraph/minimizer.h#L1247-L1249).

It would be nice to have a command line flag for which bit size to use instead of having to edit code, but perhaps this may be difficult as it requires re-compiling code to switch indexes.

**Comment by StephenHwang** [comment]
@jltsiren and @adamnovak Is this a reasonable request?

**Comment by jltsiren** [comment]
We can use `MinimizerIndex<Key64>` and `MinimizerIndex<Key128>` explicitly instead of using `DefaultMinimizerIndex`. `MinimizerMapper` could hold both and decide at runtime which to use. Giraffe uses the minimizer index only in `MinimizerMapper::find_minimizers()` and `MinimizerMapper::find_optimal_tail_alignments()`, so it would not be a major change.

However, the bigger issue is that type `MinimizerMapper::Minimizer` contains `MinimizerIndex<KeyType>::minimizer_type`, which in turn contains `KeyType`. Large parts of `MinimizerMapper` would have to be converted to generic functions. It might be cleaner to have a separate implementation for the long read mapper instead of sharing the logic with the short read mapper.

As for serialization and loading, if you read `MinimizerHeader` from the start of the file, you can use member function `key_bits()` to determine the type of the index.
