### ISSUE TITLE
giraffe aligns a read to non-existing node/edges

### ISSUE THREAD

**Issue by ldenti** [vgteam/vg#3749]
**1. What were you trying to do?**
Align short reads with `vg giraffe`.

**2. What did you want to happen?**
The reads are aligned to an existing path of the graph or read is aligned with a clipped suffix (but maybe I'm missing something here and what I'm seeing is the expected behavior).

**3. What actually happened?**
One read is aligned to a path containing a non-existing node in the graph (in the data I'm using: node 44 is not present in the input graph, but read is aligned to `...>39>40>43>44>46`. Moreover, no input path has `..40+,43+..`).

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**
```
```

**5. What data and command can the vg dev team use to make the problem happen?**
Data: [data.tar.gz](https://github.com/vgteam/vg/files/9674623/data.tar.gz)

Commands:
```
vg autoindex --workflow giraffe -g graph.gfa -p graph
vg giraffe -Z graph.giraffe.gbz -f read.fq -o GAF
```

**6. What does running `vg version` say?**

```
vg version v1.43.0 "Barisano"
Compiled with g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0 on Linux
Linked against libstd++ 20210601
Built by anovak@octagon
```

**Comment by jltsiren** [comment]
In this case, the heuristics in `vg autoindex` guess that the GFA file does not contain haplotype paths. It's probably because the paths are P-lines instead of W-lines.

Based on the guess, `vg autoindex` converts the GFA to a VG graph and the VG graph to an XG graph. At this point, it apparently also chops long segments into 32 bp nodes. Then it builds a GBWT index for artificial haplotype paths and builds the data structures Giraffe needs using that GBWT. Because the segments were chopped into shorter nodes, the node identifiers in the graph do not match those in the GFA file. There is a translation stored in the GBZ graph, but I'm not sure if it can be used for translating the mappings at this point.

If you want to use the paths in the graph as the mapping target, you can build the indexes manually:

```
vg gbwt -g graph.gbz --gbz-format -p -G graph.gfa
vg snarls -T graph.gbz > graph.snarls
vg index -s graph.snarls -j graph.dist graph.gbz
vg minimizer -o graph.min -d graph.dist graph.gbz
```

(See https://github.com/vgteam/vg/wiki/Index-Construction and https://github.com/vgteam/vg/wiki/VG-GBWT-Subcommand for further details.)

In this case, the node identifiers also match the originals, because the chopping limit is 1024 bp instead of 32 bp.

It looks like you have 633 overlapping paths in the graph, which is more than the ideal for Giraffe. The best practice with more than ~200 haplotypes is downsampling them to 64 synthetic haplotypes. You can do that manually with `vg gbwt`, but it needs some ugly workarounds:

```
# Build a temporary graph.
vg gbwt -g temp.gbz --gbz-format -p -G graph.gfa

# Convert it to another format to avoid a bug.
vg convert -a temp.gbz > temp.hg

# Extract the GBWT from the temporary graph.
vg gbwt -o temp.gbwt -Z temp.gbz

# Downsample the haplotypes.
vg gbwt -x temp.hg -l -g graph.gbz --gbz-format temp.gbwt

# Build the other indexes as before.
vg snarls -T graph.gbz > graph.snarls
vg index -s graph.snarls -j graph.dist graph.gbz
vg minimizer -o graph.min -d graph.dist graph.gbz
```

`vg autoindex` should do that automatically, but here its heuristics would have failed again. Because your path naming scheme does not match any scheme VG is familiar with, it assumes that the paths are just arbitrary named paths. And because we recently chose to interpret named paths as contigs instead of samples, GBWT metadata says that there is only 1 haplotype in the graph, which would make downsampling unnecessary.

(The bug I mentioned in the second example is that `vg::algorithms::find_translation` does not handle GBWTGraphs that do not contain a node-to-segment translation correctly.)

**Comment by ldenti** [comment]
Thanks for the detailed explanation. It seems to work as expected now.

Regarding the number of paths, most of the paths are redundant so we can remove them. It's unlikely we'll have more than 50/100 unique paths. But in case, we can downsample them.

Thanks again. I close this for now.
