### ISSUE TITLE
Paths not included in xg index 

### ISSUE THREAD

**Issue by ekg** [vgteam/vg#3753]
Does the presence of a '#' is a path name trigger its exclusion from reference paths in the xg index? How can I force all paths (P-lines) to be used as paths in the xg?

**Comment by jltsiren** [comment]
What is the exact workflow where the issue occurs?

VG tries to parse path names and interprets the paths as either haplotype paths or generic named paths. There are also some mechanisms to promote (haplotype?) paths to reference paths. Some algorithms only use paths of a specific sense. Some graph implementations expose all paths through the `PathHandleGraph` interface. GBWTGraph only exposes generic and reference paths, because there could be far too many haplotype paths for most applications.

The situation with path senses is pretty complicated, and I'm not sure we have fully dealt with the consequences yet.
