### ISSUE TITLE
Can't run giraffe in an array job with sbatch 

### ISSUE THREAD

**Issue by IsaacDiaz026** [vgteam/vg#3966]
**1. What were you trying to do?**

Using vg giraffe to align fastq files to a genome graph created with minigraph. I was trying to perform these alignments in parallel using an array job submission via sbatch. The SBATCH parameters are below 

```
#!/bin/bash -l
#SBATCH --nodes=1
#SBATCH --ntasks=4
#SBATCH --mem-per-cpu=60G
#SBATCH --time=10-00:15:00
#SBATCH --job-name="002_giraffeAlign.sh"
#SBATCH --output=std/002_giraffeAlign.sh%j.stdout
#SBATCH --output=std/002_giraffeAlign.sh%j.stderr
#SBATCH -p seymourlab
#SBATCH --array=1-92
```

The command used  is 

```
vg giraffe -Z "$GRAPH" -f  "$SRA"_pass_1_val_1.fq.gz -f "$SRA"_pass_2_val_2.fq.gz -o gam > "$RESULTS"/"$NAME"_"$SPECIES"_toGraph.gam --report-name "$LOG"/"$NAME"_"$SPECIES".log.txt
```

**2. What did you want to happen?**
I wanted to align reads from each genotype separately per array job. There are 92 genotypes, and 92 jobs in the array submission. I expected the alignment of each genotype to begin once the specific job starts running. I expected the output GAM file to be created, and the file size to grow over time as reads are aligned.

**3. What actually happened?**
The first 3 / 92 jobs have been running for over 20 hrs, but only the GAM file for the first job is changing in size. The other two files have created the GAM file, but is still empty after 20 hours. However, watchdog warnings for each job are displayed in stderr as expected. 

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

```
Place stacktrace here.
```

**5. What data and command can the vg dev team use to make the problem happen?**

```
vg giraffe -Z "$GRAPH" -f  "$SRA"_pass_1_val_1.fq.gz -f "$SRA"_pass_2_val_2.fq.gz -o gam > "$RESULTS"/"$NAME"_"$SPECIES"_toGraph.gam --report-name "$LOG"/"$NAME"_"$SPECIES".log.txt
```

**6. What does running `vg version` say?**

```
vg version v1.46.0-43-g0d21fd306 "Altamura"
Compiled with g++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0 on Linux
Linked against libstd++ 20220421
Built by hickey@boreale
```

**Comment by jltsiren** [comment]
Try making the distance index file read-only and updating to vg version 1.47 or 1.48. The distance index is a memory-mapped file, and vg still opens it in read+write mode by default if the file is not read-only. That can cause issues in some distributed environments.

**Comment by IsaacDiaz026** [comment]
I have updated to 1.48 and changed the distance index to read only. Vg giraffe has been running for 2.5 days, is producing watchdog warnings in stderr, but currently the GAM files are empty. 

Should I expect the GAM file to increase in size as the alignment is being run? Or will it not show until the alignment is complete.

**Comment by jltsiren** [comment]
Normally, mapping a 30x human sample using 32 threads takes 1-10 hours, depending on the computer and the graph. That translates to roughly 500-5000 reads/second/thread, and the GAM file should grow at a steady pace. If your mapping speed is much slower than that, something is likely wrong. I mentioned some of the details that could help solving the situation in #3954.

I'm not familiar with Slurm beyond using it to launch single tasks. However, it looks like you are not specifying how many threads `vg giraffe` should use. By default, Giraffe uses one mapping thread for each CPU core it can see. If you run multiple Giraffe jobs on a 128-core server, each of them will try to use 128 mapping threads, regardless of sbatch parameters. You can change the number of mapping threads with `vg giraffe` option `-t` / `--threads`. (`export OMP_NUM_THREADS=<threads>` should also work.)

Also, because you specified only the GBZ graph in the `vg giraffe` command, Giraffe will try to guess the filenames for the distance index and minimizer index, build new indexes if it can't find them, and write the new indexes to files where the guessing mechanism can find them. If the indexes are missing, the behavior can be unpredictable if multiple jobs are trying to do this simultaneously. Specifying the index files with `-m` / `--minimizer-name` and `-d` / `--dist-name` is a good habit.

Another thing that can go wrong is using a manually built minimizer index without distance index annotations. That makes Giraffe very slow. You can avoid the issue by building the indexes with `vg autoindex`, by letting Giraffe build the indexes, or by using `vg minimizer` option `-d` / `--distance-index`.

**Comment by IsaacDiaz026** [comment]
It turns out that setting the distance index to read only solved the issue.  Thanks!

**Comment by DongyaoLiu** [comment]
I am also encountering the same problem. I work with slurm. I test to throw single job. It runs fast mapping around 2hrs. But when I use job array and cast 80 jobs which containing the same I test in single one to slurm system. All of them run very slow. Did you test your in job in single one submission? I think they would work fine and fast. Base on my experience. My cluster supporter told me maybe the IO problem. But I don't think so. Even I use job array to activate 5 jobs at same time. All of them run very slow. So.. the problem maybe the slurm. Do you think this maybe cause we are using pre-compile bin will act a little bit different by comparing with the bin compiled on our linux?
