### ISSUE TITLE
Documentation re: vg giraffe and vg surject multimapping/qual adjusting

### ISSUE THREAD

**Issue by JosephLalli** [vgteam/vg#4019]
Coming from a short read human linear reference genome background, there are a handful of settings that I have questions about. Specifically, I can't seem to find thorough information about two options:

``` --max-multimaps (giraffe), --multimap (surject) ```

Besides the obvious (these settings enable the creation of secondary alignments), how do these settings impact alignment performance? Does eliminating multimapping noticeably speed up alignment? How do these settings compare with default settings/assumptions in current state-of-the-art linear reference aligners like bwamem? Is there a reason why one might want to eliminate secondary reads when aligning to graphical genomes?

Secondly, I can't find much about the --qual-adj option in vg surject, but from the commit notes it seems like this is an option with no downside. Should researchers aligning short reads to the draft human pangenome reference always use the --qual-adj option when surjecting?

Thanks,
Joe

**Comment by jeizenga** [comment]
The distinction is subtle, but these options do pretty different things. `--max-multimaps` will report secondary alignments in addition to the primary alignment. These alignments will be at different locations in the graph. In contrast, `vg surject` never selects a different location for a read to be aligned to. It only realigns off-path portions of the alignment onto a reference path. In some cases, you might have multiple reference paths that overlap each other (e.g. GRCh38 and its alt scaffolds) so that you can align to multiple paths, all of which are in essentially the same location. In these cases, you can use `--multimap` to report alignments to all of the overlapping paths. By default, only the highest-scoring alignment is reported.

In both cases, I don't think these options will greatly affect run time. Internally, both tools are already doing multimapping in order to find the best alignment (both tools) and estimate mapping quality (just `giraffe`). These options are more about what results are reported. 

It probably won't matter if you use `--qual-adj` with alignments from `vg giraffe`. Since `vg surject` doesn't move reads around, it generally only has one possible alignment of the read onto the reference path, with or without `--qual-adj`. The real reason to use `--qual-adj` is to keep your alignment scores consistent with the tool you used to map the reads. By default, `vg map` and `vg mpmap` use base quality adjustments in the alignment process. We have not implemented quality adjustment in `vg giraffe`, so it's probably best not to use `--qual-adj`. However, it only really matters if you expect to use the alignment scores downstream, which most users do not.

**Comment by JosephLalli** [comment]
Thank you! This is very helpful. I'm trying to run vg giraffe in a manner as similar to a reference genome alignment pipeline as possible. 

From what I can tell, bwa-mem2 will report the number of secondary alignments, but will not create separate entries for those alignments. (If I'm wrong about that, please let me know.) So, I'll just leave --max-multimaps set at 1. For my purposes, --qual-adj and --multimap both seem fine to ignore.
