### ISSUE TITLE
Only one haplotype in information.txt file which is one of output from vg rna

### ISSUE THREAD

**Issue by jjuhyunkim** [vgteam/vg#4084]
**1. What were you trying to do?**
Generate pantranscriptome graph with vg rna

**2. What did you want to happen?**
Generate pantranscriptome graph with vg rna

**3. What actually happened?**
It doesn't omit error, but I thought the result looks weird.

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**
No Error. Please see the figures I attached in this issue.

**5. What data and command can the vg dev team use to make the problem happen?**
`vg rna -p --transcripts test.gtf --use-hap-ref --gbz-format -b test.bgwt -i test.txt test.gbz > test.pg`

**6. What does running `vg version` say?**
`Crash report for vg v1.50.1 "Monopoli"`

Hi,

When I generate a splicing graph with the gbz file generated from minigraph-cactus using the vg rna command line, only one haplotype, especially the used as reference in minigraph-cactus, remains in the information(test.txt) file(hereafter text.txt or information file), which has transcripts-haplotype and haplotype pairs for running rpvg.

Here is the command line and a preview of the file after running the command line.

`vg rna -p --transcripts test.gtf --use-hap-ref --gbz-format -b test.bgwt -i test.txt test.gbz > test.pg`

<img width="684" alt="스크린샷 2023-09-13 오후 1 33 21" src="https://github.com/vgteam/vg/assets/131193680/cfe61654-723b-434f-b512-7f0c4dc329bf">

As you can see, at the last line, I could get the reference haplotype only in 4th column of test.txt(information) file ( I used `cut -f 4 | sort | uniq test.txt`) and one reference path in splicing.pg graph(please see the 2nd results "MAT#0#chr20"), but there are 3 paths in my gbz file.(When check with `vg paths -L -x gbz`)

Additionally, is it correct if the number of haplotypes in gbwt (checked with `vg gbwt -M`) matches the line number of information file, and if the number of paths should be the same in graph.xg, the SQ header in the gamp file, and the unique numbers of transcripts in the information file?
<img width="465" alt="스크린샷 2023-09-13 오후 1 14 23" src="https://github.com/jonassibbesen/rpvg/assets/131193680/68524942-f9ac-4bf9-b1d8-1b089dee42d0">

Thank you!
Best,

JH Kim

**Comment by jjuhyunkim** [comment]
I could send my inputs to the development team if you need them. Additionally, it would be helpful to me if you could send a GTF file and a minimap-cactus gbz file for testing and for examining the formats.

**Comment by jeizenga** [comment]
I believe the issue is that you provided the `--use-hap-ref` option. That option is intended for cases where you've made your own annotation of the haplotypes, in which case you provide the annotations as GTF(s) with the `--transcripts` flag. If you remove `--use-hap-ref`, then `vg rna` will attempt to project the reference annotations onto the haplotypes. However, dedicated external tools may do a better job of lifting the annotations over.

The fact that you got the same count for some of these outputs is an artifact of having no non-reference transcripts. In general, the correspondence will be:
- paths in XG: 1 per reference path
- paths in haplotype GBWT: 1 per haplotype and 1 per reference path
- rows in info table, paths in pantranscriptome GBWT: 1 per HST and/or reference transcript
- unique entries in column 4: 1 per combination of reference and/or haplotypes

Also, GAMP files don't have headers, so there are no SQ lines.

**Comment by jjuhyunkim** [comment]
Thank you for fast response! 

According to the 'Construct the pantranscriptome' section on [this page](https://github.com/vgteam/vg/wiki/Transcriptomic-analyses), the `--use-hap-ref`option was included with `--transcript`. However, are you saying that I could run the command just with `--transcript` without `--use-hap-ref`?

**Comment by jjuhyunkim** [comment]
So if I want to make the input files in the same format as the `rpvg` test data, is this command line correctly used?

`vg rna -p --transcripts test.gtf --gbz-format -b test.bgwt -i test.txt test.gbz > test.pg`

Or is it:

`vg rna -p --transcripts test.gtf -e --gbz-format -b test.bgwt -i test.txt test.gbz > test.pg`

Regarding the SQ header, I meant it in BAM file after converted the gamp to bam to take a look at the format. Thank you for clarifying.

**Comment by jeizenga** [comment]
Yes, the `--use-hap-ref` is not required. In fact, if you haven't annotated the haplotypes, you should probably never use `--use-hap-ref`. The purpose of `--use-hap-ref` is to indicate that the GTF file(s) include annotations that are expressed against haplotypes instead of the reference (so that you "use haplotypes as a reference"). We should highlight this more on the wiki page. 

I'm pretty sure you would not use the `-e` option, but not 100% sure. I believe that option is for projecting onto labeled paths in the graph (which are usually reference sequences), whereas you would want to project onto haplotype paths in the GBZ.

**Comment by jjuhyunkim** [comment]
Thank you so much.

I'll proceed with this command line, and I'll leave a comment regarding whether I obtain the desired output or not later (within 2 days).

**Comment by jjuhyunkim** [comment]
And could you please explain more about `--use-hap-ref`?

I used minigraph cactus with two haplotype of one sample and CHM13(haplotype) as reference. And use the annotation of CHM13.

**Comment by jeizenga** [comment]
You would not use `--use-hap-ref` then. The case when you'd use it is if you had used a tool like CAT, or liftOff to generate a GTF for each individual haplotype.

**Comment by jeizenga** [comment]
Based on email correspondence, I believe this particular issue is resolved. Feel free to re-open it if I've misinterpreted it.
