### ISSUE TITLE
VG 1.52.0 `autoindex`' GBZ construction is malforming path names

### ISSUE THREAD

**Issue by subwaystation** [vgteam/vg#4153]
**1. What were you trying to do?**
I wanted to build all indices for mapping with giraffe.
```
vg autoindex -p lodelo_B2 -w giraffe -g lodelo_vg.gfa -t 28
```

**2. What did you want to happen?**
That the resulting indices and especially the GBZ graph contain properly named `REFERENCE` and `HAPLOTYPE` paths.
I expected path names like
```
lodEloB2#0#chrA
lodEloA1#0#contig_11#0
lodEloA1#0#contig_44#0
lodEloA1#0#contig_45#0
lodEloA1#0#contig_46#0
lodEloA1#0#contig_47#0
lodEloC0#0#contig_32#0
```

**3. What actually happened?**
```
vg paths --metadata -x lodelo_B2.giraffe.gbz
```
shows me totally weird path names:
```
#NAME	SENSE	SAMPLE	HAPLOTYPE	LOCUS	PHASE_BLOCK	SUBRANGE
0#0#0#0	HAPLOTYPE	0	0	0	0	NO_SUBRANGE
1#0#0#0	HAPLOTYPE	1	0	0	0	NO_SUBRANGE
2#0#0#0	HAPLOTYPE	2	0	0	0	NO_SUBRANGE
3#0#0#0	HAPLOTYPE	3	0	0	0	NO_SUBRANGE
4#0#0#0	HAPLOTYPE	4	0	0	0	NO_SUBRANGE
5#0#0#0	HAPLOTYPE	5	0	0	0	NO_SUBRANGE
6#0#0#0	HAPLOTYPE	6	0	0	0	NO_SUBRANGE
7#0#0#0	HAPLOTYPE	7	0	0	0	NO_SUBRANGE
8#0#0#0	HAPLOTYPE	8	0	0	0	NO_SUBRANGE
9#0#0#0	HAPLOTYPE	9	0	0	0	NO_SUBRANGE
10#0#0#0	HAPLOTYPE	10	0	0	0	NO_SUBRANGE
11#0#0#0	HAPLOTYPE	11	0	0	0	NO_SUBRANGE
```

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

```
Place stacktrace here.
```

**5. What data and command can the vg dev team use to make the problem happen?**
The actual command I already put above. I can't share the input graph publicly, but I am happy to send it to you via mail.

**6. What does running `vg version` say?**

```
vg version v1.52.0 "Bozen"
Compiled with g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0 on Linux
Linked against libstd++ 20230528
Built by jeizenga@emerald
```

Thanks for any feedback!

**Comment by subwaystation** [comment]
I got the current path naming scheme from https://github.com/vgteam/vg/wiki/Path-Metadata-Model#data-model.

**Comment by jltsiren** [comment]
How many haplotypes were in the original graph, and what is the largest sample number in the GBZ graph? Were the haplotypes P-lines or W-lines, and if they were P-lines, what was the naming scheme they used?

`vg autoindex` can do many kinds of transformations to make the graph better suited for Giraffe. If you want to map reads to a specific graph with specific haplotypes, it's better to create the GBZ directly from the GFA with `vg gbwt` and then build the indexes manually.

**Comment by subwaystation** [comment]
In total there are 11 haplotypes in the original graph. One of these 11 is what we perceive as the reference. The largest sample number is 15. 
The graph was built with PGGB, so only P-lines. The naming scheme used following the recommendations in  https://github.com/vgteam/vg/wiki/Path-Metadata-Model#data-model:

```
lodEloB2#0#chrA --> REFERENCE
lodEloA1#0#contig_11#0 --> HAPLOTYPE
lodEloA1#0#contig_44#0 --> HAPLOTYPE
lodEloA1#0#contig_45#0 --> HAPLOTYPE
```

I am happy to do this manually, do you have a link to some tutorial? Thanks!

**Comment by jltsiren** [comment]
Do you also have reference paths in the GBZ graph or only paths with numerical names?

It looks like `vg autoindex` guesses that because the GFA file contains no W-lines, it does not contain any haplotypes. Therefore it uses the vg algorithm for reading the GFA instead of the GBWTGraph algorithm. It builds a graph with all the paths in the GFA, and assigns the paths senses according to the first matching name pattern. Then it builds a GBWT with all reference and generic paths from the graph. Instead of including the haplotypes (which it thinks do not exist), it builds a path cover GBWT with 16 arbitrary paths per graph component. Then it uses that GBWT as a basis for the GBZ graph.

If you want to try building the indexes manually, there is some documentation in the wiki:
* https://github.com/vgteam/vg/wiki/VG-GBWT-Subcommand
* https://github.com/vgteam/vg/wiki/Index-Construction

If you have a reasonable GFA, the following commands should be enough for building the indexes:
```
vg gbwt -p -g graph.gbz --gbz-format -G graph.gfa
vg index -j graph.dist graph.gbz
vg minimizer -p -d graph.dist -o graph.min graph.gbz
```
VG should use a reasonable number of threads by default. If it doesn't, you can try adding `--num-jobs X` to `vg gbwt` and `-t X` to `vg minimizer`, or limiting the number of CPU cores visible to OpenMP. Note that the number you specify for `vg gbwt` is the number of parallel GBWT construction jobs, each of which uses 1-2 threads on the average.

I'm not sure if `vg gbwt` supports the default vg naming scheme. If it doesn't, the easiest solution is converting the graph to use W-lines and specifying reference sample(s) in the header:
```
H	VN:Z:1.1	RS:Z:GRCh38 CHM13
```

Alternatively, you could convert path names to PanSN and try using the `gfa2gbwt` tool included with GBWTGraph:
```
gfa2gbwt -p --parallel-jobs 16 --pan-sn graph
```
The command reads `graph.gfa` and writes `graph.gbz`. It should recognize reference samples from GFA header. The number of parallel jobs is again the number of GBWT construction jobs.

**Comment by subwaystation** [comment]
Found some explanation at https://www.biostars.org/p/9567587/.

**Comment by jltsiren** [comment]
Part of the problem is that there are two path metadata models in vg:

* vg / libhandlegraph model: Each path has a string name, which can be parsed and interpreted.
* GBWT / GBZ model: Each path is a haplotype with a structured name. A special sample name has been reserved to support generic paths with opaque string names. Any sample can be promoted to reference status at any time by specifying its name in a tag in the GBWT index.

Both kinds of graphs support the same metadata interface. The key difference is that no path in a GBZ graph is inherently a reference path. Being a reference is a property of the sample, not the haplotype, and that can change without changing the path metadata itself.

**Comment by subwaystation** [comment]
I see, thanks.
Does this also mean I could make all paths in a GBZ reference paths without increasing storage? Would that slow the data structure somehow?

**Comment by jltsiren** [comment]
There is a time overhead for reference paths when loading the data structure. The loading code traverses all reference paths to cache some information needed to support the `PathHandleGraph` interface. Some applications also have a space overhead, because they create a random access overlay for all reference paths.
