### ISSUE TITLE
Studying allele-biased expression with VG

### ISSUE THREAD

**Issue by AlineMuyle** [vgteam/vg#4199]
Hi,
I study allele-biased expression (when the two haplotypes of an individual are biologically expressed differently) using RNA-seq short read data. My analyses suffer from reference allele bias, which is why I became interested in using VG.
I have RNA-seq data from multiple individuals of a population and I would like to obtain allele counts at each SNP and individual after correcting for reference mapping bias. A recurrent issue with this kind of analyses is that often the same allele is expressed at a lower lever in all individuals. Many genotypers miss some alternative alleles because they have lower RNA-seq read counts than the reference allele. Do you have a solution to account for allelic expression bias in VG?
Thank you in advance for your help!
Best wishes

**Comment by jeizenga** [comment]
Am I understanding correctly that you are also trying to genotype the individual using the RNA-seq data (rather than separate genomic DNA)? If so, I do think the confounding effect between allele-biased expression and genotype is pretty fundamental, and it remains a challenge in `vg`. The most straightforward way around this issue is to use genomic DNA sequencing to determine the genotypes.

That said, there are some methods in `vg` you can use in this situation if you don't mind restricting to common, polymorphic variants. The `vg mpmap`-`rpvg` pipeline can be used to infer a posterior distribution over haplotype combinations and their expression. The haplotype distribution can be marginalized into a posterior over variants (and likewise for the haplotype expression). The fact that the space of common haplotypes is known a priori gives you a leg up over methods that discover the variants de novo. 

You can see an example of this kind of analysis in figure 4 from our paper:
https://www.nature.com/articles/s41592-022-01731-9

**Comment by AlineMuyle** [comment]
Thank you very much for your answer, indeed I would like to genotype the individuals and study allele expression. Your explanations are useful for my research thanks a lot.
