### ISSUE TITLE
Catch exceptions in main()?

### ISSUE THREAD

**Issue by elfring** [vgteam/vg#43]
I expect that exception handling is usually supported by a C++ program. I wonder why your function "[main](https://github.com/ekg/vg/blob/d9b3e2ae99a90c75d5657f831c4733952231a027/main.cpp#L2850 "main function")" does not contain [corresponding try and catch instructions](http://stackoverflow.com/questions/368184/does-it-make-sense-to-catch-exceptions-in-the-main "Does it make sense to catch exceptions in the main(…)?") so far.

How do you think about recommendations by Matthew Wilson in [an article](http://accu.org/index.php/journals/1706 "Quality Matters #6: Exceptions for Practically-Unrecoverable Conditions")?

Would you like to adjust the implementation if you consider [effects for uncaught/unhandled exceptions](http://www.informit.com/guides/content.aspx?g=cplusplus&seqNum=108 "stack unwinding") like they are described by Danny Kalev?

**Comment by ekg** [comment]
I absolutely agree. The reason it doesn't is time.

Thus far I am a single person producing the "first" public and open source
graph reference system. (Thank you Wellcome Trust for my PhD stipend!) So I
can use all the help I can get...

That said people are now starting to pitch in and that is making it a
really exciting time to be working on this project.

If you are concerned about this please propose a patch! I would appreciate
it greatly. I am currently blocked more severely by other issues. This one
hasn't been too great, yet. But it will be as more users work with the
system.

That said, even if you don't have time to contribute, is there a particular
pattern you would like to follow?

**Comment by ekg** [comment]
@adamnovak @glennhickey --- we should probably consider this.

**Comment by adamnovak** [comment]
I looked into adding a useful exception handler that would print nice stack traces, but it seems that the standard library backtrace functions for inspecting the stack don't really play well with the OpenMP threading that we use. In general, exceptions aren't supposed to cross OpenMP section boundaries, but of course it would be completely horrible to cram in some kind of all-purpose exception-in-thread-but-we-can't-stop-the-whole-program-here catch logic every time we add in a `#pragma omp parallel`. I think g++ adds some uncaught exception code that kills the program, and that's probably as much as we can hope for.

I'm going to close this; we can't really do a generic exception handler the right way, and moving all our error reporting logic to main instead of leaving it where the errors are happening (with our current cerr-and-exit(1) pattern) seems like a bad idea. But if someone comes up with a good way to effectively use exceptions for all our errors and have nice and useful error output, it would be good to include. Obviously killing the whole program every time you don't like something about a graph is horrible behavior if you're a library.
