### ISSUE TITLE
vg sim is very slow when simulating long alignments

### ISSUE THREAD

**Issue by shilpagarg** [vgteam/vg#667]
Simulating true pacbio reads from graph takes more than 30 mins:

vg sim -a -s 1337 -n 200 -e 0.3 -l 10000 -x true_hap1.xg

**Comment by ekg** [comment]
The problem here is that we pay a lot to introduce errors into the read
while recording the true alignment (accounting for the errors).

There are a few ways we might be able to solve this.

1. We simulate perfect reads, then introduce errors after the fact using
something like simlord.

2. We accept the slow implementation but make it run faster by simulating
the reads in parallel.

3. We don't bother with the alignment editing for the errors, but do edit
the sequence of the read. This would be a lot faster and vg map --compare
would still basically work.

**Comment by ekg** [comment]
@shilpagarg running without `-e 0.3`, I find this to be very quick. The problem is in the way that the edits representing errors must be introduced into the read. I will see if there is anything obvious I can fix to make this faster while still recording the alignment as it relates to the errors. Otherwise, we can introduce a mode that introduces the errors only in the sequence of the read.

**Comment by ekg** [comment]
The problem was in a bit of code that is only called when the errors are introduced, but it wasn't what I thought it was. An expand_context call to the index was being called for every mapping, causing exponential slowdown on long reads. Will push a fix shortly.
