### ISSUE TITLE
vg index: Size limit exceeded

### ISSUE THREAD

**Issue by grthb** [vgteam/vg#769]
Hi,

I'm working with a smallish genome (34Mb), but struggling to get an index built.

Using a version of vg downloaded on 13th April, following instructions on the wiki 'working with...' page, I can get the xg file made, but when trying to generate the GCSA2 index I get:

$ ~/vg/bin/vg index -g 1-6MR.gcsa -Z 15 -X 3 -t 4 $(for i in $(seq 1 6; echo M; echo R); do echo -n " -i $i".graph; done)
PathGraphBuilder::write(): Size limit exceeded, construction aborted

I'm guessing I should try this with something bigger than my laptop, but I assumed that for something on this scale memory wouldn't be too much of a constraint.

Am I doing something wrong, or is there a workaround for this?

TIA for any hints!

**Comment by jltsiren** [comment]
The `-Z` parameter is not really a memory limit, but a limit to the size of the temporary graph on disk. Because you have 8 graph files, you are probably using several times less memory than 15 gigabytes, so you can try increasing the limit. Parameter `-p` adds some progress information, which may help understanding the situation.

In general, the size limit only stops the construction when the graph grows too large. It does not change the indexing behavior in any other way. If you are willing to use N gigabytes for temporary files, you should set the limit to N/2 gigabytes. If an individual chromosome ends up taking more memory than you have, the construction just crashes, which is pretty harmless.

On the other hand, some graphs contain complex regions that may generate a ridiculous number of kmers. Without the limit, those kmers might eat up all your disk space, regardless of whether it is measured in gigabytes, terabytes, or petabytes. Such graphs cannot be indexed without pruning them.

**Comment by grthb** [comment]
Hi - Increasing the -Z allowance fixed it.

Many thanks for the quick response!
