### ISSUE TITLE
building on Linux with linuxbrew

### ISSUE THREAD

**Issue by jq2252** [vgteam/vg#820]
Will the building on Linux with linuxbrew be added in the future.
For users who didn't have root access, they will use linuxbrew to store dependencies. 
The package names will be different from the those installed by yum/apt-get, and also be different from the homebrew for MacOS. 
For example, I will try to install raptor with linuxbrew  (there might be similar situation for other packages)

==> Downloading http://download.librdf.org/source/raptor2-2.0.15.tar.gz
Already downloaded: /home/username/.cache/Homebrew/raptor-2.0.15.tar.gz
==> ./configure --prefix=/home/username/.linuxbrew/Cellar/raptor/2.0.15
==> make install
Last 15 lines from /home/username/.cache/Homebrew/Logs/raptor/02.make:

....//srcsrc//..libslibs//libraptor2.solibraptor2.so::  undefinedundefined  referencereference  toto  ``xsltGenericErrorContextxsltParseStylesheetDoc@@LIBXML2_1.0.24LIBXML2_1.0.11''

....//srcsrc//..libslibs//libraptor2.solibraptor2.so::  undefinedundefined  referencereference  toto  ``xsltParseStylesheetDocxsltSetDefaultSecurityPrefs@@LIBXML2_1.0.11LIBXML2_1.0.22''

....//srcsrc//..libslibs//libraptor2.solibraptor2.so::  undefinedundefined  referencereference  toto  ``xsltSetDefaultSecurityPrefsxsltGenericError@@LIBXML2_1.0.22LIBXML2_1.0.24''

../src/.libs/libraptor2.so: undefined reference to `xsltGenericError@LIBXML2_1.0.24'
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
make[1]: *** [rdfdiff] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [rapper] Error 1
make[1]: Leaving directory `/tmp/raptor-20170612-74056-it6sdp/raptor2-2.0.15/utils'
make: *** [install-recursive] Error 1

READ THIS: https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
Please do not report this issue to Homebrew/brew or Homebrew/core, which support macOS only.

**Comment by adamnovak** [comment]
We definitely support building vg with libraries installed in non-standard locations (like inside one's home directory), *as long as* the appropriate environment variables are set to include the directories where the libraries or required commands are installed. Assuming Linuxbrew does that, everything should work when building vg normally using dependencies from Linuxbrew.

My system, where a bunch of vg dependencies (including the compiler) are installed in my home directory, has all these environment variables set:

```
CPLUS_INCLUDE_PATH
C_INCLUDE_PATH
INCLUDE_PATH
LD_INCLUDE_PATH
LD_LIBRARY_PATH
LD_RUN_PATH
LIBRARY_PATH
PATH
PKG_CONFIG_PATH
PYTHONPATH
```

The error you've posted here looks to be due to a problem that Linuxbrew is having installing Raptor. vg depends on Raptor, but it's not really vg's problem if your chosen method of installing Raptor does not succeed; I can vouch for being able to install Raptor manually from source using the normal `./configure --prefix=<where to install to>; make; make install` method, but I've never tried to install it through Linuxbrew. You probably want to report that particular error to either the Raptor devs, or whoever maintains the Linuxbrew Raptor port.

We can consider packaging vg for Linuxbrew if the dependncies are there, but I don't think our project necessarily has the resources to package or maintain the packaging of all of vg's dependencies. I'm going to close this as wontfix, but feel free to re-open if you can get all the dependencies installed via Linuxbrew, and we can think about writing a vg Linuxbrew port.
