### ISSUE TITLE
Unifying or interoperating between vg trace and vg chunk

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#848]
@wolfib is using `vg chunk` to pull out reads and graph regions to display on his visualizer, but only `vg trace` can get the locally distinct gPBWT threads in a region.

We should probably add that functionality into `vg chunk`.

**Comment by adamnovak** [comment]
@yoheirosen wrote vg trace originally.

**Comment by wolfib** [comment]
Thanks Adam!

The tubemaps code parses vg's json-format, but those files can easily get too big to be handled by the browser. That's why my current approach is to create smaller subgraphs with vg, transform them into json and then have the browser work with that data.

For visualisations without reads, showing only nodes and paths/haplotypes I'm using the following command:
`vg trace -x inputfile.xg -n nodeID -d distance -j outputfile.json`
In addition to the graph itself in outputfile.json this command creates a file outputfile.json.annotation which contains the frequencies of the haplotypes tubemaps uses for determining the path widths.

For visualisations including reads I'm using
`vg chunk -x inputfile.xg -a gamIndexDirectory -g -p pathname:nodeID-nodeID -i -c distance | vg view -j - >outputfile.json`
This works with one dataset that I have, but only pulls out the ref haplotype in another case. If I understand @adamnovak correctly, vg chunk does not pull out embedded haplotype threads.

It would be great if there was a way to define a region (via nodeID and distance) and then get the corresponding subgraph including all haplotypes and reads in that region.

In addition, the vg chunk command currently requires a valid pathname as an argument. It would be great if that wasn't necessary when you're interested in all paths (There's probably a better way to do this, but right now I'm creating a json of the whole graph and the grepping it for path names).

**Comment by glennhickey** [comment]
I updated vg chunk's interface so you don't need the path name when looking
for id ranges.  It now has similar options to vg find to get id ranges
directly.

(FWIW The main difference between chunk and find, is that chunk can create
many chunks in parallel, as well as return bed files keeping track of path
offsets.  chunk will also be more efficient at getting a sub-graph and
sub-gam in one shot)

I'll take a look at adding the trace functionality today.

**Comment by wolfib** [comment]
That's great, thanks! I already took a quick look at the new `vg chunk -r` option and it seems to work for me.

**Comment by glennhickey** [comment]
Fixed in #853. @wolfib let me know if you have any problems or want the interface tuned.
