### ISSUE TITLE
Examine reads with scores worse than simulated alignments' scores

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#880]

**Comment by adamnovak** [comment]
OK, on top of Erik's new mapper, I found a problem with read pair `1cf6d11ad788744d` in the Jenkins BRCA1 test.

```
kolossus 2017-07-28 11:10:56,434 MainThread WARNING vgci: Read 1cf6d11ad788744d_1 has a negative score increase of -102 on graph snp1kg-pe vs. input
```

Basically one end is not mapping when we re-map against the graph it was generated from with paired-end mode on.

The problem goes away if you set almost any paired-end distribution in `vg map` with `-I`.

I worked out that this is because, when no distribution is set, the mapper remains agnostic about what orientations of MEMs it is willing to chain. So it creates a bunch more links between vertices in the MEM chainer, and I think it exhausts `max_connections` before it considers the connection from read 1's clump to read 2's clump. So there's no cluster that maps both ends of the read, so we get a result where one read just isn't mapped.

@jeizenga @ekg How does the MEM chainer know that orientations mean the same thing across nodes without connecting them in the graph? I'm worried this logic is going to get very confused where a read or pair spans a change in the local forward direction.

Is the right approach maybe just to up `max_connections`? It seems to solve this read, but I suspect it's there to control combinatorial explosions at scale.

**Comment by ekg** [comment]
We need a method that can take two positions in the graph and efficiently tell us the relative orientation and distance between them. In absence of this we are going to have the problem that you describe and there is not much we can do about it. On the other hand, this is a relatively modular change that we would have to make and then reflect in the MEM chainer (and Alignment chainer) in order to improve performance.

Also, it deserves to be noted that it will be very hard to get the right behavior chaining the MEMs between fragments if we don't have a fragment model. We'll need to permit everything in this context. Any ideas about how to do this?

We can up max_connections, but you are right that this is there to prevent combinatorial explosions when our MEMs end up in certain kinds of repeats. How far are you increasing it?

**Comment by jeizenga** [comment]
Well, you're in luck because I already wrote that function!
https://github.com/vgteam/xg/blob/master/src/xg.hpp#L239

On my branch, I also have a clusterer built around this function that I'm pretty happy with so far. It doesn't have paired end logic yet, but it could be modularized a bit to fit into your clustering code. Right now it also only supports QualAdjAligners, but that wouldn't be hard to change.
https://github.com/jeizenga/vg/blob/multipath-alignments/src/multipath_mapper.hpp#L120

The basic idea of mine is that it treats distances as transitive (technically untrue on a graph, but nearly true on our graphs) so that you only need to actually measure one distance between a MEM and the other MEMs on the same strand of the same chromosome. Of course, you don't know which MEMs you need to measure the distance from a priori, but it has a scheme that uses block ciphers and some neat Erdos-Renyi random graph-inspired theory to measure them all in N log N distance queries (N = number of MEMs). There's actually no quadratic component in it, although there's one part where I couldn't figure out a way to get around a N log^2 N subroutine.

**Comment by ekg** [comment]
@jeizenga exactly :)

My only concern is the performance of the queries on the positional paths. If we can achieve similar runtime to the current approach then I'm all for it.

If the graph is groomed and partially ordered then we won't have problems with the current (approximate) solution in which each MEM has an approximate position in the same coordinate space.

I don't know if we can expect to be clustering through non-ordered regions of the graph, although we can use alignment to find the optimal path through them.

Let's talk about this.

**Comment by adamnovak** [comment]
I'm just going to work on this all the time; I don't expect to get this done in a week.
